[package]
name = "d2-net"
description = "Transport for d2-proto messages (in-memory for local play, network for online)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
d2-proto.workspace = true

[lints]
workspace = true
