[package]
name = "d2-formats"
description = "Readers for D2 file formats: MPQ, DC6, DCC, DT1, DS1, COF, palettes, string tables."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
