// Spec: specs/sim/tick.md §3, §4, §5; specs/monsters/population.md §1.1, §11.1; specs/monsters/init.md §4, §5; specs/monsters/ai.md §2; specs/drlg/preset.md §3.2, §8, §9 (end to end)
//! End to end: a game whose act DRLG was created through the level-type
//! dispatcher, a preset level generated by the real generator, two of
//! its rooms streamed, then `d2_sim::tick::tick` through [`WorldSim`]:
//! the room pass populates the rooms (the DS1's preset monster and the
//! room population of `population.md` §3 on the real coordinate lists,
//! created by monster init on the game seed), the preset monster's think
//! runs through
//! the action dispatcher. Twice from the same seeds, same result.

use super::population::{isle, monsters};
use super::*;
use crate::tick::events::event;

/// What a run leaves behind: frame, monsters with their seeds, positions,
/// monster data and timers, the game seed, active rooms and their
/// populated flags, the pending log.
type Digest = (
    i32,
    Vec<(UnitId, Seed, (i32, i32), (u32, i32, u16))>,
    Vec<Vec<(u8, i32)>>,
    Seed,
    Vec<(RoomId, bool)>,
    Vec<String>,
);

fn timers(fx: &Fx, u: UnitId) -> Vec<(u8, i32)> {
    let mut v: Vec<_> = fx
        .game
        .timers
        .unit_timers(u)
        .into_iter()
        .filter_map(|t| Some((fx.game.timers.event(t)?.0, fx.game.timers.expire(t)?)))
        .collect();
    v.sort();
    v
}

fn run() -> Digest {
    let mut fx = Fx::new(isle_ds1s());
    fx.sim.create_regions();
    let (a, b) = isle(&mut fx);
    assert_eq!(fx.game.lists.active_rooms(0).len(), 2);
    assert!(monsters(&fx).is_empty());
    // Tick 1: the room pass (step 3) populates both rooms: A's preset
    // monster, then room population (`population.md` §3) on each room's
    // one-record coordinate list (`levels.md` §11.2 step 2).
    crate::tick::tick(&mut fx.game, &mut fx.sim);
    let m = monsters(&fx);
    let preset: Vec<UnitId> = m
        .iter()
        .copied()
        .filter(|u| {
            let tag = format!("preset {} ", u.0);
            fx.sim
                .action
                .sys
                .hooks
                .x
                .log
                .iter()
                .any(|l| l.starts_with(&tag))
        })
        .collect();
    assert_eq!(preset.len(), 1);
    let u = preset[0];
    assert_eq!(fx.game.lists.unit(u).unwrap().room(), Some(a));
    // Room population placed more, all inside the two rooms.
    assert!(m.len() > 1, "room population placed nothing");
    for &v in &m {
        let r = fx.game.lists.unit(v).unwrap().room();
        assert!(r == Some(a) || r == Some(b), "{v:?} in {r:?}");
    }
    assert!(fx.game.lists.room(a).unwrap().populated);
    assert!(fx.game.lists.room(b).unwrap().populated);
    // The creation mode start that schedules the first think is not
    // specified (units.md §4.6 runs it on a mode change); the test
    // schedules one think as the action e2e does.
    fx.game
        .schedule_event(u, u32::from(event::AI_THINK), 3, None, 0, 0)
        .unwrap();
    for _ in 0..9 {
        crate::tick::tick(&mut fx.game, &mut fx.sim);
    }
    fx.assert_clean();
    // Idle (AI 1) thought at tick 3 and rescheduled itself 200 later.
    assert!(timers(&fx, u).contains(&(event::AI_THINK, 203)));
    // Nothing more was populated: the rooms are marked.
    assert_eq!(monsters(&fx), m);
    let units = m
        .iter()
        .map(|&u| {
            let md = fx.sim.world.monsters.get(u).unwrap();
            (
                u,
                fx.sim.action.sys.units.get(u).unwrap().seed,
                fx.sim.action.sys.hooks.x.pos[&u],
                (md.class, md.level_id, md.type_flags),
            )
        })
        .collect();
    let rooms = fx
        .game
        .lists
        .active_rooms(0)
        .into_iter()
        .map(|r| (r, fx.game.lists.room(r).unwrap().populated))
        .collect();
    (
        fx.game.frame,
        units,
        m.iter().map(|&u| timers(&fx, u)).collect(),
        fx.sim.action.sys.hooks.game_seed,
        rooms,
        fx.sim.action.sys.hooks.x.log.clone(),
    )
}

// Covers: specs/sim/tick.md §4 r1, §4 r2; specs/monsters/population.md §11.1
#[test]
fn generated_level_is_populated_and_ticks_deterministically() {
    let first = run();
    assert_eq!(first.0, 10);
    assert_eq!(first, run());
}
