// Spec: specs/sim/intents-events.md
//! Audit of every S→C id (0x00–0xB4): which have a typed builder, and
//! what is missing for the rest. Mirrored row for row in
//! `docs/handoff/s2c-builders.md` (checked by a test).

/// How far the specs give an S→C message's layout.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    /// Full layout from a system spec: a type in [`super::messages`].
    Built,
    /// Full layout in the TSV `layout` column: a type in
    /// [`crate::generated::server`], re-exported by [`super`].
    Generated,
    /// Some bytes are given (fields, a prefix, recorded bytes); not all.
    Partial,
    /// Only the size rule is given.
    Unspecified,
    /// Size 0: the id is never receivable (§3.1 rules 2–3).
    Never,
}

/// One id's audit row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Audit {
    pub id: u8,
    pub status: Status,
    /// The type that builds it (or, for [`Status::Partial`], the form
    /// that is built).
    pub builder: Option<&'static str>,
    /// Layout source, or what is missing.
    pub note: &'static str,
}

use Status::*;

/// One row per id, in id order.
pub const AUDIT: [Audit; 0xB5] = [
    Audit { id: 0x00, status: Generated, builder: Some("GameLoading"), note: "TSV layout" },
    Audit { id: 0x01, status: Generated, builder: Some("GameFlags"), note: "TSV layout" },
    Audit { id: 0x02, status: Generated, builder: Some("LoadSuccessful"), note: "TSV layout" },
    Audit { id: 0x03, status: Generated, builder: Some("LoadAct"), note: "TSV layout" },
    Audit { id: 0x04, status: Generated, builder: Some("LoadComplete"), note: "TSV layout" },
    Audit { id: 0x05, status: Generated, builder: Some("UnloadComplete"), note: "TSV layout" },
    Audit { id: 0x06, status: Generated, builder: Some("GameExit"), note: "TSV layout" },
    Audit { id: 0x07, status: Generated, builder: Some("MapReveal"), note: "TSV layout" },
    Audit { id: 0x08, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x09, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x0A, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x0B, status: Built, builder: Some("GameHandshake"), note: "model.md §3 r1 (type, GUID)" },
    Audit { id: 0x0C, status: Generated, builder: Some("MonsterHit"), note: "TSV layout" },
    Audit { id: 0x0D, status: Built, builder: Some("PlayerStop"), note: "waypoints.md §7 r7 values + recorded widths" },
    Audit { id: 0x0E, status: Partial, builder: None, note: "unit address only (type u8 @1, GUID u32 @2; §3.4 r3)" },
    Audit { id: 0x0F, status: Partial, builder: None, note: "unit address only (type u8 @1, GUID u32 @2; §3.4 r3)" },
    Audit { id: 0x10, status: Partial, builder: None, note: "unit address only (type u8 @1, GUID u32 @2; §3.4 r3)" },
    Audit { id: 0x11, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x12, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x13, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x14, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x15, status: Partial, builder: None, note: "recorded bytes only (waypoints.md Test vectors); no field list (HANDOFF §7 q8)" },
    Audit { id: 0x16, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x17, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x18, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x19, status: Generated, builder: Some("SmallGoldPickup"), note: "TSV layout" },
    Audit { id: 0x1A, status: Generated, builder: Some("AddExpByte"), note: "TSV layout" },
    Audit { id: 0x1B, status: Generated, builder: Some("AddExpWord"), note: "TSV layout" },
    Audit { id: 0x1C, status: Generated, builder: Some("AddExpDword"), note: "TSV layout" },
    Audit { id: 0x1D, status: Generated, builder: Some("SetStatByte"), note: "TSV layout" },
    Audit { id: 0x1E, status: Generated, builder: Some("SetStatWord"), note: "TSV layout" },
    Audit { id: 0x1F, status: Generated, builder: Some("SetStatDword"), note: "TSV layout" },
    Audit { id: 0x20, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x21, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x22, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x23, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x24, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x25, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x26, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x27, status: Partial, builder: None, note: "header given (u8 1, NPC GUID u32 @2; npc.md §2 step 5); the 34-byte text list layout is not" },
    Audit { id: 0x28, status: Built, builder: Some("QuestInfo"), note: "quests.md §1.5" },
    Audit { id: 0x29, status: Built, builder: Some("GameQuestInfo"), note: "quests.md §1.5" },
    Audit { id: 0x2A, status: Built, builder: Some("NpcTransaction"), note: "npc.md §9; bytes 3–6 unwritten" },
    Audit { id: 0x2B, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x2C, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x2D, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x2E, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x2F, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x30, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x31, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x32, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x33, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x34, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x35, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x36, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x37, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x38, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x39, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x3A, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x3B, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x3C, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x3D, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x3E, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x3F, status: Generated, builder: Some("UseStackableItem"), note: "TSV layout; senders: impl-moves (inventory-moves.md §11)" },
    Audit { id: 0x40, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x41, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x42, status: Generated, builder: Some("ClearCursor"), note: "TSV layout; senders: impl-moves (inventory-moves.md §11)" },
    Audit { id: 0x43, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x44, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x45, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x46, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x47, status: Generated, builder: Some("Relator1"), note: "TSV layout; senders: impl-moves (inventory-moves.md §11)" },
    Audit { id: 0x48, status: Generated, builder: Some("Relator2"), note: "TSV layout; senders: impl-moves (inventory-moves.md §11)" },
    Audit { id: 0x49, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x4A, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x4B, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x4C, status: Partial, builder: None, note: "unit address only (type u8 @1, GUID u32 @2; §3.4 r3)" },
    Audit { id: 0x4D, status: Partial, builder: None, note: "unit address only (type u8 @1, GUID u32 @2; §3.4 r3)" },
    Audit { id: 0x4E, status: Built, builder: Some("MercForHire"), note: "npc.md §7.2" },
    Audit { id: 0x4F, status: Generated, builder: Some("StartMercList"), note: "TSV layout" },
    Audit { id: 0x50, status: Partial, builder: Some("QuestSpecial"), note: "quest form (u16 1 @1) built as QuestSpecial; mercenary form (u16 2 @1, name u16 @3; npc.md §7.5) has no bytes 5–14" },
    Audit { id: 0x51, status: Partial, builder: None, note: "recorded bytes only (waypoints.md Test vectors); no field list" },
    Audit { id: 0x52, status: Built, builder: Some("QuestLogInfo"), note: "quests.md §6.2 step 4" },
    Audit { id: 0x53, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x54, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x55, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x56, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x57, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x58, status: Built, builder: Some("OpenUi"), note: "npc.md §8.1; byte 6 unwritten" },
    Audit { id: 0x59, status: Built, builder: Some("AssignPlayer"), note: "msg-units.md §1.1 r1 offsets, intents-events.md §7.2 fields" },
    Audit { id: 0x5A, status: Partial, builder: None, note: "prefix only (`5A 0E 01 …`, use.md OQ9)" },
    Audit { id: 0x5B, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x5C, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x5D, status: Built, builder: Some("QuestItemState"), note: "quests.md §6.3" },
    Audit { id: 0x5E, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x5F, status: Generated, builder: Some("PortalFlags"), note: "TSV layout" },
    Audit { id: 0x60, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x61, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x62, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x63, status: Built, builder: Some("WaypointMenu"), note: "waypoints.md §5.3" },
    Audit { id: 0x64, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x65, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x66, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x67, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x68, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x69, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x6A, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x6B, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x6C, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x6D, status: Partial, builder: None, note: "unit address only (monster GUID u32 @1; §3.4 r3)" },
    Audit { id: 0x6E, status: Generated, builder: Some("Unknown6E"), note: "TSV layout" },
    Audit { id: 0x6F, status: Generated, builder: Some("Unknown6F"), note: "TSV layout" },
    Audit { id: 0x70, status: Generated, builder: Some("Unknown70"), note: "TSV layout" },
    Audit { id: 0x71, status: Generated, builder: Some("Unknown71"), note: "TSV layout" },
    Audit { id: 0x72, status: Generated, builder: Some("Unknown72"), note: "TSV layout" },
    Audit { id: 0x73, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x74, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x75, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x76, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x77, status: Built, builder: Some("TradeAction"), note: "cube.md §1 (action byte)" },
    Audit { id: 0x78, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x79, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x7A, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x7B, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x7C, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x7D, status: Generated, builder: Some("SetItemState"), note: "TSV layout; senders: impl-moves (inventory-moves.md §11)" },
    Audit { id: 0x7E, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x7F, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x80, status: Never, builder: None, note: "size 0 (client expects 4; never receivable, §3.1 r2)" },
    Audit { id: 0x81, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x82, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x83, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x84, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x85, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x86, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x87, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x88, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0x89, status: Built, builder: Some("UniqueEvent"), note: "quests.md §6.5" },
    Audit { id: 0x8A, status: Built, builder: Some("NpcWantsInteract"), note: "quests.md §6.4" },
    Audit { id: 0x8B, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x8C, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x8D, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x8E, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x8F, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x90, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x91, status: Built, builder: Some("NpcGossipAct"), note: "quests.md §6.7" },
    Audit { id: 0x92, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x93, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x94, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x95, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x96, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x97, status: Generated, builder: Some("WeaponSwitch"), note: "TSV layout" },
    Audit { id: 0x98, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x99, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x9A, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x9B, status: Built, builder: Some("Unknown9B"), note: "npc.md §7.3 step 4" },
    Audit { id: 0x9C, status: Partial, builder: None, note: "header given (inventory-moves.md §11); item bit stream unspecified (inventory.md OQ1); senders: impl-moves" },
    Audit { id: 0x9D, status: Partial, builder: None, note: "header given (inventory-moves.md §11); item bit stream unspecified (inventory.md OQ1); senders: impl-moves" },
    Audit { id: 0x9E, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0x9F, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA0, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA1, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA2, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA3, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA4, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA5, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA6, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA7, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA8, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xA9, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xAA, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xAB, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xAC, status: Partial, builder: None, note: "fields listed (init.md §24), not their byte/bit positions" },
    Audit { id: 0xAD, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0xAE, status: Built, builder: Some("WardenRequest"), note: "TSV layout (transport row, out of scope)" },
    Audit { id: 0xAF, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xB0, status: Generated, builder: Some("ConnectionTerminated"), note: "TSV layout" },
    Audit { id: 0xB1, status: Never, builder: None, note: "size 0: never receivable (§3.1 r3)" },
    Audit { id: 0xB2, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xB3, status: Unspecified, builder: None, note: "size rule only" },
    Audit { id: 0xB4, status: Unspecified, builder: None, note: "size rule only" },
];

/// The audit row of `id`. Panics for ids past 0xB4.
pub fn audit(id: u8) -> Audit {
    AUDIT[id as usize]
}
