#!/usr/bin/env python3
"""check-gen: writes scenario-diff .check files from the 1.14d tables.

Spec: specs/tools/scenario-diff.md (the .check syntax, section 2),
specs/tools/poke.md (the poke directives used).  Fidelity plan:
docs/handoff/fidelity-gaps.md section 4 (check-gen).

Families (one check per table row, written under traces/checks/gen/):

  lvl   one level warp per levels.txt row         (a*-warp-* pattern)
  wp    one waypoint travel per waypoints.tsv row (combat-cold-plains-wp)
  ai    one monster spawn per monstats AI name    (combat-random-boss)
  su    one superunique per superuniques row      (missile-superunique.poke)
  boss  one boss spawn per monstats boss=1 row
  umod  one unique spawn per monumod row          (boss-kinds.poke)
  skill one right-click cast per class skill      (dru-* / bar-* / ass-*)
  shrine one shrine operated per reachable shrines.txt row
  item  a census of ITEM_CHUNK base items per check, each created on the ground by
        the game's own creation path (poke `item`), compared by the items channel

Every generated file starts with a header naming this generator, its
format version, the family and the table row; the files are never edited
by hand (regenerate, `--check` fails when they differ).  Inputs are the
live excel view of the 1.14d install (`$D2_GAME_DIR/extracted/patch_d2/
data/global/excel`, built by `data-tool excel-dir`), strict: a missing
column or an unknown value is an error, nothing is defaulted.

Usage:
  check_gen.py [--excel DIR] [--out DIR] [--family F]... [--ledger FILE]
               [--waypoints TSV] [--check] [--list] [--selftest]
"""
import argparse
import csv
import os
import re
import sys

GEN_VERSION = 1
GEN_NAME = "tools/check-gen/check_gen.py"
FAMILIES = ["lvl", "wp", "ai", "su", "boss", "umod", "skill", "shrine", "item"]
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
CLASSES = ["ama", "sor", "nec", "pal", "bar", "dru", "ass"]
CLASS_SAVE = {"ama": "ScnAma", "sor": "ScnSor", "nec": "ScnNec", "pal": "ScnPal",
              "bar": "ScnBar", "dru": "ScnDru", "ass": "ScnAss"}
# The save of the act a level or waypoint belongs to: the form of the
# existing a2-a5 warp checks (act index 0..4).
ACT_SAVE = ["ScnAma --class ama --expansion"] + [
    f"ScnAm{a + 1} --class ama --expansion --act {a} --quests acts={a}" for a in range(1, 5)]
SORC_ACT_SAVE = ["ScnSo1 --class sor --expansion"] + [
    f"ScnSo{a + 1} --class sor --expansion --act {a} --quests acts={a}" for a in range(1, 5)]


class GenError(Exception):
    pass


def slug(text):
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    if not s:
        raise GenError(f"empty slug from {text!r}")
    return s


class Table:
    """A tab separated game table: header row, rows addressed by column name."""

    def __init__(self, path, need):
        with open(path, encoding="latin-1", newline="") as f:
            rows = list(csv.reader(f, delimiter="\t"))
        self.path = path
        self.head = rows[0]
        self.idx = {}
        for k, n in enumerate(self.head):
            self.idx.setdefault(n, k)
        for n in need:
            if n not in self.idx:
                raise GenError(f"{os.path.basename(path)}: column {n!r} missing")
        self.rows = rows[1:]

    def get(self, row, col):
        k = self.idx[col]
        return row[k] if k < len(row) else ""


def excel(d, name, need):
    p = os.path.join(d, name)
    if not os.path.isfile(p):
        raise GenError(f"{p}: not found (build the excel view: data-tool excel-dir)")
    return Table(p, need)


def read_tsv(path, need):
    with open(path, encoding="utf-8", newline="") as f:
        rows = [r for r in csv.reader(f, delimiter="\t") if r and not r[0].startswith("#")]
    head = rows[0]
    for n in need:
        if n not in head:
            raise GenError(f"{path}: column {n!r} missing")
    return [dict(zip(head, r)) for r in rows[1:]]


# ---------------------------------------------------------------- output

class Check:
    def __init__(self, name, family, row, title, save, ticks, seconds, channels,
                 lines, variant=None, comment=(), seed=1234, extra=None):
        self.name, self.family, self.row, self.title = name, family, row, title
        self.save, self.ticks, self.seconds = save, ticks, seconds
        self.channels, self.lines, self.variant = channels, lines, variant
        self.comment, self.seed, self.extra = comment, seed, extra or {}
        self.area = "-"

    def render(self):
        if not re.fullmatch(r"[a-z0-9-]+", self.name):
            raise GenError(f"bad check name {self.name!r}")
        out = ["check 1",
               f"# GENERATED by {GEN_NAME} (format {GEN_VERSION}), family {self.family}, "
               f"row {self.row}: {self.title}.",
               f"# Ledger area: {self.area}. Do not edit: regenerate with "
               f"`python3 {GEN_NAME}`."]
        out += [f"# {c}" for c in self.comment]
        out += ["# Spec: specs/tools/scenario-diff.md, specs/tools/poke.md.",
                f"name {self.name}", f"save {self.save}", f"seed {self.seed}",
                f"ticks {self.ticks}", f"seconds {self.seconds}",
                f"channels {self.channels}"]
        if self.variant:
            out.append(f"variant {self.variant}")
        out += self.lines
        return "\n".join(out) + "\n"


SEEDS = ["at 30 poke seed-game 0x00001234 666",
         "at 30 poke seed-unit @player 0x00000055 666"]
BM = ["at 4 poke warp 2"]  # Blood Moor (variant blood-moor-empty: no population)



# -------------------------------------------------------------- families

def fam_lvl(ctx):
    t = excel(ctx.excel, "levels.txt", ["Name", "Id", "Act", "DrlgType"])
    out = []
    for r in t.rows:
        lid = t.get(r, "Id")
        if not lid.isdigit() or int(lid) == 0:
            continue  # the "Null" row and the "Expansion" separator
        lid, act = int(lid), int(t.get(r, "Act"))
        if not 0 <= act <= 4:
            raise GenError(f"levels row {lid}: act {act}")
        name = t.get(r, "Name")
        out.append(Check(
            f"gen-lvl-{lid}", "lvl", f"levels.txt Id {lid}",
            f"level generation of {name} (level {lid}, act {act + 1})",
            ACT_SAVE[act], 160, 900, "state rng", ["at 20 poke warp %d" % lid],
            comment=[f"Level generation of {name}: the character starts in its act's town, "
                     f"idle until frame 20, then the level warp (poke `warp {lid}`, tile 0) on "
                     "both sides; rooms, presets, populated units and the draws."]))
        out[-1].extra = {"level": lid}
    return out


def walk_steps(p):
    """`pos` pokes from the join point to 3 sub-tiles beside the waypoint object:
    10 sub-tiles per step, 3 frames apart (the form of milestone-hephasto), so
    each target lies in a room the previous step activated."""
    sx, sy = int(p["sx"]), int(p["sy"])
    tx, ty = int(p["wx"]) - 3, int(p["wy"]) + 5
    n = max(1, -(-max(abs(tx - sx), abs(ty - sy)) // 10))
    return [f"at {8 + 3 * i} poke pos @player {sx + (tx - sx) * (i + 1) // n} "
            f"{sy + (ty - sy) * (i + 1) // n}" for i in range(n)]


def fam_wp(ctx):
    rows = read_tsv(ctx.waypoints, ["wp", "level", "act", "town", "level_name"])
    towns = {int(r["act"]): int(r["wp"]) for r in rows if r["town"] == "1"}
    pos = {int(r["act"]): r for r in read_tsv(ctx.waypoint_towns,
                                              ["act", "wp_class", "wx", "wy", "sx", "sy"])}
    out = []
    for r in rows:
        wp, lvl, act = int(r["wp"]), int(r["level"]), int(r["act"])
        town = towns[act]
        known = sorted({town, wp})
        out.append(Check(
            f"gen-wp-{wp}", "wp", f"waypoints.tsv wp {wp}",
            f"waypoint travel to {r['level_name']} (wp {wp}, level {lvl}, act {act + 1})",
            SORC_ACT_SAVE[act] + " --waypoints " + ",".join(map(str, known)), 460, 900, "state",
            walk_steps(pos[act]) + [f"at 400 poke msg 0x49 @wp {lvl}"],
            comment=[f"Waypoint travel (world/waypoints.md section 6-7): a sorceress in the town "
                     f"of act {act + 1} that knows waypoint {wp} is moved by `pos` pokes (10 sub-tiles every "
                     f"3 frames from frame 8, as milestone-hephasto) from the join point "
                     f"({pos[act]['sx']}, {pos[act]['sy']}) to the waypoint object "
                     f"(class {pos[act]['wp_class']} at {pos[act]['wx']}, {pos[act]['wy']}; "
                     "reach 22 sub-tiles, section 6.2 step 3), then the C->S 0x49 to level "
                     f"{lvl} at frame 400 (after the 10 s hostile delay, section 6.1) with the "
                     "town's waypoint object as `@wp`."
                     + (" The target is the start town itself: the travel to the town waypoint."
                        if wp == town else "")]))
    return out


def monster_rows(ctx):
    t = excel(ctx.excel, "monstats.txt", ["Id", "hcIdx", "AI", "enabled", "boss"])
    return t, [(int(t.get(r, "hcIdx")), t.get(r, "Id"), t.get(r, "AI"),
                t.get(r, "enabled"), t.get(r, "boss")) for r in t.rows
               if t.get(r, "hcIdx").isdigit()]


def spawn_check(name, family, row, title, spawn, comment, ticks=150):
    return Check(name, family, row, title, "ScnAma --class ama --expansion", ticks, 360,
                 "state", BM + SEEDS + ["at 30 poke " + spawn],
                 variant="blood-moor-empty",
                 comment=comment + ["Blood Moor warp (level 2) before frame 4 under variant "
                                    "blood-moor-empty (no population), game and unit seeds "
                                    "fixed at frame 30, then the spawn; the state channel "
                                    "compares the units and their AI frame by frame."])


def fam_ai(ctx):
    _, mons = monster_rows(ctx)
    first = {}
    for hc, ident, ai, enabled, boss in mons:
        if not ai:
            continue
        cur = first.get(ai)
        # prefer an enabled class that is not a boss, then the lowest row
        key = (enabled != "1", boss == "1", hc)
        if cur is None or key < cur[0]:
            first[ai] = (key, hc, ident)
    out = []
    for ai in sorted(first, key=str.lower):
        _, hc, ident = first[ai]
        c = spawn_check(f"gen-ai-{slug(ai)}", "ai", f"monstats.txt AI {ai}",
                        f"monster AI {ai} (class {hc} {ident})",
                        f"spawn {hc} @x+5 @y-4 normal",
                        [f"Monster AI {ai}: its first class {hc} ({ident}) spawned normal next "
                         "to the player."])
        c.extra = {"ai": ai, "class": hc}
        out.append(c)
    return out


def fam_su(ctx):
    t = excel(ctx.excel, "superuniques.txt", ["Superunique", "Name", "Class", "hcIdx"])
    out = []
    for n, r in enumerate(t.rows):
        if not t.get(r, "Superunique") or not t.get(r, "hcIdx"):
            continue  # a blank row
        hc, name = t.get(r, "hcIdx"), t.get(r, "Name")
        c = spawn_check(f"gen-su-{n}", "su", f"superuniques.txt row {n}",
                        f"superunique {name} (hcIdx {hc}, class {t.get(r, 'Class')})",
                        f"superunique {n} @x+4 @y+4",
                        [f"Superunique row {n} ({name}) and its minions through the superunique "
                         "creation (poke `superunique`)."])
        c.extra = {"hcIdx": hc}
        out.append(c)
    return out


def fam_boss(ctx):
    _, mons = monster_rows(ctx)
    out = []
    for hc, ident, ai, enabled, boss in mons:
        if boss != "1":
            continue
        c = spawn_check(f"gen-boss-{hc}", "boss", f"monstats.txt row {hc}",
                        f"boss {ident} (class {hc}, AI {ai})", f"spawn {hc} @x+4 @y+4 normal",
                        [f"Act or quest boss {ident} (monstats boss=1, AI {ai}) spawned normal "
                         "next to the player."])
        c.extra = {"class": hc, "id": ident}
        out.append(c)
    return out


def fam_umod(ctx):
    t = excel(ctx.excel, "monumod.txt", ["uniquemod", "id", "enabled"])
    out = []
    for r in t.rows:
        uid = t.get(r, "id")
        if not uid.isdigit() or int(uid) == 0:
            continue
        name = t.get(r, "uniquemod")
        c = spawn_check(f"gen-umod-{uid}", "umod", f"monumod.txt id {uid}",
                        f"unique modifier {uid} {name}",
                        f"spawn 19 @x+4 @y+4 unique umod {uid}",
                        [f"Unique modifier {uid} ({name}) on a unique fallen (monstats 19), the "
                         "`unique` kind of scenario.md section 3.1."])
        c.extra = {"umod": int(uid)}
        out.append(c)
    return out


def fam_skill(ctx):
    t = excel(ctx.excel, "skills.txt", ["skill", "Id", "charclass", "passive"])
    out = []
    for cl in CLASSES:
        for r in t.rows:
            if t.get(r, "charclass") != cl:
                continue
            sid, name = int(t.get(r, "Id")), t.get(r, "skill")
            passive = t.get(r, "passive") == "1"
            c = Check(
                f"gen-skill-{cl}-{sid}", "skill", f"skills.txt Id {sid}",
                f"{cl} skill {name} ({sid})", f"{CLASS_SAVE[cl]} --class {cl} --expansion "
                f"--level 30 --all-skills 20 --right-skill {sid}", 70, 300, "state",
                BM + ["input frame 20; rclick 330 300"], variant="blood-moor-empty",
                comment=[f"Cast of {name} (skill {sid}, class {cl}): expansion character, level 30, "
                         f"every skill at 20, right skill {sid}; warp to the Blood Moor "
                         "(variant blood-moor-empty: no target monster), one right click at client "
                         "pixel (330, 300) before frame 20's drain. Compares the cast (mode, "
                         "states, stats), its missiles' or summons' effects and the draws."
                         + (" Passive skill: the click casts nothing; the check compares the "
                            "passive's stats and the idle click." if passive else "")])
            c.extra = {"skill": sid, "class": cl, "passive": passive}
            out.append(c)
    return out


def fam_shrine(ctx):
    """Shrines.txt rows the shrine pick can reach through `poke object`
    (tools/check-gen/shrine-seeds.tsv, written by find_shrine_seeds.py):
    rows 0, 4, 5 and 16 are never picked (world/objects.md section 5.1
    rule 4), so they have no check."""
    t = excel(ctx.excel, "shrines.txt", ["Shrine Type", "Shrine name", "Code"])
    out = []
    for n, r in enumerate(t.rows):
        if n not in ctx.shrine_seeds:
            continue
        seed, cls, how = ctx.shrine_seeds[n]
        name = t.get(r, "Shrine name")
        c = Check(
            f"gen-shrine-{n}", "shrine", f"shrines.txt row {n}",
            f"shrine {name} ({t.get(r, 'Shrine Type')})",
            "ScnAm2 --class ama --expansion --level 30 --act 1 --quests acts=1", 120, 300, "state",
            [f"at 30 poke object {cls} @x+3 @y",
             f"at 40 send InteractWithEntity type=2 id=@2:{cls}"],
            seed=seed,
            comment=[f"Shrine {n} {name}: objects row {cls} created next to the player in "
                     f"Lut Gholein (level 40, a town; its level id is above every LevelMin of "
                     f"shrines.txt) at frame 30, operated by C->S 0x13 at frame 40. With -seed "
                     f"{seed} the shrine pick of the object control (world/objects.md section "
                     f"5.1) gives row {n} ({how}; PROVISIONAL REC-1330: the seed is d2rs's pick, settled by the first 1.14d run); the check compares the shrine's effect, the "
                     "player's stats and states and the draws."])
        c.extra = {"shrine": n}
        out.append(c)
    return out


ITEM_CHUNK = 20
ITEM_TABLES = ["weapons.txt", "armor.txt", "misc.txt"]


def item_rows(ctx):
    """(combined index, code, name) over weapons, armor, misc in file order: the
    combined items array of items/treasure.md section 9.1 (ledger ids item.<id>-<code>)."""
    out = []
    for tn in ITEM_TABLES:
        t = excel(ctx.excel, tn, ["code", "name"])
        for r in t.rows:
            code = t.get(r, "code")
            if code.strip() == "ear":
                out.append((len(out), "ear", t.get(r, "name")))  # keeps the index; not poked
            elif code.strip():
                out.append((len(out), code.strip(), t.get(r, "name")))
    return out


def fam_item(ctx):
    rows = item_rows(ctx)
    out = []
    for k in range(0, len(rows), ITEM_CHUNK):
        chunk = rows[k:k + ITEM_CHUNK]
        n = k // ITEM_CHUNK
        lines = ["at 4 poke seed-game 0x00001234 666"]
        for j, (idx, code, _) in enumerate(chunk):
            if code == "ear":
                continue  # the ear is made from a killed player (PK); `poke item` refuses it
            dy = 2 * (j // 5)
            lines.append(f"at 4 poke item {code} @x+{2 + 2 * (j % 5)} " + (f"@y+{dy}" if dy else "@y"))
        c = Check(f"gen-item-{n:02d}", "item",
                  f"items {chunk[0][0]}-{chunk[-1][0]} (combined index)",
                  f"base items {chunk[0][1]} .. {chunk[-1][1]} ({len(chunk)} items)",
                  "ScnAma --class ama --expansion", 20, 240, "items", lines,
                  comment=["Census of base items (items/generation.md section 3): each item is "
                           "created on the ground at normal quality by the game's own creation "
                           "path with the game seed fixed first; the items channel compares the "
                           "S->C 0x9C bit streams item by item. Items: " +
                           ", ".join(f"{i}-{cd}" for i, cd, _ in chunk) + "."])
        c.extra = {"items": [(i, cd) for i, cd, _ in chunk]}
        out.append(c)
    return out


FAMILY_FN = {"lvl": fam_lvl, "wp": fam_wp, "ai": fam_ai, "su": fam_su, "boss": fam_boss,
             "umod": fam_umod, "skill": fam_skill, "shrine": fam_shrine, "item": fam_item}


# ----------------------------------------------------------- ledger join

def load_ledger(path):
    """area ids of the fidelity ledger, for the headers of the checks."""
    areas = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            cols = line.rstrip("\n").split("\t")
            if cols[0] == "area":
                continue
            areas.append((cols[0], cols[3] if len(cols) > 3 else cols[1]))
    return areas


def resolve_area(c, areas):
    f, x = c.family, c.extra
    pick = []
    if f == "lvl":
        pick = [a for a, _ in areas if re.fullmatch(rf"level\.a\d\.{x['level']}\..*", a)]
    elif f == "wp":
        n = c.row.split()[-1]
        pick = [a for a, _ in areas if a.startswith(f"waypoint.{n}.")]
    elif f == "ai":
        pick = [a for a, _ in areas if a == f"monster.ai.{x['ai'].lower()}"]
    elif f == "su":
        pick = [a for a, s in areas if a.startswith("monster.superunique.")
                and f"(hcIdx {x['hcIdx']}," in s]
    elif f == "boss":
        pick = [a for a, s in areas if a.startswith("monster.boss.")
                and f"({x['class']})" in s]
    elif f == "umod":
        pick = [a for a, _ in areas if a.startswith(f"monster.umod.{x['umod']}-")]
    elif f == "skill":
        pick = [a for a, s in areas if a.startswith(f"skill.{x['class']}.")
                and f"({x['skill']})" in s]
    elif f == "shrine":
        pick = [a for a, _ in areas if a.startswith(f"shrine.{x['shrine']}.")]
    elif f == "item":
        ids = {a: a for a, _ in areas}
        pick = [f"item.{i}-{cd}" for i, cd in x["items"] if f"item.{i}-{cd}" in ids]
        # the ledger lists the bases "never created" in run a1a2 only; others have no row
        c.area = ",".join(pick) if pick else "-"
        return
    if len(pick) > 1:
        raise GenError(f"{c.name}: {len(pick)} ledger areas {pick}")
    c.area = pick[0] if pick else "-"


# ------------------------------------------------------------------ main

class Ctx:
    pass


def default_excel():
    gd = os.environ.get("D2_GAME_DIR")
    if not gd:
        raise GenError("--excel DIR or D2_GAME_DIR needed")
    return os.path.join(gd, "extracted", "patch_d2", "data", "global", "excel")


def generate(ctx, families):
    checks = []
    for f in families:
        checks += FAMILY_FN[f](ctx)
    names = [c.name for c in checks]
    if len(set(names)) != len(names):
        raise GenError("duplicate check names")
    if ctx.ledger:
        areas = load_ledger(ctx.ledger)
        for c in checks:
            resolve_area(c, areas)
    return checks


def index_text(checks):
    out = [f"#check-gen-index {GEN_VERSION}",
           f"# generated by {GEN_NAME}; one line per generated check",
           "name\tfamily\trow\tledger_area\ttitle"]
    for c in checks:
        out.append(f"{c.name}\t{c.family}\t{c.row}\t{c.area}\t{c.title}")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--excel")
    ap.add_argument("--out", default=os.path.join(ROOT, "traces", "checks", "gen"))
    ap.add_argument("--family", action="append", choices=FAMILIES)
    ap.add_argument("--ledger", default=os.path.join(HERE, "ledger-areas.tsv"),
                    help="ledger area ids for the headers (default: the committed snapshot; "
                         "the full fidelity-ledger.tsv is read too)")
    ap.add_argument("--waypoints", default=os.path.join(ROOT, "specs", "world", "waypoints.tsv"))
    ap.add_argument("--waypoint-towns", default=os.path.join(HERE, "waypoint-towns.tsv"))
    ap.add_argument("--shrine-seeds", default=os.path.join(HERE, "shrine-seeds.tsv"))
    ap.add_argument("--check", action="store_true", help="fail when the files differ")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        import selftest
        return selftest.run()
    ctx = Ctx()
    ctx.excel = a.excel or default_excel()
    ctx.waypoints = a.waypoints
    ctx.waypoint_towns = a.waypoint_towns
    ctx.ledger = a.ledger
    ctx.shrine_seeds = {}
    if os.path.isfile(a.shrine_seeds):
        for r in read_tsv(a.shrine_seeds, ["shrine", "seed", "object_class", "verified"]):
            ctx.shrine_seeds[int(r["shrine"])] = (int(r["seed"]), int(r["object_class"]),
                                                 r["verified"])
    fams = a.family or FAMILIES
    try:
        checks = generate(ctx, fams)
    except GenError as e:
        print(f"check-gen: {e}", file=sys.stderr)
        return 2
    if a.list:
        for c in checks:
            print(c.name, c.area, c.title, sep="\t")
        return 0
    want = {f"{c.name}.check": c.render() for c in checks}
    index_name = "INDEX.tsv"
    if not a.family:
        want[index_name] = index_text(checks)
    os.makedirs(a.out, exist_ok=True)
    have = {f for f in os.listdir(a.out) if f.endswith(".check") or f == index_name}
    bad = []
    if a.check:
        for f, text in want.items():
            p = os.path.join(a.out, f)
            if not os.path.isfile(p) or open(p, encoding="utf-8").read() != text:
                bad.append(f)
        if not a.family:
            bad += sorted(have - set(want))
        if bad:
            print(f"check-gen: {len(bad)} generated files are stale or missing, e.g. {bad[:3]}",
                  file=sys.stderr)
            return 1
        print(f"check-gen: {len(want)} files current")
        return 0
    for f, text in want.items():
        with open(os.path.join(a.out, f), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    if not a.family:
        for f in sorted(have - set(want)):
            os.remove(os.path.join(a.out, f))
    counts = {}
    for c in checks:
        counts[c.family] = counts.get(c.family, 0) + 1
    print("check-gen: wrote %d checks to %s: %s" % (
        len(checks), os.path.relpath(a.out, ROOT),
        ", ".join(f"{k} {v}" for k, v in counts.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
