"""Scene groups for scenes.py: character, seed, input script (ticks, marks), scenes."""
GROUPS = {
    "panels": {
        "char": "SceSor", "seed": 1234,
        "script": "waitticks 20; mark idle; key I; waitticks 28; mark inv; waitticks 2; click 678 330; waitticks 10; "
                  "click 563 250; waitticks 15; mark invbelt; key I; waitticks 20; "
                  "key 0xC0; waitticks 28; mark belt; waitticks 2; key 0xC0; waitticks 15; "
                  "key C; waitticks 28; mark char; waitticks 2; key C; waitticks 20; "
                  "key T; waitticks 28; mark skill; waitticks 2; key T; waitticks 20; "
                  "key TAB; waitticks 28; mark automap; waitticks 2; key TAB; waitticks 20; "
                  "key I; waitticks 10; rclick 446 345; waitticks 28; mark cube; waitticks 2; key ESC; waitticks 20; "
                  "key ESC; wait 4; mark esc; key ESC; wait 2; end",
        "scenes": {"a1-panel-inventory": ("inv", 0), "a1-panel-character": ("char", 0),
                   "a1-panel-skilltree": ("skill", 0), "a1-panel-automap": ("automap", 0),
                   "a1-panel-esc-menu": ("esc", 0, "last"), "a1-panel-cube": ("cube", 0),
                   "a1-panel-belt-open": ("belt", 0)},
    },
}

for _a, _n in ((2, "lut-gholein"), (3, "kurast-docks"), (4, "pandemonium-fortress"), (5, "harrogath")):
    GROUPS[f"act{_a}town"] = {
        "char": f"SceAct{_a}", "seed": 1234,
        "script": "waitticks 40; mark t; waitticks 10; end",
        "scenes": {f"a{_a}-town-{_n}": ("t", 0)},
    }
GROUPS["a1town"] = {
    "char": "SceSor", "seed": 1234,
    "script": "waitticks 40; mark t; waitticks 10; end",
    "scenes": {"a1-town-idle-sor": ("t", 0)},
}

GROUPS["npc"] = {
    "char": "SceSor", "seed": 1234,
    "script": "goto 2 267; waitticks 70; mark s0; waitticks 30; mark s1; "
              "goto 1 150; waitticks 70; mark n0; waitticks 30; mark n1; waitticks 10; end",
    "scenes": {"s0": ("s0", 0), "s1": ("s1", 0), "n0": ("n0", 0), "n1": ("n1", 0)},
}

# quest log (Q), then the Act I waypoint menu (walk to it, open it): fixed clicks like `fight`
GROUPS["panels2"] = {
    "char": "SceSor", "seed": 1234,
    "script": "waitticks 20; key Q; waitticks 30; mark quest; key Q; waitticks 20; "
              "click 700 300; waitticks 60; click 650 300; waitticks 40; mark wp; waitticks 6; end",
    "scenes": {"a1-panel-quest-log": ("quest", 0), "a1-panel-waypoint": ("wp", 0)},
}

# the stash: click the chest next to the barrel (screen 268, 226 from the start), wait for the walk
GROUPS["panels3"] = {
    "char": "SceSor", "seed": 1234,
    "script": "waitticks 20; click 268 226; waitticks 90; mark stash; waitticks 6; end",
    "scenes": {"a1-panel-stash": ("stash", 0)},
}

# walking and running in the 8 screen directions (SceSor, Rogue Encampment): click a point 200 px
# from the player's screen position (400, 284); the frame is the first one 10 ticks after the click
_DIRS = (("n", 400, 184), ("s", 400, 384), ("ne", 541, 213), ("sw", 259, 355),
         ("e", 600, 284), ("w", 200, 284), ("se", 541, 355), ("nw", 259, 213))
_walk = "waitticks 20; "
for _n, _x, _y in _DIRS:
    _walk += f"click {_x} {_y}; waitticks 10; mark w_{_n}; waitticks 4; "
_walk += "key R; waitticks 6; "
for _n, _x, _y in _DIRS:
    _walk += f"click {_x} {_y}; waitticks 10; mark r_{_n}; waitticks 4; "
GROUPS["walk"] = {
    "char": "SceSor", "seed": 1234, "script": _walk + "waitticks 6; end",
    "scenes": {**{f"a1-walk-{n}": (f"w_{n}", 0) for n, _, _ in _DIRS},
               **{f"a1-run-{n}": (f"r_{n}", 0) for n, _, _ in _DIRS}},
}

# Cold Plains by waypoint, fixed clicks only (no unit lookup), so every input lands on the same tick:
# walk to the Act I waypoint, open it, take Cold Plains, cast Fire Bolt into the Fallen group
GROUPS["fight"] = {
    "char": "SceSor", "seed": 1234,
    "script": "waitticks 20; click 700 300; waitticks 60; click 650 300; waitticks 40; click 590 262; waitticks 50; "
              "click 207 176; waitticks 80; mark cp; "
              + "".join(f"click 330 190; waitticks 12; click 300 200; waitticks 13; mark f{i}; " for i in range(1, 15)) + "end",
    "scenes": {"a1-cold-plains-monsters": ("cp", 0), "a1-cold-plains-corpse": ("f3", 0), "a1-cold-plains-drop": ("f9", 0)},
}

# an outdoor level of each act by the town waypoint: the click path to the waypoint (collision-grid
# route, one click per 13 ticks), the waypoint, a row of the menu (Acts II-V: Dry Hills, Spider Forest,
# City of the Damned, Frigid Highlands); generated by d2rs's autoplay host (docs/handoff/q-chk-render-world.md)
GROUPS["act2out"] = {
    "char": "SceAct2", "seed": 1234,
    "script": ("waitticks 8; click 352 84; waitticks 13; click 352 84; waitticks 13; click 544 132; waitticks 13; click 496 108; waitticks 13; click 464 92; waitticks 13; click 464 92; waitticks 13; click 464 92; waitticks 13; click 448 84; waitticks 13; click 448 84; waitticks 13; click 432 76; waitticks 13; click 416 68; waitticks 13; click 432 76; waitticks 13; click 560 140; waitticks 13; click 560 140; waitticks 13; click 624 172; waitticks 13; click 560 140; waitticks 13; click 544 132; waitticks 13; click 496 108; waitticks 13; click 512 116; waitticks 13; click 464 92; waitticks 13; click 464 92; waitticks 13; click 448 84; waitticks 13; click 432 76; waitticks 13; click 432 76; waitticks 13; click 432 76; waitticks 13; click 416 68; waitticks 13; click 400 60; waitticks 13; click 416 84; waitticks 13; click 400 140; waitticks 13; click 400 188; waitticks 13; click 400 244; waitticks 41; click 230 207; waitticks 81; mark o; waitticks 10; end"),
    "scenes": {"a2-outdoor-dry-hills": ("o", 0)},
}
GROUPS["act3out"] = {
    "char": "SceAct3", "seed": 1234,
    "script": ("waitticks 8; click 736 260; waitticks 13; click 688 252; waitticks 13; click 688 236; waitticks 13; click 672 196; waitticks 13; click 656 188; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 624 172; waitticks 13; click 688 204; waitticks 13; click 688 204; waitticks 13; click 704 212; waitticks 13; click 720 220; waitticks 13; click 688 204; waitticks 13; click 688 204; waitticks 13; click 688 204; waitticks 13; click 688 204; waitticks 13; click 688 204; waitticks 13; click 704 212; waitticks 13; click 768 244; waitticks 13; click 784 252; waitticks 13; click 688 268; waitticks 13; click 576 276; waitticks 13; click 464 276; waitticks 41; click 230 171; waitticks 81; mark o; waitticks 10; end"),
    "scenes": {"a3-outdoor-spider-forest": ("o", 0)},
}
GROUPS["act4out"] = {
    "char": "SceAct4", "seed": 1234,
    "script": ("waitticks 8; click 624 172; waitticks 13; click 624 172; waitticks 13; click 576 148; waitticks 13; click 512 180; waitticks 13; click 464 236; waitticks 13; click 416 268; waitticks 41; click 230 171; waitticks 81; mark o; waitticks 10; end"),
    "scenes": {"a4-outdoor-city-of-the-damned": ("o", 0)},
}
GROUPS["act5out"] = {
    "char": "SceAct5", "seed": 1234,
    "script": ("waitticks 8; click 240 428; waitticks 13; click 240 428; waitticks 13; click 240 428; waitticks 13; click 240 428; waitticks 13; click 240 428; waitticks 13; click 240 428; waitticks 13; click 240 428; waitticks 13; click 272 444; waitticks 13; click 304 396; waitticks 13; click 352 340; waitticks 13; click 384 284; waitticks 41; click 230 171; waitticks 81; mark o; waitticks 10; end"),
    "scenes": {"a5-outdoor-frigid-highlands": ("o", 0)},
}
GROUPS["act1out"] = {
    "char": "SceSor", "seed": 1234,
    "script": ("waitticks 8; click 768 324; waitticks 13; click 790 276; waitticks 13; click 790 276; waitticks 13; click 768 276; waitticks 13; click 768 276; waitticks 13; click 688 316; waitticks 13; click 576 308; waitticks 13; click 464 292; waitticks 41; click 352 284; waitticks 41; click 230 171; waitticks 81; mark o; waitticks 10; end"),
    "scenes": {"a1-outdoor-cold-plains": ("o", 0)},
}

# Spell and effect scenes (docs/handoff/q-chk-render-effects.md): a level-30 character of the class
# with the one skill at level 1 on the left (attacks) or right (auras, buffs) mouse button, the same
# click path as "fight" (the waypoint, Cold Plains, the Fallen group) with the cast clicked 14 times;
# tools/cloud-game/prepare_effect_chars.sh makes the characters (name Fx<skill id>)
# (group, class, skill byte index, skill id, button, scene label)
FX = (
    ("fxicebolt", "sor", 3, 39, "l", "ice-bolt"), ("fxfireball", "sor", 11, 47, "l", "fire-ball"),
    ("fxlightning", "sor", 13, 49, "l", "lightning"), ("fxcharged", "sor", 2, 38, "l", "charged-bolt"),
    ("fxfrostnova", "sor", 8, 44, "l", "frost-nova"), ("fxnova", "sor", 12, 48, "l", "nova"),
    ("fxfrozenarmor", "sor", 4, 40, "r", "frozen-armor"),
    ("fxteeth", "nec", 1, 67, "l", "teeth"), ("fxbonespear", "nec", 18, 84, "l", "bone-spear"),
    ("fxamplify", "nec", 0, 66, "l", "amplify-damage"),
    ("fxholybolt", "pal", 5, 101, "l", "holy-bolt"), ("fxmight", "pal", 2, 98, "r", "might-aura"),
    ("fxbash", "bar", 0, 126, "l", "bash"), ("fxwarcry", "bar", 28, 154, "l", "war-cry"),
    ("fxhowl", "bar", 4, 130, "l", "howl"),
    ("fxfirestorm", "dru", 4, 225, "l", "firestorm"), ("fxmolten", "dru", 8, 229, "l", "molten-boulder"),
    ("fxfiretrauma", "ass", 0, 251, "l", "fire-trauma"), ("fxshockfield", "ass", 5, 256, "l", "shock-field"),
    ("fxinnersight", "ama", 2, 8, "l", "inner-sight"),
)
for _g, _c, _i, _s, _b, _l in FX:
    _cast = ("click" if _b == "l" else "rclick")
    GROUPS[_g] = {
        "char": f"Fx{_s}", "seed": 1234,
        "script": "waitticks 20; click 700 300; waitticks 60; click 650 300; waitticks 40; click 590 262; waitticks 50; "
                  "click 207 176; waitticks 80; mark cp; "
                  + "".join(f"{_cast} 330 190; waitticks 12; {_cast} 300 200; waitticks 13; mark f{i}; " for i in range(1, 15)) + "end",
        "scenes": {f"fx-{_l}-cast": ("f1", 0), f"fx-{_l}-flight": ("f2", 0), f"fx-{_l}-hit": ("f4", 0),
                   f"fx-{_l}-later": ("f9", 0)},
    }
