// Spec: specs/data/loading.md ("d2-data policy")
//! D2 game data: the live `.bin` set 1.14d loads (game truth), the `.txt`
//! reader and the txt → record compiler verified byte for byte against it.
//! Must not depend on Bevy.
//!
//! - [`txt`]: strict `.txt` reader and column binding (`txt-format.md`).
//! - [`schema`]: the 1.14d field lists (`fields.tsv`, `tables.tsv`).
//! - [`compile`]: field types, linkers, callbacks (`field-types.md`).
//! - [`calc`]: formula compiler and code buffers (`calc-expressions.md`).
//! - [`strings`]: string tables and `strkey` (`field-types.md` §7).
//! - [`compile_set`]: every table in load order.
//! - [`bin`]: `.bin` container, live files, load checks (`loading.md`).
//! - [`crosscheck`]: compiled text vs live `.bin`.
//! - [`fixup`]: post-load fix-ups and runtime maps (`loading.md` §7.4).
//! - [`tables`]: typed records, generated by [`codegen`] from the schema.
//! - [`links`]: cross-reference validation (`field-types.md` §6.7).
//! - [`patch`]: mod patch layers over the `.txt` cells (`patch-layers.md`).
//! - [`sounds`]: the runtime `.txt` sound tables (`audio/sound-table.md` §1–§2).

pub mod bin;
pub mod calc;
pub mod codegen;
pub mod compile;
pub mod compile_set;
pub mod crosscheck;
pub mod fixup;
pub mod links;
pub mod patch;
pub mod schema;
pub mod sounds;
pub mod strings;
pub mod tables;
pub mod txt;

#[cfg(test)]
mod gaps_loading_tests;
#[cfg(test)]
mod gaps_patch_fixup_tests;
#[cfg(test)]
mod loading_gaps_numbered_tests;
#[cfg(test)]
mod mutant_tests_bin_calc;
#[cfg(test)]
mod mutant_tests_compile;
#[cfg(test)]
mod mutant_tests_fixup;
#[cfg(test)]
mod mutant_tests_misc;
#[cfg(test)]
mod mutant_tests_patch;
#[cfg(test)]
mod robust;
#[cfg(test)]
mod robust_tests;
