// Spec: specs/client/bridge.md §3; specs/sim/intents-events.md §1–§3; specs/sim/tick.md §3, §4; specs/drlg/levels.md §5; specs/drlg/preset.md §3, §8, §9; specs/drlg/rooms.md §4.1; specs/monsters/population.md §11.1; specs/skills/use.md §1, §4; specs/world/waypoints.md §6, §7 (end to end)
//! End-to-end single player: the bridge (`d2_client::bridge`) on its
//! local link (`bridge::local::LocalLink`) over the in-process
//! `d2-server` host, whose game is `SimGame` on the fully wired `d2-sim`
//! (`wiring::worldgen::WorldSim` around `wiring::action::ActionSim`),
//! from synthetic tables and synthetic DS1 files (no game files).
//!
//! The run, step by step (`docs/handoff/e2e-single-player.md` lists
//! where each step stops and why):
//!
//! 1. game creation on a fixed seed: act 0's DRLG through the level-type
//!    dispatcher (`WorldTypes`: the Act I outdoor placer, preset inits),
//!    the regions on the game seed;
//! 2. a preset level generated by the real generator (`drlg::preset`),
//!    one of its rooms streamed for the player;
//! 3. the player joins; the first host tick runs the client room change
//!    (`rooms.md` §4.1: rooms near the player become active) and the room
//!    pass (`population.md` §11.1: the DS1's preset monster is created);
//! 4. a right-skill cast at the monster (C→S 0x0C): the handler runs and
//!    the mode starts, **then stops**: no AnimData record is routed
//!    (`units.md` §4.1), so no skill event, missile, hit, kill,
//!    experience or drop follows;
//! 5. pick-up (C→S 0x16), buy (0x32) and sell (0x33) reach the server
//!    and **stop at the stubs** (no inventory spec; no vendor provider on
//!    the server's world host);
//! 6. a waypoint travel (C→S 0x49) runs through the handler, the warp
//!    seam and the destination's spawn search, **then stops**: the
//!    same-act placement belongs to the unwritten path spec, so the
//!    player is not moved and `waypoints.md` §7 rule 7 sends no S→C 0x0D.
//!
//! No S→C message with a spec layout fires on these paths, so the bytes
//! the client receives are asserted empty in every frame.
//!
//! The whole run is repeated: same seed → byte-identical transcript.

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, MutexGuard};

use d2_client::bridge::dispatch::Dispatch;
use d2_client::bridge::link::{LinkError, Pumped, SendQueue, Sent, ServerLink};
use d2_client::bridge::local::{LocalLink, PendingSession};
use d2_client::bridge::{Bridge, FrameReport};
use d2_data::bin::BinTable;
use d2_data::fixup::records::stat_ops;
use d2_data::tables::{
    Charstats, Difficultylevels, Itemstatcost, Levels, Monlvl, Monstats, Monstats2, Objects,
    Record, Skilldesc, Skills,
};
use d2_proto::client::{BuyItem, PickItem, RightSkill, SellItem, TakeOrCloseWp};
use d2_server::adapters::handlers::skills::seams::SkillSeams;
use d2_server::adapters::handlers::skills::wired::WiredSkills;
use d2_server::adapters::handlers::world::{ActionWorld, Outbox};
use d2_server::adapters::{PlayerData, PlayerFields, ProtoSizes, SimGame, UnitFacts};
use d2_server::dispatch::Outcome;
use d2_server::host::{Handled, Host};
use d2_server::seams::{Clock, PlayerGate, Pos, ResultCode};
use d2_sim::combat::vitals::VitalsTables;
use d2_sim::combat::{CombatTables, RoomKind};
use d2_sim::drlg::maze::{Maze, MazeData, MazeRow, Specials};
use d2_sim::drlg::outdoor::{OutdoorData, PresetDef as OutdoorPreset, SubDefs, SubFileMap};
use d2_sim::drlg::preset::{
    Ds1Input, Ds1ObjectInput, Ds1Source, PresetData, PresetDef, PresetTables,
};
use d2_sim::drlg::tiles::{cell, FIXED_LIBRARY};
use d2_sim::drlg::{Drlg, DrlgData, DrlgRoomId, Dungeon, LevelDef, TileInfo, TileSource};
use d2_sim::game::Game;
use d2_sim::monsters::init::{GameInfo, MonstatsExtra};
use d2_sim::monsters::population::PopTables;
use d2_sim::rng::Seed;
use d2_sim::skills::use_::{MissileAim, UseState};
use d2_sim::skills::{SkillEntry, SkillTables, LEVEL_CAP_114D};
use d2_sim::stats::{StatData, StatTable};
use d2_sim::units::hooks::{MonsterInfo, UnitData};
use d2_sim::units::lifecycle::AllocRequest;
use d2_sim::units::lists::client_state;
use d2_sim::units::{RoomId, UnitId, UnitType};
use d2_sim::wiring::action::{ActionHooks, ActionTables, DrlgWorld, Pending};
use d2_sim::wiring::worldgen::{
    SharedTypes, WorldPending, WorldSim, WorldState, WorldTables, WorldTypes,
};
use d2_sim::world::waypoints::{WaypointData, NO_WAYPOINT};

// ---- constants -----------------------------------------------------------------------

/// The DRLG init seed of `outdoor.md`'s recorded Act I placement
/// (`dwStartSeed` 4014346869): act 0's levels are allocated by the real
/// level types from it.
const DRLG_SEED: u32 = 644_409_375;
/// The game seed (`rng.md` §5.3).
const GAME_SEED: u32 = 1234;
/// A preset level outside the Act I chain (40 × 18 tiles at (8000,
/// 8000)): the player's level, with a waypoint and the DS1 monster.
const ISLE: u32 = 30;
const ISLE_DEF: u32 = 1104;
/// The preset level the waypoint travels to: also outside the Act I
/// chain (40 × 18 at (9000, 9000)). A chain level (e.g. the Monastery
/// Gate) would generate its outdoor neighbours, which need `lvlsub` rows
/// this fixture does not have.
const GATE: u32 = 31;
const GATE_DEF: u32 = 1105;
/// Waypoint indices (`levels.txt` `Waypoint`).
const ISLE_WP: u8 = 2;
const GATE_WP: u8 = 1;
/// The ISLE DS1's monster: DS1 sub-tile (12, 10), class 0.
const ISLE_MONSTER: (u32, u32) = (12, 10);
/// The player's position: room (8000, 8000)'s sub-tiles start at
/// (40000, 40000) (`rooms.md` §9.2, 5 sub-tiles per tile).
const PLAYER_AT: (i32, i32) = (40_020, 40_020);
/// The waypoint object's position.
const WP_AT: (i32, i32) = (40_024, 40_020);
/// Skills of the synthetic table: attack, and a right skill (srvst 4,
/// mana 4 + 1 per level, shift 8; `use.md`'s Multiple Shot vector).
const ATTACK: i32 = 0;
const MULTI: i32 = 1;

// ---- seams without a provider --------------------------------------------------

/// The action and world-generation seams no written spec provides yet
/// (positions, interaction, warp, arrival mode, transport, the DRLG
/// population reads), and a log of the calls that change something.
/// The answers are the narrowest ones (`Pending`'s defaults) except the
/// positions and the interaction record, which the test stages.
#[derive(Default)]
struct TestPending {
    pos: BTreeMap<UnitId, (i32, i32)>,
    interact: BTreeMap<UnitId, (u8, u32)>,
    sent: Vec<(UnitId, Vec<u8>)>,
    log: Vec<String>,
}

impl Pending for TestPending {
    fn position(&self, unit: UnitId) -> (i32, i32) {
        self.pos.get(&unit).copied().unwrap_or_default()
    }
    fn place(&mut self, unit: UnitId, x: i32, y: i32) {
        self.pos.insert(unit, (x, y));
    }
    fn class_has_mode(&self, _: i32, _: u8) -> bool {
        true
    }
    fn set_interact(&mut self, player: UnitId, unit_type: u8, guid: u32) {
        self.interact.entry(player).or_insert((unit_type, guid));
    }
    fn reset_interact(&mut self, player: UnitId) {
        self.interact.remove(&player);
    }
    fn interact_guid(&self, player: UnitId) -> Option<u32> {
        self.interact.get(&player).map(|i| i.1)
    }
    fn send(&mut self, player: UnitId, msg: &[u8]) {
        self.sent.push((player, msg.to_vec()));
    }
    fn warp(&mut self, _: &mut Game, player: UnitId, level: u32, tile_code: u8) {
        self.log
            .push(format!("warp {} {level} {tile_code}", player.0));
    }
    fn set_player_mode_arrival(&mut self, _: &mut Game, player: UnitId) {
        self.log.push(format!("arrival mode {}", player.0));
    }
}

impl WorldPending for TestPending {
    fn preset_created(&mut self, unit: UnitId, p: &d2_sim::monsters::population::PresetUnit) {
        self.log.push(format!(
            "preset {} class {} at {},{}",
            unit.0, p.class, p.x, p.y
        ));
    }
}

impl Outbox for TestPending {
    fn take_sent(&mut self) -> Vec<(UnitId, Vec<u8>)> {
        std::mem::take(&mut self.sent)
    }
}

/// The skill pipeline's seams without a provider (skill list, skill
/// bodies, missile creation: `use.md` OQ10, `server-skills.md` §4): the
/// player's skill list and a call log, shared with the test.
#[derive(Default)]
struct Inner {
    list: Vec<SkillEntry>,
    right: Option<SkillEntry>,
    used: Option<SkillEntry>,
    log: Vec<String>,
}

#[derive(Clone, Default)]
struct Book(Arc<Mutex<Inner>>);

impl Book {
    fn get(&self) -> MutexGuard<'_, Inner> {
        self.0.lock().unwrap()
    }
}

impl SkillSeams for Book {
    fn skill_list(&self, _: UnitId) -> Vec<SkillEntry> {
        self.get().list.clone()
    }
    fn used_skill(&self, _: UnitId) -> Option<SkillEntry> {
        self.get().used
    }
    fn set_used_skill(&mut self, _: UnitId, e: Option<SkillEntry>) {
        self.get().used = e;
    }
    fn right_skill(&self, _: UnitId) -> Option<SkillEntry> {
        self.get().right
    }
    fn find_entry(&self, _: UnitId, skill: i32) -> Option<SkillEntry> {
        self.get().list.iter().copied().find(|e| e.skill == skill)
    }
    fn entry_mode(&self, _: UnitId, e: &SkillEntry) -> u32 {
        // Skill entry +8 (`use.md` §4): attack 7 (A1), the right skill
        // 10 (SC).
        if e.skill == MULTI {
            10
        } else {
            7
        }
    }
    fn use_state(&mut self, _: UnitId, _: &SkillEntry) -> UseState {
        UseState::Usable
    }
    fn srvst(&mut self, index: u16, _: UnitId, skill: i32, lvl: i32) -> i32 {
        self.get().log.push(format!("srvst {index} {skill} {lvl}"));
        1
    }
    fn srvdo(&mut self, i: u16, _: UnitId, s: i32, l: i32, c: bool, it: bool, a: bool) -> i32 {
        self.get()
            .log
            .push(format!("srvdo {i} {s} {l} {c} {it} {a}"));
        1
    }
    fn create_skill_missile(&mut self, _: UnitId, s: i32, l: i32, m: u16, _: bool, _: MissileAim) {
        self.get().log.push(format!("missile {s} {l} {m}"));
    }
    fn room(&self, _: UnitId) -> RoomKind {
        RoomKind::Field
    }
}

// ---- DS1 / DT1 sources ---------------------------------------------------------------

#[derive(Default)]
struct Ds1s(BTreeMap<Vec<u8>, Ds1Input>);

impl Ds1Source for Ds1s {
    fn ds1(&self, path: &[u8]) -> Option<&Ds1Input> {
        self.0.get(path)
    }
}

/// A v18 DS1 of `w × h` tiles: one layer of plain floors, an empty
/// shadow layer, monsters (id = class) at DS1 sub-tile positions.
fn ds1(w: u32, h: u32, monsters: &[(u32, u32, u32)]) -> Ds1Input {
    let cells = ((w + 1) * (h + 1)) as usize;
    Ds1Input {
        version: 18,
        width: w,
        height: h,
        act: 0,
        tag_type: 0,
        walls: Vec::new(),
        orientations: Vec::new(),
        floors: vec![vec![cell::FLOOR; cells]],
        shadow: vec![0; cells],
        objects: monsters
            .iter()
            .map(|&(id, x, y)| Ds1ObjectInput {
                kind: 1,
                id,
                x,
                y,
                flags: 0,
            })
            .collect(),
        paths: Vec::new(),
    }
}

fn ds1s() -> Ds1s {
    let (x, y) = ISLE_MONSTER;
    Ds1s(BTreeMap::from([
        (
            format!("def{ISLE_DEF}.ds1").into_bytes(),
            ds1(40, 18, &[(0, x, y)]),
        ),
        (format!("def{GATE_DEF}.ds1").into_bytes(), ds1(40, 18, &[])),
    ]))
}

fn tile(o: u32, main: u32, sub: u32, rarity: u32) -> TileInfo {
    TileInfo {
        orientation: o,
        main,
        sub,
        rarity,
        material: 0,
        subtile_flags: [0; 25],
    }
}

struct Tiles(BTreeMap<Vec<u8>, Vec<TileInfo>>);

impl TileSource for Tiles {
    fn dt1(&self, path: &[u8]) -> Option<&[TileInfo]> {
        self.0.get(path).map(Vec::as_slice)
    }
}

fn tiles() -> Tiles {
    let mut t = BTreeMap::new();
    t.insert(b"floor.dt1".to_vec(), vec![tile(0, 0, 0, 1); 4]);
    let blank_tile = |sub| {
        let mut x = tile(0, 30, sub, 0);
        x.subtile_flags = [0x20; 25];
        x
    };
    t.insert(
        FIXED_LIBRARY[0].to_vec(),
        vec![blank_tile(0), blank_tile(1)],
    );
    t.insert(FIXED_LIBRARY[1].to_vec(), vec![]);
    t.insert(FIXED_LIBRARY[2].to_vec(), vec![tile(10, 0, 0, 0)]);
    Tiles(t)
}

// ---- tables -----------------------------------------------------------------------------

fn blank<T: Record>() -> T {
    T::decode(&vec![0u8; T::SIZE])
}

/// Act I sizes, offsets and Vis of `outdoor.md`'s recorded placement,
/// plus [`ISLE`] and the maze level 8; level types 1 and 3 with one DT1.
fn drlg_data() -> DrlgData {
    let mut d = DrlgData {
        levels: vec![LevelDef::default(); 150],
        ..DrlgData::default()
    };
    for l in &mut d.levels {
        l.warp = [-1; 8];
        l.level_type = 1;
    }
    let set = |d: &mut DrlgData, id: usize, ty: u32, size: (i32, i32), off: (i32, i32)| {
        d.levels[id].drlg_type = ty;
        d.levels[id].size = [size; 3];
        d.levels[id].offset = off;
    };
    set(&mut d, 1, 2, (56, 40), (0, 0));
    set(&mut d, 2, 3, (56, 96), (0, 0));
    set(&mut d, 3, 3, (80, 80), (0, 0));
    set(&mut d, 4, 3, (80, 80), (1000, 1000));
    set(&mut d, 5, 3, (80, 80), (0, 0));
    set(&mut d, 6, 3, (80, 80), (0, 0));
    set(&mut d, 7, 3, (80, 80), (0, 0));
    set(&mut d, 8, 1, (200, 200), (1500, 1000));
    set(&mut d, 17, 3, (40, 48), (0, 0));
    set(&mut d, 26, 2, (40, 18), (3000, 1000));
    set(&mut d, 27, 2, (40, 40), (0, 0));
    set(&mut d, 39, 3, (64, 64), (5000, 1148));
    set(&mut d, ISLE as usize, 2, (40, 18), (8000, 8000));
    set(&mut d, GATE as usize, 2, (40, 18), (9000, 9000));
    d.levels[8].level_type = 3;
    d.levels[2].vis = [1, 3, 0, 0, 0, 0, 0, 0];
    d.levels[3].vis = [2, 4, 17, 0, 0, 0, 0, 0];
    d.levels[1].vis = [2, 0, 0, 0, 0, 0, 0, 0];
    d.levels[4].vis = [3, 0, 0, 0, 0, 0, 0, 0];
    d.levels[17].vis = [3, 0, 0, 0, 0, 0, 0, 0];
    let mut files = vec![Vec::new(); 32];
    files[0] = b"floor.dt1".to_vec();
    d.lvltypes = vec![
        vec![Vec::new(); 32],
        files.clone(),
        vec![Vec::new(); 32],
        files,
    ];
    d
}

/// lvlprest rows 0..1199 (`Files` 1, DT1 mask 1), the preset levels'
/// rows (town Files 0, Monastery Gate, Outer Cloister Files 3, ISLE, the
/// travel level) and
/// the outdoor cell row 1103 (16 × 16, Files 2).
fn preset_data() -> PresetData {
    let mut defs: Vec<PresetDef> = (0..1200)
        .map(|i| PresetDef {
            def: i,
            files: 1,
            dt1_mask: 1,
            populate: 1,
            file: Default::default(),
            ..PresetDef::default()
        })
        .collect();
    for d in &mut defs {
        d.file[0] = format!("def{}.ds1", d.def).into_bytes();
    }
    for (i, level, files) in [
        (1100, 1, 0),
        (1101, 26, 1),
        (GATE_DEF, GATE, 1),
        (1102, 27, 3),
        (ISLE_DEF, ISLE, 1),
        (1103, 0, 2),
    ] {
        defs[i as usize].level_id = level;
        defs[i as usize].files = files;
    }
    defs[1103].size_x = 16;
    defs[1103].size_y = 16;
    PresetData {
        defs,
        monpreset_acts: Default::default(),
        monpreset: Vec::new(),
        monstats_count: 1,
        superuniques_count: 0,
        hdm_item: -1,
        tables: PresetTables::spec().expect("preset-tables.tsv"),
    }
}

fn outdoor_data(pd: &PresetData) -> OutdoorData {
    OutdoorData {
        levels: vec![
            SubDefs {
                sub_type: -1,
                sub_theme: -1,
                sub_waypoint: -1,
                sub_shrine: -1,
            };
            150
        ],
        presets: pd
            .defs
            .iter()
            .map(|d| OutdoorPreset {
                size_x: d.size_x as i32,
                size_y: d.size_y as i32,
                files: d.files,
            })
            .collect(),
        subs: Vec::new(),
    }
}

fn maze_data() -> MazeData {
    MazeData {
        rows: vec![MazeRow {
            level: 8,
            rooms: [1; 3],
            size_x: 24,
            size_y: 24,
            merge: 0,
        }],
        prest_files: (0..1200).map(|d| (d, 1)).collect(),
        specials: Specials::shipped(),
    }
}

/// Monster class 0: killable, AI 1 (Idle), no skills, no minions.
fn monster_class() -> Monstats {
    let mut m: Monstats = blank();
    m.killable = true;
    m.velocity = 1;
    (m.drain, m.drain_n, m.drain_h) = (100, 100, 100);
    m.montype = 0xFFFF;
    m.ai = 1;
    (m.aidel, m.aidel_n, m.aidel_h) = (15, 15, 15);
    (m.skill1, m.skill2, m.skill3) = (0xFFFF, 0xFFFF, 0xFFFF);
    m.rarity = 1;
    (m.mingrp, m.maxgrp) = (1, 1);
    (m.minion1, m.minion2) = (0xFFFF, 0xFFFF);
    m.enabled = true;
    m.isspawn = true;
    m
}

/// levels.txt: no monsters, act by level id; waypoints at [`ISLE`] and
/// [`GATE`] only.
fn levels() -> Vec<Levels> {
    let mut v: Vec<Levels> = vec![blank(); 150];
    for (i, l) in v.iter_mut().enumerate() {
        for m in [
            &mut l.mon1,
            &mut l.mon2,
            &mut l.mon3,
            &mut l.mon4,
            &mut l.mon5,
            &mut l.mon6,
            &mut l.mon7,
            &mut l.mon8,
            &mut l.mon9,
            &mut l.mon10,
            &mut l.mon11,
            &mut l.mon12,
            &mut l.mon13,
            &mut l.mon14,
            &mut l.mon15,
            &mut l.mon16,
            &mut l.mon17,
            &mut l.mon18,
            &mut l.mon19,
            &mut l.mon20,
            &mut l.mon21,
            &mut l.mon22,
            &mut l.mon23,
            &mut l.mon24,
            &mut l.mon25,
            &mut l.nmon1,
            &mut l.umon1,
        ] {
            *m = 0xFFFF;
        }
        l.act = d2_sim::drlg::act_of_level(i as u32);
        l.waypoint = NO_WAYPOINT;
    }
    v[ISLE as usize].waypoint = ISLE_WP;
    v[GATE as usize].waypoint = GATE_WP;
    v
}

/// A synthetic itemstatcost: 359 stats, no ops, fixed up.
fn stat_data() -> Arc<StatData> {
    let (n, size) = (359, Itemstatcost::SIZE);
    let mut records = vec![0u8; n * size];
    for (s, r) in records.chunks_mut(size).enumerate() {
        for o in [0x32, 0x48, 0x4A, 0x56, 0x58, 0x5A, 0x5C] {
            r[o..o + 2].copy_from_slice(&0xFFFFu16.to_le_bytes());
        }
        r[0..2].copy_from_slice(&(s as u16).to_le_bytes());
    }
    let mut t = BinTable {
        name: "itemstatcost".into(),
        source: "synthetic".into(),
        count: n,
        record_size: size,
        records,
    };
    stat_ops(&mut t);
    Arc::new(StatData {
        stats: StatTable::from_fixed(&t).expect("itemstatcost"),
        ..StatData::default()
    })
}

fn skill_rec() -> Skills {
    let mut s: Skills = blank();
    for f in [
        &mut s.auralencalc,
        &mut s.aurarangecalc,
        &mut s.aurastatcalc1,
        &mut s.calc1,
        &mut s.calc2,
        &mut s.calc3,
        &mut s.calc4,
        &mut s.passivecalc1,
        &mut s.passivecalc2,
        &mut s.passivecalc3,
        &mut s.passivecalc4,
        &mut s.passivecalc5,
        &mut s.petmax,
        &mut s.skpoints,
        &mut s.tohitcalc,
        &mut s.dmgsympercalc,
        &mut s.edmgsympercalc,
        &mut s.elensympercalc,
        &mut s.delay,
        &mut s.perdelay,
    ] {
        *f = 0xFFFF_FFFF;
    }
    s.skilldesc = 0xFFFF;
    s.charclass = 0xFF;
    (s.reqskill1, s.reqskill2, s.reqskill3) = (0xFFFF, 0xFFFF, 0xFFFF);
    s.itypea1 = 0xFFFF;
    s.srvmissile = 0xFFFF;
    s.intown = true;
    s.ingame = true;
    s
}

fn skills() -> SkillTables {
    let mut v = vec![skill_rec(), skill_rec()];
    let m = &mut v[MULTI as usize];
    (m.srvstfunc, m.mana, m.lvlmana, m.manashift) = (4, 4, 1, 8);
    SkillTables {
        skills: v,
        skilldesc: vec![blank::<Skilldesc>()],
        missiles: Vec::new(),
        skills_code: Vec::new(),
        miss_code: Vec::new(),
        level_cap: LEVEL_CAP_114D,
        stat_count: 359,
    }
}

fn combat_tables() -> CombatTables {
    let mut d: Difficultylevels = blank();
    (d.monsterfreezedivisor, d.monstercolddivisor) = (1, 1);
    (d.lifestealdivisor, d.manastealdivisor) = (1, 1);
    CombatTables {
        charstats: vec![blank::<Charstats>(); 7],
        difficultylevels: vec![d; 3],
        monstats: vec![monster_class()],
        monstats2: vec![blank::<Monstats2>()],
        hitclass: vec![*b"none", *b"hth "],
    }
}

fn vitals() -> VitalsTables {
    VitalsTables {
        charstats: vec![blank::<Charstats>(); 7],
        experience: vec![blank()],
    }
}

/// One waypoint object class (0): operate 23, init 17.
fn waypoint_data() -> WaypointData {
    let mut o: Objects = blank();
    o.operatefn = 23;
    o.initfn = 17;
    o.framecnt1 = 15 << 8;
    WaypointData::new(&levels(), &[o])
}

// ---- the game --------------------------------------------------------------------------

type Sim = SimGame<WorldSim<TestPending>, ActionWorld>;

/// Manual host clock (ms), injected into the host (`tick.md` §8).
struct Ms(u32);

impl Clock for Ms {
    fn now_ms(&mut self) -> u32 {
        self.0
    }
}

type Link = LocalLink<Sim, ProtoSizes, PendingSession, Ms>;

/// The local link, recording every S→C chunk the bridge receives.
struct Tap {
    inner: Link,
    chunks: Vec<Vec<u8>>,
}

impl ServerLink for Tap {
    fn protocol_version(&self) -> u32 {
        self.inner.protocol_version()
    }
    fn send(&mut self, queue: SendQueue, msg: &[u8]) -> Result<Sent, LinkError> {
        self.inner.send(queue, msg)
    }
    fn pump(&mut self) -> Result<Pumped, LinkError> {
        self.inner.pump()
    }
    fn receive(&mut self) -> Vec<Vec<u8>> {
        let got = self.inner.receive();
        self.chunks.extend(got.iter().cloned());
        got
    }
}

const ALIVE: PlayerGate = PlayerGate {
    mode: 1,
    uninterruptable: false,
};

/// Steps 1–3 before the first host frame: game creation, the generated
/// level, the player's room streamed, the player and the waypoint object
/// allocated there, the client joined (its room not yet set: the first
/// tick's room change activates the rooms near the player).
struct Fx {
    bridge: Bridge<Tap>,
    player: UnitId,
    wp: u32,
    book: Book,
    /// The ISLE level's DRLG rooms.
    level_rooms: Vec<DrlgRoomId>,
}

impl Fx {
    fn new(game_seed: u32) -> Self {
        // 1. Game creation: act 0's DRLG through the level-type
        // dispatcher on the recorded init seed; regions on the game seed.
        let data = Arc::new(drlg_data());
        let pd = preset_data();
        let types = SharedTypes::new(WorldTypes::new(
            data.clone(),
            Maze::new(maze_data()),
            pd.clone(),
            outdoor_data(&pd),
            Box::new(ds1s()),
            Box::new(SubFileMap::default()),
        ));
        let mut handle = types.clone();
        let drlg = Drlg::create(0, DRLG_SEED, 0, 0, false, &data, &mut handle).expect("act 0");
        let mut dungeon = Dungeon::default();
        dungeon.acts[0] = Some(drlg);
        let world = DrlgWorld {
            dungeon,
            data,
            tiles: Box::new(tiles()),
            types: Box::new(handle),
        };
        let tables = ActionTables {
            missiles: Vec::new(),
            skills: skills(),
            combat: combat_tables(),
            levels: levels(),
            skill_modes: vec![[0; 3]],
        };
        let hooks = ActionHooks::new(
            Arc::new(tables),
            world,
            Seed::init_low(game_seed),
            TestPending::default(),
        );
        let wt = WorldTables {
            pop: PopTables::from_records(&levels(), &[monster_class()], &[blank()], &[]),
            monstats: vec![monster_class()],
            monstats2: vec![blank()],
            monlvl: vec![blank::<Monlvl>(); 10],
            levels: levels(),
            difficultylevels: vec![blank::<Difficultylevels>(); 3],
            monstats_extra: vec![MonstatsExtra::default()],
            components: vec![[0; 16]],
            ..WorldTables::default()
        };
        let state = WorldState::new(types, Arc::new(wt), GameInfo::default());
        let unit_data = UnitData {
            monsters: vec![MonsterInfo {
                enabled: true,
                aidel: [15; 3],
                moves: 1 << 4,
            }],
            ..UnitData::default()
        };
        let mut sim = WorldSim::new(stat_data(), unit_data, hooks, state);
        sim.create_regions();
        let mut game = Game::new();
        game.lists.ensure_act(0).unwrap();

        // 2. The level, by the real preset generator; the player's room
        // streamed (`rooms.md` §9.2).
        let (level_rooms, room) = sim
            .action
            .hooks()
            .drlg
            .with_act(0, &mut game.lists, |d, svc| {
                let l = d.get_or_alloc_level(svc.data, svc.types, ISLE)?;
                d.generate_level(svc.data, svc.types, l)?;
                let rooms = d.level_rooms(l);
                let a = *rooms
                    .iter()
                    .find(|&&r| d.room(r).rect == d2_sim::drlg::TileRect::new(8000, 8000, 8, 8))
                    .expect("room at the level origin");
                let active = d.stream_room(svc, a)?.expect("active");
                Ok::<_, d2_sim::drlg::DrlgError>((rooms, active))
            })
            .expect("act 0")
            .expect("generated");

        // 3. The player (a sorceress, class 1) and the waypoint object.
        let mut alloc = |ty, class, (x, y): (i32, i32)| {
            let req = AllocRequest {
                ty,
                class,
                room: Some(room),
                add: true,
                fixed_guid: None,
                mode: 1,
                allied: ty == UnitType::Player,
            };
            sim.action
                .with(&mut game, |g, v| v.allocate(g, &req, x, y))
                .expect("allocated")
        };
        let object = alloc(UnitType::Object, 0, WP_AT);
        let player = alloc(UnitType::Player, 1, PLAYER_AT);
        // Players are allocated in mode 0; neutral (`units.md` §2).
        sim.action.sys.units.get_mut(player).unwrap().mode = 1;
        // Both waypoints known (`waypoints.md` §2).
        let rec = sim.action.hooks().waypoints.entry(player).or_default();
        rec.get_mut(0).set(ISLE_WP.into()).unwrap();
        rec.get_mut(0).set(GATE_WP.into()).unwrap();
        sim.action
            .with(&mut game, |_, v| v.set_base(player, 8, 4000));
        let wp = game.lists.unit(object).unwrap().guid;

        let mut s: Sim = SimGame::with_events(game, sim);
        s.world.waypoints = Some(waypoint_data());
        s.join(LOCAL_CLIENT_ID, Some(player), None, client_state::IN_GAME)
            .unwrap();
        s.set_player(
            player,
            PlayerFields {
                gate: ALIVE,
                data: Some(PlayerData { last_accept: 0 }),
            },
        );
        s.set_unit(player, facts(PLAYER_AT));
        s.set_unit(object, facts(WP_AT));
        let multi = SkillEntry {
            skill: MULTI,
            base: 10,
            owner_guid: -1,
            ..SkillEntry::default()
        };
        let book = Book::default();
        {
            let mut b = book.get();
            b.list = vec![
                SkillEntry {
                    skill: ATTACK,
                    base: 1,
                    owner_guid: -1,
                    ..SkillEntry::default()
                },
                multi,
            ];
            b.right = Some(multi);
        }
        s.skills = Some(Box::new(WiredSkills::new(vitals(), book.clone())));

        let link = LocalLink::new(Host::new(
            s,
            ProtoSizes,
            PendingSession::default(),
            Ms(1000),
        ));
        let tap = Tap {
            inner: link,
            chunks: Vec::new(),
        };
        let bridge = Bridge::with_dispatch(tap, Dispatch::from_spec().unwrap()).unwrap();
        Fx {
            bridge,
            player,
            wp,
            book,
            level_rooms,
        }
    }

    fn sim(&mut self) -> &mut Sim {
        &mut self.bridge.link_mut().inner.host_mut().game
    }

    fn sim_ref(&self) -> &Sim {
        &self.bridge.link().inner.host().game
    }

    fn pending(&mut self) -> &mut TestPending {
        &mut self.sim().events.action.hooks().x
    }

    fn guid(&self, u: UnitId) -> u32 {
        self.sim_ref().game.lists.unit(u).unwrap().guid
    }

    fn mode(&self, u: UnitId) -> u32 {
        self.sim_ref().events.action.sys.units.get(u).unwrap().mode
    }

    /// Stat `s` of unit `u` (unit getter, `stats.md`).
    fn stat(&mut self, u: UnitId, s: u16) -> i32 {
        let sim = self.sim();
        sim.events.action.with(&mut sim.game, |_, v| v.stat(u, s))
    }

    /// The player's timer events (type, expiry).
    fn player_timers(&self) -> Vec<(u8, i32)> {
        let t = &self.sim_ref().game.timers;
        t.unit_timers(self.player)
            .into_iter()
            .filter_map(|i| Some((t.event(i)?.0, t.expire(i)?)))
            .collect()
    }

    fn monsters(&self) -> Vec<UnitId> {
        let mut v = self.sim_ref().game.lists.units_of_type(UnitType::Monster);
        v.sort();
        v
    }

    /// Every error so far: world adapters, level types, action adapters,
    /// the unit dispatch, the world handlers' faults.
    fn errors(&self) -> Vec<String> {
        let s = self.sim_ref();
        let mut e = s.events.errors();
        e.extend(s.world.faults.iter().map(|f| format!("{f:?}")));
        e
    }

    /// Sends `msgs` through the bridge, advances the host clock 40 ms
    /// (one tick, `tick.md` §1) and runs one bridge frame. The frame's
    /// result codes, the S→C bytes the client received, the bridge
    /// report.
    fn step(&mut self, msgs: &[Vec<u8>]) -> Step {
        for m in msgs {
            assert_eq!(self.bridge.send_bytes(m).unwrap(), Sent::Queued);
        }
        self.bridge.link_mut().inner.host_mut().clock.0 += 40;
        let report = self.bridge.frame().unwrap();
        let host = self.bridge.link().inner.last_frame();
        let codes = host
            .messages
            .iter()
            .map(|h| match h.handled {
                Handled::Game(Outcome::Dispatched(c)) => (h.id, Some(c)),
                _ => (h.id, None),
            })
            .collect();
        Step {
            codes,
            received: self.bridge.log().unowned.clone(),
            report,
        }
    }
}

const LOCAL_CLIENT_ID: u32 = d2_client::bridge::LOCAL_CLIENT;

fn facts((x, y): (i32, i32)) -> UnitFacts {
    UnitFacts {
        act: 0,
        pos: Pos { x, y },
        owner: None,
    }
}

/// One bridge frame: (C→S id, result) per drained message, the
/// bridge's unowned S→C counts so far, the frame report.
#[derive(Debug, PartialEq, Eq)]
struct Step {
    codes: Vec<(u8, Option<ResultCode>)>,
    received: BTreeMap<u8, u64>,
    report: FrameReport,
}

fn bytes<M: d2_proto::FixedMessage>(m: &M) -> Vec<u8> {
    d2_client::bridge::intent::encode(m)
}

// ---- the run ----------------------------------------------------------------------------

/// One recorded bridge frame: the C→S bytes sent, the drained results,
/// the S→C chunks the client received.
type Frame = (Vec<Vec<u8>>, Step, Vec<Vec<u8>>);

/// Everything a run leaves behind, compared byte for byte between runs.
#[derive(Debug, PartialEq, Eq)]
struct Transcript {
    /// Per bridge frame: the C→S bytes sent, the drained results, the
    /// S→C chunks the client received.
    frames: Vec<Frame>,
    game_frame: i32,
    game_seed: Seed,
    /// Monsters: GUID, unit seed, position, mode.
    monsters: Vec<(u32, Seed, (i32, i32), u32)>,
    active_rooms: Vec<RoomId>,
    player_mode: u32,
    player_mana: i32,
    pending_log: Vec<String>,
    skill_log: Vec<String>,
    unhandled: Vec<(u32, u8, usize)>,
    client: (u64, u64, usize),
    errors: Vec<String>,
}

/// A recording bridge frame.
fn record(fx: &mut Fx, frames: &mut Vec<Frame>, msgs: Vec<Vec<u8>>) {
    let before = fx.bridge.log().unowned.values().sum::<u64>();
    let step = fx.step(&msgs);
    // The bridge has no S→C handler yet (`bridge-dispatch.tsv`: every id
    // TBD), so each received message is counted unowned; the chunks are
    // taken from the host's flush report.
    let chunks = std::mem::take(&mut fx.bridge.link_mut().chunks);
    let after = fx.bridge.log().unowned.values().sum::<u64>();
    assert_eq!(after - before, step.report.messages as u64);
    frames.push((msgs, step, chunks));
}

fn run() -> Transcript {
    run_with(GAME_SEED)
}

fn run_with(game_seed: u32) -> Transcript {
    let mut fx = Fx::new(game_seed);
    let mut frames = Vec::new();
    let (player, wp) = (fx.player, fx.wp);
    // No step below has a defined S→C message that fires (see each step):
    // every frame's received bytes are asserted empty.
    let none: Vec<Vec<u8>> = Vec::new();

    // Before any frame: one active room (the player's), no monster, the
    // generated level's 15 preset rooms (40 × 18 tiles, `preset.md`
    // §3.2).
    assert_eq!(fx.level_rooms.len(), 15);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 1);
    assert!(fx.monsters().is_empty());

    // Frame 1 at 1000 ms: the tick driver starts its clock; no tick.
    let r = fx.bridge.frame().unwrap();
    assert!(!r.ticked);

    // Frame 2 (tick 1): the client's room change activates the rooms
    // near the player's (`rooms.md` §4.1: 4 rooms); the room pass
    // creates the DS1's preset monster at its sub-tile (`population.md`
    // §11.1). No step sends.
    record(&mut fx, &mut frames, vec![]);
    assert_eq!(frames[0].2, none);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 4);
    let monsters = fx.monsters();
    assert_eq!(monsters.len(), 1, "the DS1 preset monster");
    let monster = monsters[0];
    let mpos = fx.pending().pos[&monster];
    assert_eq!(mpos, (40_012, 40_010));
    assert_eq!(fx.pending().log, ["preset 2 class 0 at 12,10"]);
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    fx.sim().set_unit(monster, facts(mpos));

    // 4. Right skill at the monster (C→S 0x0C, `use.md` §1): accepted
    // (0), mana charged at start (the Multiple Shot vector: 3,328 of
    // 4,000 in 1/256 units), srvst 4 run, mode SC (10) set. STOP: the
    // mode start's animation schedule (`units.md` §4.1–§4.2) needs the
    // AnimData record `0x00620F00`, which the action wiring does not
    // route (`UnitHooks::anim_record` default) → `AnimError::NoRecord`;
    // no event 0 / 1 is scheduled, so no srvdo, no missile
    // (`SkillSeams::create_skill_missile`), no hit, kill, experience or
    // drop.
    let cast = bytes(&RightSkill {
        x: mpos.0 as u16,
        y: mpos.1 as u16,
    });
    assert_eq!(cast, [0x0C, 0x4C, 0x9C, 0x4A, 0x9C]);
    record(&mut fx, &mut frames, vec![cast]);
    assert_eq!(frames[1].1.codes, [(0x0C, Some(ResultCode::Done))]);
    assert_eq!(frames[1].2, none);
    assert_eq!(fx.mode(player), 10);
    assert_eq!(fx.stat(player, 8), 4000 - 3328);
    assert_eq!(fx.book.get().log, ["srvst 4 1 10"]);
    assert_eq!(fx.errors(), ["Unit(Anim(NoRecord))"]);
    assert!(fx.player_timers().is_empty(), "no animation events");
    assert_eq!(fx.mode(monster), 1, "the monster is untouched");
    let missiles = fx
        .sim_ref()
        .events
        .action
        .sys
        .hooks
        .missile_store()
        .missiles()
        .count();
    assert_eq!(missiles, 0);

    // 5. Pick-up (0x16), buy (0x32), sell (0x33). STOP: 0x16 has no
    // owner spec (inventory spec not written, `server-items.md` §2);
    // the vendor ids have handlers (`world/vendors.md` §7) but the
    // server's `ActionWorld` has no vendor provider
    // (`server-world.md` §6): all three are stubs (result 0, recorded).
    // (No item exists to pick up or sell: the kill above never ran.)
    let pick = bytes(&PickItem {
        type_: 4,
        id: 0x7777,
        cursor: 0,
    });
    let buy = bytes(&BuyItem {
        npc: 0x10,
        item: 0x20,
        mode: 0,
        cost: 0,
    });
    let sell = bytes(&SellItem {
        npc: 0x10,
        item: 0x21,
        tab: 0,
        cost: 0,
    });
    record(&mut fx, &mut frames, vec![pick, buy, sell]);
    let done = Some(ResultCode::Done);
    assert_eq!(
        frames[2].1.codes,
        [(0x16, done), (0x32, done), (0x33, done)]
    );
    assert_eq!(frames[2].2, none);
    assert_eq!(
        fx.sim_ref().unhandled,
        [
            (LOCAL_CLIENT_ID, 0x16, 13),
            (LOCAL_CLIENT_ID, 0x32, 17),
            (LOCAL_CLIENT_ID, 0x33, 17)
        ]
    );

    // 6. Waypoint travel (C→S 0x49, `waypoints.md` §6–§7): accepted,
    // the interaction closed (rule 2), the destination bit tested (rule
    // 3), tile code 0 (rule 4), the warp called (rule 5), the spawn
    // search streamed the destination's room (rule 7's `0x00619E50`: 5
    // active rooms), the arrival node prepended (rule 8). STOP: the
    // warp's same-act placement `0x00554EA0` belongs to the unwritten
    // path / placement spec (`Pending::warp`), so the player stays in
    // the ISLE room and rule 7's room test sends no S→C 0x0D.
    fx.pending().interact.insert(player, (2, wp));
    let travel = bytes(&TakeOrCloseWp {
        wp,
        level: GATE as u16,
    });
    let mut want = vec![0x49];
    want.extend_from_slice(&wp.to_le_bytes());
    want.extend_from_slice(&[GATE as u8, 0, 0, 0]);
    assert_eq!(travel, want);
    record(&mut fx, &mut frames, vec![travel]);
    assert_eq!(frames[3].1.codes, [(0x49, done)]);
    assert_eq!(frames[3].2, none);
    assert!(fx.pending().interact.is_empty());
    assert_eq!(
        fx.pending().log,
        [
            "preset 2 class 0 at 12,10".to_string(),
            format!("warp {} {GATE} 0", player.0)
        ]
    );
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 5);
    let arrivals = &fx.sim_ref().world.arrivals.0;
    assert_eq!(arrivals.len(), 1);
    assert_eq!((arrivals[0].x, arrivals[0].y), PLAYER_AT);
    assert_eq!(fx.errors(), ["Unit(Anim(NoRecord))"]);

    // The client: 5 frames, 4 server ticks, no message received, so no
    // unit in the model and nothing unowned, rejected or discarded.
    let w = fx.bridge.world();
    let client = (w.frames, w.server_ticks, w.units.len());
    assert_eq!(client, (5, 4, 0));
    let log = fx.bridge.log();
    assert!(log.unowned.is_empty() && log.rejected.is_empty() && log.discarded.is_empty());

    let player_mana = fx.stat(player, 8);
    let skill_log = fx.book.get().log.clone();
    let s = fx.sim_ref();
    let x = &s.events.action.sys;
    Transcript {
        game_frame: s.game.frame,
        game_seed: x.hooks.game_seed,
        monsters: fx
            .monsters()
            .iter()
            .map(|&m| {
                (
                    fx.guid(m),
                    x.units.get(m).unwrap().seed,
                    x.hooks.x.pos[&m],
                    x.units.get(m).unwrap().mode,
                )
            })
            .collect(),
        active_rooms: s.game.lists.active_rooms(0),
        player_mode: fx.mode(player),
        player_mana,
        pending_log: x.hooks.x.log.clone(),
        skill_log,
        unhandled: s.unhandled.clone(),
        client,
        errors: fx.errors(),
        frames,
    }
}

// Covers: specs/client/bridge.md §3 r1, §3 r2, §3 r3
#[test]
fn single_player_end_to_end() {
    let t = run();
    assert_eq!(t.game_frame, 4);
    assert_eq!(t.frames.len(), 4);
}

/// Same seeds → the same run: every C→S byte, result code, S→C chunk,
/// seed, unit, room and log, twice.
#[test]
fn same_seed_same_run() {
    assert_eq!(run(), run());
}

/// The comparison sees the seed: another game seed gives other unit
/// seeds (`rng.md` §5.3), so the transcripts differ.
#[test]
fn other_seed_other_run() {
    let (a, b) = (run(), run_with(GAME_SEED + 1));
    assert_ne!(a.game_seed, b.game_seed);
    assert_ne!(a.monsters, b.monsters);
    assert_eq!(a.frames, b.frames, "the wire is seed-independent here");
}
