// Spec: specs/client/bridge.md §3; specs/sim/intents-events.md §1–§3; specs/sim/tick.md §3, §4; specs/drlg/levels.md §5; specs/drlg/preset.md §3, §8, §9; specs/drlg/rooms.md §4.1; specs/monsters/population.md §11.1; specs/skills/use.md §1, §4, §5.2, §5.4; specs/formats/animdata.md §5; specs/sim/units.md §4.1, §4.2, §4.6; specs/missiles/missiles.md §R2–§R6; specs/combat/damage.md §5.2, §7.1, §7.2; specs/combat/vitals.md §2, §3, §4.2, §4.3; specs/items/treasure.md §3, §7, §8; specs/world/npc.md §2, §3, §9; specs/world/vendors.md §3, §4, §7, §9; specs/world/quests.md §1.5; specs/world/cube.md §1, §2, §3, §8; specs/world/waypoints.md §6, §7; specs/items/inventory-moves.md §6, §7, §11 (end to end)
// Spec: specs/world/quests-act1.md (§10, split out of `quests.md`)
// Spec: specs/items/inventory.md (the sections other than §6–§11)
//! End-to-end single player: the bridge (`d2_client::bridge`) on its
//! local link (`bridge::local::LocalLink`) over the in-process
//! `d2-server` host, whose game is `SimGame` on the fully wired `d2-sim`
//! (`wiring::worldgen::WorldSim` around `wiring::action::ActionSim`),
//! from synthetic tables and synthetic DS1 files (no game files).
//!
//! The run, step by step (`docs/handoff/e2e-single-player.md` lists
//! where each step stops and why):
//!
//! 1. game creation on a fixed seed: act 0's DRLG through the level-type
//!    dispatcher (`WorldTypes`: the Act I outdoor placer, preset inits),
//!    the regions on the game seed;
//! 2. a preset level generated by the real generator (`drlg::preset`),
//!    one of its rooms streamed for the player;
//! 3. the player joins; the first host tick runs the client room change
//!    (`rooms.md` §4.1: rooms near the player become active) and the room
//!    pass (`population.md` §11.1: the DS1's preset monster is created);
//! 4. a right-skill cast at the monster (C→S 0x0C): the handler runs, the
//!    mode starts and its animation schedule (`units.md` §4.1–§4.2)
//!    reads the AnimData record of the unit's composed COF name
//!    (`animdata.md` §5); the action frame (event 0) runs the do
//!    function and the real missile creation; the missile flies, hits,
//!    kills (`damage.md` §5.2, §7.1, §7.2): the death mode with its
//!    target and the player's experience (`vitals.md` §4);
//! 5. (a) the death start drops gold through the treasure walk as a real
//!    item unit in the monster's room (`treasure.md` §3, §7, §8); the
//!    kill's experience levels the player up (`vitals.md` §4.3 → §3);
//!    then (step 7) a stat point is spent (C→S 0x3A, `vitals.md` §2);
//!    (step 5b) pick-up of that gold (C→S 0x16, `inventory-moves.md` §7.1 →
//!    §8.1 → §10.1): the drop created it in the game's one item store,
//!    so the item-move handler finds it and the gold is credited;
//! 8. (steps 8–10) Akara on the server's `WiredWorld` (the same units):
//!    talk (C→S 0x13: S→C 0x27, 0x29, 0x28, `npc.md` §2), chat (0x2F),
//!    trade (0x38: the store generated, `vendors.md` §3, §4);
//! 9. (steps 11–18) item moves on the game's one inventory model
//!    (`inventory-moves.md` §7, `d2_sim::wiring::inventory` under
//!    `handlers::items::moves`): a cap on the ground is picked to the
//!    cursor (0x16), placed in the grid (0x18), lifted (0x19), equipped
//!    (0x1A), unequipped (0x1C), dropped (0x17), picked and placed
//!    again; each frame's tick sends the deferred item messages (§6,
//!    §11: 0x9C / 0x9D with the item bit stream, `items/bitstream.md`:
//!    decoded with `d2-proto`'s reader and cut off by `streams`) and
//!    0x47, 0x48;
//! 10. (steps 19–22) the vendor on the same inventory (the player
//!     leaves Akara for the item moves, C→S 0x30, and talks to her
//!     again first): the cap placed by 0x18 is sold (0x33: removed, freed, the price received: S→C 0x2A
//!     kind 3), a buy (0x32) copies the store cap (`0x0055A2A0`, §7.1
//!     rule 9.2, on the inventory model) into the backpack (0x2A kind 4,
//!     its 0x9C action 4), the stored buckler is sold (a restored copy
//!     into the store, §7.2 rule 8), the stored cap is sold; quests
//!     (0x31, 0x40, 0x58) are a marked step for after the quest-host
//!     merge;
//! 11. (steps 23–25) the cube (C→S 0x2A, 0x4F, `cube.md` §1, §2, §3, §8)
//!     on the same inventory: a ground ring picked to the cursor, put in
//!     the cube (§2.4 placement: 0x9C action 4), transmuted (the ring's
//!     0x9D action 5 now, the amulet's 0x9C action 4 in the update
//!     pass);
//! 12. (step 6) a waypoint travel (C→S 0x49) runs through the
//!     handler, the warp seam and the destination's spawn search, **then
//!     stops**: this run keeps the path provider off (step 4's missile
//!     would get no path points with it on, blocker WP1), so the warp's
//!     placement stays `Pending`, the player is not moved and
//!     `waypoints.md` §7 rule 7 sends no S→C 0x0D. With the provider on
//!     the step holds: `e2e_walk.rs` (placement, 0x07 then 0x0D).
//!
//! The S→C messages the specs lay out (0x27, 0x29, 0x28, 0x2A, 0x9C,
//! 0x9D, 0x47, 0x48) are asserted byte for byte; every other frame's
//! received bytes are asserted empty: the wiring sends no S→C message on
//! the other paths (no written spec ties a mode, missile, death, stat or
//! cube message to them yet). Where a step needs behaviour no written spec
//! owns (the COF-name composer, the animation rate, the missile's path
//! and damage setup, the death start's body, the free-spot search, the
//! cube's opening, the item-move seams of `InvFx`), the fixture answers
//! the seam and says so at the answer (`docs/handoff/e2e-next.md`).
//!
//! The whole run is repeated: same seed → byte-identical transcript.

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex};

use d2_client::bridge::dispatch::Dispatch;
use d2_client::bridge::link::{LinkError, Pumped, SendQueue, Sent, ServerLink};
use d2_client::bridge::local::{LocalLink, PendingSession};
use d2_client::bridge::world::MonsterClass;
use d2_client::bridge::{Bridge, FrameReport};
use d2_data::tables::{Difficultylevels, Monlvl};
use d2_proto::client::{
    AddStatPoint, BuyItem, ClickButton, DropItem, EntityAction, EquipItem, InitEntityChat,
    InsertItemInBuffer, InteractWithEntity, ItemToCube, PickItem, RemoveBodyItem,
    RemoveItemFromBuffer, RightSkill, SellItem, TakeOrCloseWp, TerminateEntityChat,
};
use d2_server::adapters::handlers::items::{CubeParts, ItemPending};
use d2_server::adapters::handlers::skills::wired::WiredSkills;
use d2_server::adapters::handlers::world::{ActionWorld, WiredWorld};
use d2_server::adapters::{PlayerData, PlayerFields, ProtoSizes, SimGame, UnitFacts};
use d2_server::dispatch::Outcome;
use d2_server::host::{Handled, Host};
use d2_server::seams::{Clock, PlayerGate, Pos, ResultCode};
use d2_sim::drlg::collision::bits;
use d2_sim::drlg::maze::Maze;
use d2_sim::drlg::outdoor::SubFileMap;
use d2_sim::drlg::{Drlg, DrlgRoomId, Dungeon};
use d2_sim::game::Game;
use d2_sim::items::inventory::InvItem;
use d2_sim::items::moves::Owner;
use d2_sim::items::tables::ItemRec;
use d2_sim::items::{flag, q, ty, ItemRequest, ItemTables};
use d2_sim::missiles::unit_flag;
use d2_sim::monsters::init::{GameInfo, MonstatsExtra};
use d2_sim::monsters::population::PopTables;
use d2_sim::rng::Seed;
use d2_sim::skills::SkillEntry;
use d2_sim::units::hooks::{MonsterInfo, UnitData};
use d2_sim::units::lifecycle::AllocRequest;
use d2_sim::units::lists::client_state;
use d2_sim::units::{RoomId, UnitId, UnitType};
use d2_sim::wiring::action::{ActionHooks, ActionTables, DrlgWorld, Pending};
use d2_sim::wiring::economy::{DeathDrops, DropSpot, DropTables, GameFields, ItemSpawn, ItemStore};
use d2_sim::wiring::worldgen::{SharedTypes, WorldSim, WorldState, WorldTables, WorldTypes};
use d2_sim::world::cube::{
    input_flags, kind, CraftMod, CubeData, InputSlot, ItemRecord, OutputSlot, Recipe, CUBE_PAGE,
};
use d2_sim::world::npc::{class, NpcControl};
use d2_sim::world::quests::{PlayerQuests, QuestControl, QuestTables};

mod e2e_support;
#[path = "e2e_support/world.rs"]
mod e2e_world;
use e2e_support::{
    assert_stored_sale, blank, item_tables, monstats as npc_monstats, tx, vendor_tables, Rest,
};
use e2e_support::{inv_parts, inv_tables, store, InvFx, BUC, CAP, N_MONSTATS};
use e2e_world::*;

// ---- constants -----------------------------------------------------------------------

/// The player's gold before the trade.
const PLAYER_GOLD: i32 = 5000;
/// Stat ids (`itemstatcost`; `GOLD` is the shared fixture's).
const STATPTS: u16 = 4;
const NEWSKILLS: u16 = 5;
const STRENGTH: u16 = 0;
const DEXTERITY: u16 = 2;
const LEVEL: u16 = 12;
const NEXTEXP: u16 = 30;
const ARMORCLASS: u16 = 31;

// ---- the cube's item world --------------------------------------------------------------

/// Item types of the cube's items (`cube.md` V12 shape).
const T_RING: u16 = 10;
const T_BOX: u16 = 11;
const T_AMULET: u16 = 12;
/// The cube's item records, after the vendor items (`CAP`, `BUC`) in the
/// game's one item table.
const CUBE_BOX: usize = 2;
const RING: usize = 3;
const AMULET: usize = 4;
/// The gold pile's record (`gld `), the drop's item.
const GOLD_REC: usize = 5;

/// The drop tables over the game's one item table (gold among the
/// vendor and cube items): the drop creates into the game's one item
/// store, which every item system reads with these records.
fn drop_tables() -> DropTables {
    drop_tables_from(game_item_tables(), GOLD_REC)
}

/// The game's item tables: the vendor items (`e2e_support::item_tables`:
/// cap, buckler) and the cube's items (`box `, a ring, an amulet; each
/// type is its own and type 0's).
fn game_item_tables() -> ItemTables {
    let mut t = item_tables();
    let rec = |ty: u16, code: &[u8; 4]| ItemRec {
        code: *code,
        type_: ty as i16,
        level: 1,
        ..ItemRec::default()
    };
    t.items.extend([
        rec(T_BOX, b"box "),
        rec(T_RING, b"rin "),
        rec(T_AMULET, b"amu "),
        rec(ty::GOLD, b"gld "),
    ]);
    // Gold is always normal quality (itemtypes `Normal`, `treasure.md`
    // §6 step 1) and misc.
    t.itemtypes[usize::from(ty::GOLD)].normal = 1;
    let (g, m, w) = (usize::from(ty::GOLD), usize::from(ty::MISC), t.equiv.words);
    t.equiv.bits[g * w + m / 32] |= 1 << (m % 32);
    t
}

/// One recipe (`cube.md` V12 shape without mods): one ring → a normal
/// amulet.
fn cube_data(t: &ItemTables) -> CubeData {
    let mut inputs = [InputSlot::default(); 7];
    inputs[0] = InputSlot {
        flags: input_flags::USEANY,
        item: RING as u16,
        ..InputSlot::default()
    };
    let out = OutputSlot {
        kind: kind::ITEMCODE,
        item: AMULET as u16,
        quality: q::NORMAL,
        mods: [CraftMod {
            property: -1,
            ..CraftMod::default()
        }; 5],
        ..OutputSlot::default()
    };
    CubeData {
        recipes: vec![Recipe {
            enabled: 1,
            class: 0xFF,
            numinputs: 1,
            inputs,
            outputs: [out, OutputSlot::default(), OutputSlot::default()],
            ..Recipe::default()
        }],
        items: t
            .items
            .iter()
            .map(|r| ItemRecord {
                code: r.code,
                level: r.level,
                spawnable: 1,
                ..ItemRecord::default()
            })
            .collect(),
        valshift: vec![0; 359],
        max_level: 99,
    }
}

/// The cube's calls no written spec owns (`ItemPending`: the inventory
/// pass, the item routines no items spec writes); every call is logged.
/// Placement and removal are the server's inventory model's.
#[derive(Clone, Default)]
struct CubeRest(Arc<Mutex<Vec<String>>>);

impl CubeRest {
    fn log(&self, s: String) {
        self.0.lock().unwrap().push(s);
    }
}

impl ItemPending for CubeRest {
    fn inventory_pass(&mut self, _: UnitId, _: &mut Vec<Vec<u8>>) {
        self.log("inventory pass".into());
    }
    fn duplicate(&mut self, _: UnitId, _: bool) -> Option<UnitId> {
        None
    }
    fn tempered_affix(&mut self, _: UnitId, _: bool) -> u16 {
        0
    }
    fn drop_runeword_stats(&mut self, _: UnitId) {}
    fn repair(&mut self, _: UnitId) {}
    fn recharge(&mut self, _: UnitId) {}
    fn quest_item_hook(&mut self, _: UnitId, _: UnitId, _: [u8; 4]) {}
    fn cow_portal(&mut self, _: UnitId) -> bool {
        false
    }
}

// ---- the game --------------------------------------------------------------------------

type Sim = SimGame<WorldSim<TestPending>, WiredWorld<Rest, WiredSkills>>;

/// Manual host clock (ms), injected into the host (`tick.md` §8).
struct Ms(u32);

impl Clock for Ms {
    fn now_ms(&mut self) -> u32 {
        self.0
    }
}

type Link = LocalLink<Sim, ProtoSizes, PendingSession, Ms>;

/// Akara's monster add S→C 0xAC as the client reads it
/// (`client/msg-units.md` §1.2): mode 1, no components, no type flags, no
/// source unit, no stat list. d2-sim does not build monster adds yet (the
/// server-side fields past `monsters/init.md` §24 are not specified,
/// `wiring::action::switch` module docs), so the harness delivers the
/// add of an NPC without any of those parts; the client needs her unit
/// for 0x28 (`client/msg-ui.md` §16 r4).
fn akara_add(guid: u32, class: u16, (x, y): (i32, i32)) -> Vec<u8> {
    let mut m = vec![0xAC];
    m.extend(guid.to_le_bytes());
    m.extend(class.to_le_bytes());
    m.extend((x as u16).to_le_bytes());
    m.extend((y as u16).to_le_bytes());
    m.push(128);
    m.push(14);
    // Bits, low first: mode 1 (4 bits), then five 0 presence bits.
    m.push(0x01);
    m
}

/// The local link, recording every S→C chunk the bridge receives.
struct Tap {
    inner: Link,
    chunks: Vec<Vec<u8>>,
    /// Chunks delivered after the server's at the next receive, not
    /// recorded (Akara's add, [`akara_add`]).
    inject: Vec<Vec<u8>>,
}

impl ServerLink for Tap {
    fn protocol_version(&self) -> u32 {
        self.inner.protocol_version()
    }
    fn send(&mut self, queue: SendQueue, msg: &[u8]) -> Result<Sent, LinkError> {
        self.inner.send(queue, msg)
    }
    fn pump(&mut self) -> Result<Pumped, LinkError> {
        self.inner.pump()
    }
    fn receive(&mut self) -> Vec<Vec<u8>> {
        let mut got = self.inner.receive();
        self.chunks.extend(got.iter().cloned());
        got.append(&mut self.inject);
        got
    }
}

const ALIVE: PlayerGate = PlayerGate {
    mode: 1,
    uninterruptable: false,
};

/// Steps 1–3 before the first host frame: game creation, the generated
/// level, the player's room streamed, the player and the waypoint object
/// allocated there, the client joined (its room not yet set: the first
/// tick's room change activates the rooms near the player).
struct Fx {
    bridge: Bridge<Tap>,
    player: UnitId,
    wp: u32,
    book: Book,
    /// The ISLE level's DRLG rooms.
    level_rooms: Vec<DrlgRoomId>,
    /// Akara; the player's buckler (re-sellable) and cap (one of
    /// Akara's permanent codes).
    npc: UnitId,
    buckler: UnitId,
    cap: UnitId,
    /// The cube and the cursor ring.
    cube: UnitId,
    ring: UnitId,
    cube_rest: CubeRest,
    /// The item-move seams' staged answers and log.
    inv: InvFx,
}

impl Fx {
    fn new(game_seed: u32) -> Self {
        // 1. Game creation: act 0's DRLG through the level-type
        // dispatcher on the recorded init seed; regions on the game seed.
        let data = Arc::new(drlg_data());
        let pd = preset_data();
        let types = SharedTypes::new(WorldTypes::new(
            data.clone(),
            Maze::new(maze_data()),
            pd.clone(),
            outdoor_data(&pd),
            Box::new(ds1s()),
            Box::new(SubFileMap::default()),
        ));
        let mut handle = types.clone();
        let drlg = Drlg::create(0, DRLG_SEED, 0, 0, false, &data, &mut handle).expect("act 0");
        let mut dungeon = Dungeon::default();
        dungeon.acts[0] = Some(drlg);
        let world = DrlgWorld {
            dungeon,
            data,
            tiles: Box::new(tiles()),
            types: Box::new(handle),
        };
        let tables = ActionTables {
            missiles: vec![arrow()],
            skills: skills(),
            combat: combat_tables(),
            levels: levels(),
            skill_modes: vec![[0; 8]],
            overlay_count: 0,
            monequip: Vec::new(),
        };
        let book = Book::default();
        let mut hooks = ActionHooks::new(
            Arc::new(tables),
            world,
            Seed::init_low(game_seed),
            TestPending {
                book: book.clone(),
                drops: Some(DeathDrops::new(
                    Arc::new(drop_tables()),
                    GameFields::new(Seed::init_low(game_seed), false),
                )),
                ..TestPending::default()
            },
        );
        hooks.anim_data = Some(Arc::new(anim_data()));
        hooks.vitals = Some(Arc::new(vitals()));
        let wt = WorldTables {
            pop: PopTables::from_records(&levels(), &[monster_class()], &[blank()], &[]),
            monstats: vec![monster_class()],
            monstats2: vec![blank()],
            monlvl: vec![blank::<Monlvl>(); 10],
            levels: levels(),
            difficultylevels: vec![blank::<Difficultylevels>(); 3],
            monstats_extra: vec![MonstatsExtra::default()],
            components: vec![[0; 16]],
            ..WorldTables::default()
        };
        let state = WorldState::new(types, Arc::new(wt), GameInfo::default());
        let unit_data = UnitData {
            // Class 0 (the DS1 monster) moves; the others (Akara) are
            // enabled and stand.
            monsters: (0..N_MONSTATS)
                .map(|c| MonsterInfo {
                    enabled: true,
                    aidel: [15; 3],
                    moves: if c == 0 { 1 << 4 } else { 0 },
                })
                .collect(),
            ..UnitData::default()
        };
        let mut sim = WorldSim::new(stat_data(), unit_data, hooks, state);
        sim.create_regions();
        // The world systems' game-creation seeds: the NPC control (its
        // seed from the game seed, `rng.md` §5.2) and the quests, after
        // the regions (the order among the creation seeds beyond
        // `NpcControl::new` → `QuestControl::new` is not written: a
        // fixture order, `docs/handoff/e2e-next.md` §4).
        let mut seed = sim.action.hooks().game_seed;
        let ctl = NpcControl::new(&npc_monstats(), Vec::new(), false, 0, &mut seed).expect("npc");
        let quests = QuestControl::new(&QuestTables::load().unwrap(), &mut seed).unwrap();
        sim.action.hooks().game_seed = seed;
        let mut game = Game::new();
        game.lists.ensure_act(0).unwrap();

        // 2. The level, by the real preset generator; the player's room
        // streamed (`rooms.md` §9.2).
        let (level_rooms, room) = sim
            .action
            .hooks()
            .drlg
            .with_act(0, &mut game.lists, |d, svc| {
                let l = d.get_or_alloc_level(svc.data, svc.types, ISLE)?;
                d.generate_level(svc.data, svc.types, l)?;
                let rooms = d.level_rooms(l);
                let a = *rooms
                    .iter()
                    .find(|&&r| d.room(r).rect == d2_sim::drlg::TileRect::new(8000, 8000, 8, 8))
                    .expect("room at the level origin");
                let active = d.stream_room(svc, a)?.expect("active");
                Ok::<_, d2_sim::drlg::DrlgError>((rooms, active))
            })
            .expect("act 0")
            .expect("generated");

        // 3. The player (a sorceress, class 1) and the waypoint object.
        let mut alloc = |ty, class, (x, y): (i32, i32)| {
            let req = AllocRequest {
                ty,
                class,
                room: Some(room),
                add: true,
                fixed_guid: None,
                mode: 1,
                allied: ty == UnitType::Player,
            };
            sim.action
                .with(&mut game, |g, v| v.allocate(g, &req, x, y))
                .expect("allocated")
        };
        let object = alloc(UnitType::Object, 0, WP_AT);
        let player = alloc(UnitType::Player, 1, PLAYER_AT);
        // Akara beside the player (allocated as the DS1 monster is; her
        // kind init is the monster spec's, not run here).
        let npc = alloc(UnitType::Monster, u32::from(class::AKARA), NPC_AT);
        // Players are allocated in mode 0; neutral (`units.md` §2).
        sim.action.sys.units.get_mut(player).unwrap().mode = 1;
        // Both waypoints known (`waypoints.md` §2).
        let rec = sim.action.hooks().waypoints.entry(player).or_default();
        rec.get_mut(0).set(ISLE_WP.into()).unwrap();
        rec.get_mut(0).set(GATE_WP.into()).unwrap();
        // Mana and max mana 4000 (1/256 units), gold; dexterity 25
        // (synthetic; the equip requirements, `inventory.md` §4.2, refuse
        // a stat below 1).
        sim.action.with(&mut game, |_, v| {
            v.set_base(player, 8, 4000);
            v.set_base(player, 9, 4000);
            v.set_base(player, GOLD, PLAYER_GOLD);
            v.set_base(player, DEXTERITY, 25);
        });
        let wp = game.lists.unit(object).unwrap().guid;
        let npc_guid = game.lists.unit(npc).unwrap().guid;

        // The world host: waypoints and skills (`ActionWorld`), the NPC /
        // vendor / quest systems and the cube on the same units
        // (`WiredWorld`).
        let mut rest = Rest::default();
        rest.quests.insert(player, PlayerQuests::default());
        let action = ActionWorld {
            waypoints: Some(waypoint_data()),
            skills: WiredSkills::default(),
            ..ActionWorld::default()
        };
        let mut world = WiredWorld::new(
            action,
            game_item_tables(),
            quests,
            ctl,
            vendor_tables(),
            rest,
            1000,
        );
        // Monster init embeds the NPC's interaction list (`npc.md` §2).
        world.state.add_npc(npc);
        // The game's one inventory model (`inventory.md`, the server's
        // `InvParts`): the player's inventory (`0x0063ABD0` at player
        // creation: the unit spec's, done here), the staged answers of the
        // item-move seams (`InvFx`). The vendors and the cube read and
        // write the same inventory.
        let inv = InvFx::default();
        let pg = game.lists.unit(player).unwrap().guid;
        inv.with(|r| {
            r.distance = 3;
            r.room = Some(room);
            r.pos.insert(Owner::player(pg), PLAYER_AT);
        });
        // Synthetic sizes: cap, buckler, cube 2 × 2; ring, amulet, gold
        // 1 × 1.
        let sizes = [(2, 2), (2, 2), (2, 2), (1, 1), (1, 1), (1, 1)];
        let tables = inv_tables(&world.tables, &sizes);
        world.inventory = Some(inv_parts(tables, inv.clone(), player, 1, pg));
        // The player's buckler and cap, then the cube, made by the economy
        // wiring on the game seed into the game's one item store and
        // stored (mode 0, page 0) in the player's inventory (§2.4, as a
        // loaded character's); a ring on the ground beside the player
        // (mode 3, in its room, its position in its item data, §2.2).
        let (buckler, cap, cube, ring) = world.with_economy(&mut game, &mut sim, |econ, _| {
            let mut make = |record: usize, quality: u8, ilvl: i32, spawn: ItemSpawn| {
                let mut rq = ItemRequest {
                    item: record as i32,
                    ilvl,
                    quality,
                    format: 1,
                    ..ItemRequest::default()
                };
                econ.create_item(&mut rq, false, spawn).expect("item")
            };
            let held = ItemSpawn {
                room: None,
                mode: 4,
                init_flags: 1,
            };
            let ground = ItemSpawn {
                room: Some(room),
                mode: 3,
                init_flags: 1,
            };
            let (buckler, cap) = (make(BUC, 2, 1, held), make(CAP, 2, 1, held));
            let cube = make(CUBE_BOX, q::NORMAL, 5, held);
            let ring = make(RING, q::NORMAL, 5, ground);
            (buckler, cap, cube, ring)
        });
        for item in [buckler, cap, cube] {
            store(&mut world, &mut game, &mut sim, (player, item), 0);
        }
        let rg = game.lists.unit(ring).unwrap().guid;
        world.inventory.as_mut().unwrap().state.items.insert(
            ring,
            InvItem {
                x: PLAYER_AT.0 + 1,
                y: PLAYER_AT.1 + 1,
                ..InvItem::new(rg, RING)
            },
        );
        // The cube's parts: its tables, the local date, the pending calls.
        let cube_rest = CubeRest::default();
        let mut parts = CubeParts::new(cube_data(&world.tables), Box::new(cube_rest.clone()));
        parts.staged.local_date = (15, 3);
        world.cube = Some(parts);

        let mut s: Sim = SimGame::with_world(game, sim, world);
        s.join(LOCAL_CLIENT_ID, Some(player), None, client_state::IN_GAME)
            .unwrap();
        s.set_player(
            player,
            PlayerFields {
                gate: ALIVE,
                data: Some(PlayerData { last_accept: 0 }),
            },
        );
        s.set_unit(player, facts(PLAYER_AT));
        s.set_unit(object, facts(WP_AT));
        s.set_unit(npc, facts(NPC_AT));
        let multi = SkillEntry {
            skill: MULTI,
            base: 10,
            owner_guid: -1,
            ..SkillEntry::default()
        };
        {
            let mut b = book.get();
            b.list = vec![
                SkillEntry {
                    skill: ATTACK,
                    base: 1,
                    owner_guid: -1,
                    ..SkillEntry::default()
                },
                multi,
            ];
            b.right = Some(multi);
        }

        let link = LocalLink::new(Host::new(
            s,
            ProtoSizes,
            PendingSession::default(),
            Ms(1000),
        ));
        let tap = Tap {
            inner: link,
            chunks: Vec::new(),
            inject: vec![akara_add(npc_guid, class::AKARA, NPC_AT)],
        };
        let mut bridge = Bridge::with_dispatch(tap, Dispatch::from_spec().unwrap()).unwrap();
        // Akara's class row in the client tables (an `interact` NPC), so
        // her add creates the unit.
        let mut tables = bridge.inputs().tables.clone();
        tables.monsters = vec![None; usize::from(class::AKARA) + 1];
        tables.monsters[usize::from(class::AKARA)] = Some(MonsterClass {
            npc: true,
            interact: true,
            ..MonsterClass::default()
        });
        bridge.set_tables(tables);
        Fx {
            bridge,
            player,
            wp,
            book,
            level_rooms,
            npc,
            buckler,
            cap,
            cube,
            ring,
            cube_rest,
            inv,
        }
    }

    /// What the unwritten kind init and movement specs would set for the
    /// monster: its target flags (`missiles.md` §R4.2) and its run-time
    /// collision bit at its position (`rooms.md` §10.6). The player's to-hit
    /// inputs: attack rating 100, level 1 (`hit.md` §3).
    fn stage_combat(&mut self, monster: UnitId) {
        let player = self.player;
        let sim = self.sim();
        sim.events.action.sys.units.get_mut(monster).unwrap().flags |=
            unit_flag::IS_VALID_TARGET | unit_flag::CAN_BE_ATTACKED;
        let (x, y) = sim.events.action.hooks().x.position(monster);
        let room = sim.game.lists.unit(monster).unwrap().room().unwrap();
        let game = &sim.game;
        *sim.events
            .action
            .sys
            .hooks
            .drlg
            .collision_mut(game, room, x, y)
            .expect("in a grid") |= bits::MONSTER;
        sim.events.action.hooks().x.aim_at = (x, y);
        sim.events.action.with(&mut sim.game, |_, v| {
            v.set_base(player, 19, 100);
            v.set_base(player, 12, 1);
        });
    }

    /// The missile units of the game, in id order.
    fn missiles(&self) -> Vec<UnitId> {
        let mut v = self.sim_ref().game.lists.units_of_type(UnitType::Missile);
        v.sort();
        v
    }

    /// The damage setup `0x0059F900` is the skills spec's (`Pending`):
    /// the missile's damage stats (21, 22, 1/256 points) are set here.
    fn set_missile_damage(&mut self, m: UnitId, d: i32) {
        let sim = self.sim();
        sim.events.action.with(&mut sim.game, |_, v| {
            v.set_base(m, 21, d);
            v.set_base(m, 22, d);
        });
    }

    /// The unit's timer events (type, expiry), sorted.
    fn timers(&self, u: UnitId) -> Vec<(u8, i32)> {
        let t = &self.sim_ref().game.timers;
        let mut v: Vec<_> = t
            .unit_timers(u)
            .into_iter()
            .filter_map(|i| Some((t.event(i)?.0, t.expire(i)?)))
            .collect();
        v.sort();
        v
    }

    /// The drops so far: item and spot.
    fn drops(&self) -> Vec<(UnitId, DropSpot)> {
        self.sim_ref()
            .events
            .action
            .sys
            .hooks
            .x
            .drops
            .as_ref()
            .unwrap()
            .placed
            .clone()
    }

    fn sim(&mut self) -> &mut Sim {
        &mut self.bridge.link_mut().inner.host_mut().game
    }

    fn sim_ref(&self) -> &Sim {
        &self.bridge.link().inner.host().game
    }

    fn pending(&mut self) -> &mut TestPending {
        &mut self.sim().events.action.hooks().x
    }

    /// A normal cap on the ground of the player's room at (x + 1, y + 1)
    /// of the player, made by the economy wiring on the game seed into
    /// the game's one item store; identified (callers set 0x10,
    /// `generation.md` §1.4); its position in its item data (§2.2).
    fn ground_cap(&mut self) -> UnitId {
        let room = self.sim_ref().game.lists.unit(self.player).unwrap().room();
        let sim = self.sim();
        let (game, events, world) = (&mut sim.game, &mut sim.events, &mut sim.world);
        let cap = world.with_economy(game, events, |econ, _| {
            let mut rq = ItemRequest {
                item: CAP as i32,
                ilvl: 1,
                quality: q::NORMAL,
                format: 1,
                ..ItemRequest::default()
            };
            let spawn = ItemSpawn {
                room,
                mode: 3,
                init_flags: 1,
            };
            econ.create_item(&mut rq, false, spawn).expect("cap")
        });
        events.action.sys.hooks.items.get_mut(cap).unwrap().flags |= flag::IDENTIFIED;
        let guid = game.lists.unit(cap).unwrap().guid;
        let inv = world.inventory.as_mut().unwrap();
        inv.state.items.insert(
            cap,
            InvItem {
                x: PLAYER_AT.0 + 1,
                y: PLAYER_AT.1 + 1,
                ..InvItem::new(guid, CAP)
            },
        );
        cap
    }

    /// The server host's cube parts.
    fn cube_parts(&mut self) -> &mut CubeParts {
        self.sim().world.cube.as_mut().unwrap()
    }

    /// The game's one item store.
    fn items(&mut self) -> &mut ItemStore {
        &mut self.sim().events.action.sys.hooks.items
    }

    /// The player's items in its inventory (link order), the game's one
    /// inventory model.
    fn inventory(&self) -> Vec<UnitId> {
        let inv = self.sim_ref().world.inventory.as_ref().unwrap();
        inv.state.items_of(self.player)
    }

    /// Whether the w × h cells at (x, y) of the player's page-0 grid
    /// (grid 2, `inventory.md` §1.2) are empty.
    fn page0_free(&self, x: u32, y: u32, w: u32, h: u32) -> bool {
        let inv = self.sim_ref().world.inventory.as_ref().unwrap();
        let i = inv.state.of(self.player).unwrap();
        (x..x + w).all(|cx| (y..y + h).all(|cy| i.item_at(2, cx as i32, cy as i32).is_none()))
    }

    fn guid(&self, u: UnitId) -> u32 {
        self.sim_ref().game.lists.unit(u).unwrap().guid
    }

    fn mode(&self, u: UnitId) -> u32 {
        self.sim_ref().events.action.sys.units.get(u).unwrap().mode
    }

    /// Stat `s` of unit `u` (unit getter, `stats.md`).
    fn stat(&mut self, u: UnitId, s: u16) -> i32 {
        let sim = self.sim();
        sim.events.action.with(&mut sim.game, |_, v| v.stat(u, s))
    }

    /// The player's timer events (type, expiry).
    fn player_timers(&self) -> Vec<(u8, i32)> {
        self.timers(self.player)
    }

    /// The monsters other than Akara, in id order.
    fn monsters(&self) -> Vec<UnitId> {
        let mut v = self.sim_ref().game.lists.units_of_type(UnitType::Monster);
        v.retain(|&m| m != self.npc);
        v.sort();
        v
    }

    /// Every error so far: world adapters, level types, action adapters,
    /// the unit dispatch, the world handlers' faults.
    fn errors(&self) -> Vec<String> {
        let s = self.sim_ref();
        let mut e = s.events.errors();
        e.extend(s.world.action.faults.iter().map(|f| format!("{f:?}")));
        e.extend(s.world.state.errors.iter().map(|f| format!("{f:?}")));
        if let Some(c) = &s.world.cube {
            e.extend(c.errors.iter().map(|f| format!("{f:?}")));
        }
        if let Some(i) = &s.world.inventory {
            e.extend(i.state.errors.iter().map(|f| format!("{f:?}")));
        }
        e.extend(s.tick_faults.iter().map(|f| format!("{f:?}")));
        e
    }

    /// Sends `msgs` through the bridge, advances the host clock 40 ms
    /// (one tick, `tick.md` §1) and runs one bridge frame. The frame's
    /// result codes, the S→C bytes the client received, the bridge
    /// report.
    fn step(&mut self, msgs: &[Vec<u8>]) -> Step {
        for m in msgs {
            assert_eq!(self.bridge.send_bytes(m).unwrap(), Sent::Queued);
        }
        self.bridge.link_mut().inner.host_mut().clock.0 += 40;
        let report = self.bridge.frame().unwrap();
        let host = self.bridge.link().inner.last_frame();
        let codes = host
            .messages
            .iter()
            .map(|h| match h.handled {
                Handled::Game(Outcome::Dispatched(c)) => (h.id, Some(c)),
                _ => (h.id, None),
            })
            .collect();
        Step {
            codes,
            received: self.bridge.log().unowned.clone(),
            report,
        }
    }
}

const LOCAL_CLIENT_ID: u32 = d2_client::bridge::LOCAL_CLIENT;

fn facts((x, y): (i32, i32)) -> UnitFacts {
    UnitFacts {
        act: 0,
        pos: Pos { x, y },
        owner: None,
    }
}

/// One bridge frame: (C→S id, result) per drained message, the
/// bridge's unowned S→C counts so far, the frame report.
#[derive(Debug, PartialEq, Eq)]
struct Step {
    codes: Vec<(u8, Option<ResultCode>)>,
    received: BTreeMap<u8, u64>,
    report: FrameReport,
}

fn bytes<M: d2_proto::FixedMessage>(m: &M) -> Vec<u8> {
    d2_client::bridge::intent::encode(m)
}

// ---- the run ----------------------------------------------------------------------------

/// One recorded bridge frame: the C→S bytes sent, the drained results,
/// the S→C chunks the client received.
type Frame = (Vec<Vec<u8>>, Step, Vec<Vec<u8>>);

/// Everything a run leaves behind, compared byte for byte between runs.
#[derive(Debug, PartialEq, Eq)]
struct Transcript {
    /// Per bridge frame: the C→S bytes sent, the drained results, the
    /// S→C chunks the client received.
    frames: Vec<Frame>,
    game_frame: i32,
    game_seed: Seed,
    /// Monsters: GUID, unit seed, position, mode.
    monsters: Vec<(u32, Seed, (i32, i32), u32)>,
    active_rooms: Vec<RoomId>,
    player_mode: u32,
    player_mana: i32,
    player_exp: i32,
    /// Dropped items: GUID, unit seed, position, mode; their gold.
    drops: Vec<(u32, Seed, i32, i32, u32)>,
    gold: Vec<i32>,
    pending_log: Vec<String>,
    skill_log: Vec<String>,
    /// The player's level, stat points, strength and gold at the end.
    player_stats: Vec<i32>,
    /// Akara's store: GUID, record, item seed, AC.
    store: Vec<(u32, usize, Seed, i32)>,
    npc_seed: Seed,
    rest_log: Vec<String>,
    cube_log: Vec<String>,
    /// The item-move seams' log.
    inv_log: Vec<String>,
    /// The player's items at the end (inventory link order).
    inventory: Vec<UnitId>,
    unhandled: Vec<(u32, u8, usize)>,
    client: (u64, u64, usize),
    errors: Vec<String>,
}

/// A recording bridge frame.
/// S→C 0x07 MapReveal of the room at tile (x, y) of `level`
/// (`server-messages.tsv`: x u16 @1, y u16 @3, level u8 @5).
/// S→C 0x51 AssignObject (`intents-events.md` §7.2 part A).
fn assign_object(guid: u32, class: u16, (x, y): (i32, i32), mode: u8, interact: u8) -> Vec<u8> {
    d2_sim::units::messages::assign_object(guid, class, x as u16, y as u16, mode, interact).to_vec()
}

fn map_reveal(x: u16, y: u16, level: u32) -> Vec<u8> {
    let mut b = vec![0x07];
    b.extend(x.to_le_bytes());
    b.extend(y.to_le_bytes());
    b.push(level as u8);
    b
}

/// Stages the player's interact info (the unit record's) as (type,
/// GUID), active: a path no written spec opens (the cube's opening, the
/// waypoint's operate).
fn stage_interact(fx: &mut Fx, player: UnitId, (ty, guid): (u8, u32)) {
    let rec = fx.sim().events.action.sys.units.get_mut(player).unwrap();
    rec.interact.reset();
    rec.interact.set(ty, guid);
}

fn record(fx: &mut Fx, frames: &mut Vec<Frame>, msgs: Vec<Vec<u8>>) {
    let step = fx.step(&msgs);
    // Each received message is accounted once (`bridge.md` §6,
    // `client/model.md` §4 rule 1): applied, queued on its unit, dropped
    // (unit-handler message for a unit the model does not hold), unowned
    // or rejected. No 0x04 arrives, so no update pass runs.
    let chunks = std::mem::take(&mut fx.bridge.link_mut().chunks);
    let r = &step.report;
    assert_eq!(
        r.handled + r.queued + r.dropped + r.unowned + r.rejected,
        r.messages
    );
    assert_eq!(r.drained, 0);
    frames.push((msgs, step, chunks));
}

/// A frame's received messages with each 0x9C / 0x9D item bit stream
/// (`items/bitstream.md`) checked and cut off (size byte = header size),
/// so the steps state the §11 headers: the stream must decode to its
/// exact length with `d2-proto`'s reader on the game's item tables and
/// carry the item's code when the item is still in the game.
fn streams(fx: &Fx, msgs: &[Vec<u8>]) -> Vec<Vec<u8>> {
    use d2_server::adapters::item_bits::TablesLookup;
    let sim = fx.sim_ref();
    msgs.iter()
        .map(|m| {
            let head = match m[0] {
                0x9C => 8,
                0x9D => 13,
                _ => return m.clone(),
            };
            assert_eq!(usize::from(m[2]), m.len(), "size byte {m:?}");
            let bits = d2_proto::item_bits::decode(&m[head..], &TablesLookup(&sim.world.tables))
                .unwrap_or_else(|e| panic!("stream of {m:?}: {e}"));
            let guid = u32::from_le_bytes(m[4..8].try_into().unwrap());
            let unit = sim
                .game
                .lists
                .find_unit(d2_sim::units::UnitType::Item, guid);
            if let Some(it) = unit.and_then(|u| sim.events.action.sys.hooks.items.get(u)) {
                assert_eq!(
                    bits.code, sim.world.tables.items[it.record].code,
                    "code of {guid}"
                );
            }
            let mut h = m[..head].to_vec();
            h[2] = head as u8;
            h
        })
        .collect()
}

fn run() -> Transcript {
    run_with(GAME_SEED)
}

fn run_with(game_seed: u32) -> Transcript {
    let mut fx = Fx::new(game_seed);
    let mut frames = Vec::new();
    let (player, wp) = (fx.player, fx.wp);
    // Each step says what it sends; a frame that sends nothing is
    // asserted empty.
    let none: Vec<Vec<u8>> = Vec::new();

    // Before any frame: one active room (the player's), no monster, the
    // generated level's 15 preset rooms (40 × 18 tiles, `preset.md`
    // §3.2).
    assert_eq!(fx.level_rooms.len(), 15);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 1);
    assert!(fx.monsters().is_empty());

    // Frame 1 at 1000 ms: the tick driver starts its clock; no tick.
    let r = fx.bridge.frame().unwrap();
    assert!(!r.ticked);

    // Frame 2 (tick 1): the client's room change activates the rooms
    // near the player's (`rooms.md` §4.1: 4 rooms) and sends one S→C 0x07
    // per room of the player's adjacency array, in its order
    // (`path-placement.md` §11 "Recipients"); the room pass creates the
    // DS1's preset monster at its sub-tile (`population.md` §11.1). Each
    // joined room's 0x07 is followed by the add messages of its units
    // (`intents-events.md` §7.8 rule 2): the waypoint's 0x51 (type 2,
    // class 0, its position, mode 1, interact 0: no object data in this
    // game) after its room's. Each monster (the preset monster, GUID 2,
    // then Akara, GUID 1, class 148) sends §7.2 part A: 0xAC
    // (`monsters/init.md` §24: life 128, a one-byte stream of mode 1 and
    // no optional blocks) and 0xAA (no states); part B's mode message
    // needs the path provider, which this game does not run. The
    // client's own player is skipped.
    record(&mut fx, &mut frames, vec![]);
    let mut want: Vec<Vec<u8>> = [(8000, 8000), (8000, 8008), (8008, 8000), (8008, 8008)]
        .map(|(x, y)| map_reveal(x, y, ISLE))
        .to_vec();
    want.insert(1, assign_object(wp, 0, WP_AT, 1, 0));
    let monster_adds: [Vec<u8>; 4] = [
        vec![0xAC, 2, 0, 0, 0, 0, 0, 76, 156, 74, 156, 128, 14, 1],
        vec![0xAA, 1, 2, 0, 0, 0, 8, 0xFF],
        vec![0xAC, 1, 0, 0, 0, 148, 0, 86, 156, 86, 156, 128, 14, 1],
        vec![0xAA, 1, 1, 0, 0, 0, 8, 0xFF],
    ];
    for (i, m) in monster_adds.into_iter().enumerate() {
        want.insert(1 + i, m);
    }
    assert_eq!(frames[0].2, want);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 4);
    let monsters = fx.monsters();
    assert_eq!(monsters.len(), 1, "the DS1 preset monster");
    let monster = monsters[0];
    let mpos = fx.pending().pos[&monster];
    assert_eq!(mpos, (40_012, 40_010));
    assert_eq!(
        fx.pending().log,
        [format!("preset {} class 0 at 12,10", monster.0)]
    );
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    fx.sim().set_unit(monster, facts(mpos));

    // 4. Right skill at the monster (C→S 0x0C, `use.md` §1): accepted
    // (0), mana charged at start (the Multiple Shot vector: 3,328 of
    // 4,000 in 1/256 units), srvst 4 run, mode SC (10) set. The mode
    // start's animation schedule (`units.md` §4.1–§4.2) reads the
    // AnimData record of the composed name (`animdata.md` §5): 8 frames
    // at speed 256, event byte 2 on frame 4 → event 0 at f + 4 = 5 with
    // args (2, 0), the end (event 1) at f + 8 = 9.
    fx.stage_combat(monster);
    let cast = bytes(&RightSkill {
        x: mpos.0 as u16,
        y: mpos.1 as u16,
    });
    assert_eq!(cast, [0x0C, 0x4C, 0x9C, 0x4A, 0x9C]);
    record(&mut fx, &mut frames, vec![cast]);
    assert_eq!(fx.sim_ref().game.frame, 2);
    assert_eq!(frames[1].1.codes, [(0x0C, Some(ResultCode::Done))]);
    assert_eq!(frames[1].2, none);
    assert_eq!(fx.mode(player), 10);
    assert_eq!(fx.stat(player, 8), 4000 - 3328);
    // The start (srvst 53, `bodies-3.md` §4.1) ran with skill 1 at level
    // 10: the used entry's param 1 := frame + 10, at the dispatch frame
    // (1: messages run before the frame's tick, which makes it 2).
    let started = format!("param1 1 {}", fx.sim_ref().game.frame - 1 + 10);
    assert_eq!(fx.book.get().log, std::slice::from_ref(&started));
    assert_eq!(fx.player_timers(), [(0, 5), (1, 9)]);
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // Frames 3–5. On frame 5 the action frame `0x00580460` runs the used
    // skill's do function (`use.md` §5.2, §5.4): srvdo 53 (no body,
    // `unreferenced`, `use.md` OQ10: the seam), then the generic
    // `srvmissile` 0 through the real missile creation (`missiles.md`
    // §R2) at the player, aimed at the cast point.
    for _ in 3..=5 {
        record(&mut fx, &mut frames, vec![]);
    }
    assert_eq!(fx.sim_ref().game.frame, 5);
    assert_eq!(
        fx.pending().log[1..],
        [format!("action frame {} 2 0", player.0)]
    );
    assert_eq!(
        fx.book.get().log,
        [started, "srvdo 53 1 10 true false false".to_string()]
    );
    assert_eq!(fx.player_timers(), [(1, 9)]);
    let shot = fx.missiles();
    assert_eq!(shot.len(), 1);
    let shot = shot[0];
    assert_eq!(fx.pending().pos[&shot], PLAYER_AT);
    // The damage setup `0x0059F900` is the skills spec's: 10 points.
    fx.set_missile_damage(shot, 2560);

    // Frames 6–15: the missile flies one sub-tile a frame (the fixture's
    // path) and enters the monster's sub-tile on frame 15: hit
    // (`missiles.md` §R5, to-hit on the player's seed), damage 10 points
    // ≥ the monster's 5 → life 0, result 3 (`damage.md` §5.2 steps
    // 11–15: events 10, 9), the missile removed (collide-kill). The
    // reaction (§7.1) kills the monster (§7.2): its seam steps in order,
    // the death mode change with the player as target (mode DT 0, the
    // death start `0x005A6FF0`), the player's experience (`vitals.md`
    // §4.2: equal levels → 100).
    for _ in 6..=15 {
        record(&mut fx, &mut frames, vec![]);
    }
    assert_eq!(fx.sim_ref().game.frame, 15);
    assert_eq!(fx.mode(player), 1, "event 1 on frame 9 → neutral");
    assert!(fx.missiles().is_empty());
    assert_eq!(fx.stat(monster, 6), 0);
    assert_eq!(fx.mode(monster), 0);
    let (p, m) = (player.0, monster.0);
    assert_eq!(
        fx.pending().log[2..],
        [
            format!("event 0 Some({m})"),
            format!("event 11 Some({m})"),
            format!("event 2 Some({m})"),
            format!("event 10 Some({m})"),
            format!("event 9 Some({p})"),
            format!("reaction {p} {m} 0x3"),
            format!("kill PetCredit {m} {p}"),
            // `damage.md` §7.2 step 2: the experience distribution (its
            // level-up event, `vitals.md` §4.5), then the arena event.
            format!("level up {p}"),
            format!("kill AttackerBookkeeping {m} {p}"),
            format!("kill FaceAttacker {m} {p}"),
            format!("death start {m} target Some({p})"),
            format!("kill QuestKill {m} {p}"),
            format!("kill BarricadeDoors {m} {p}"),
        ]
    );
    assert_eq!(fx.stat(player, 13), 100);
    // The death animation: 4 frames → event 1 at 19. Tick 1's room
    // switch woke the monster created by that tick's room pass
    // (`intents-events.md` §7.8 rule 2.3, `0x00573780`: think at frame
    // 1 + 2; Idle → the next think at 203); the death clean-up's
    // `0x005738D0` cancelled that think (`units.md` §4.6 rule 1.2).
    assert_eq!(fx.timers(monster), [(1, 19)]);

    // 5a. The drop (`treasure.md` §3): the death start's gate passes
    // (no flag 0x20000, no wall / door at the monster's sub-tile); TC 1
    // picks gold on the monster's seed; the item is created on the game
    // seed (`generation.md` §3), placed at the start spot (x + 2, y + 3,
    // §7 step 2) and added to that room's units in mode 3, its gold
    // amount (§8) in stat 14.
    let drops = fx.drops();
    assert_eq!(drops.len(), 1);
    let (gold, spot) = drops[0];
    let room = fx.sim_ref().game.lists.unit(monster).unwrap().room();
    assert_eq!(
        spot,
        DropSpot {
            room,
            x: mpos.0 + 2,
            y: mpos.1 + 3
        }
    );
    assert_eq!(fx.sim_ref().game.lists.unit(gold).unwrap().room(), room);
    let rec = fx.sim_ref().events.action.sys.units.get(gold).unwrap();
    assert_eq!(
        (rec.ty, rec.class, rec.mode),
        (UnitType::Item, GOLD_REC as u32, 3)
    );
    let amount = fx.stat(gold, 14);
    assert!((1..=6).contains(&amount), "roll(5 · 1) + 1: {amount}");
    for f in &frames[2..] {
        assert_eq!(f.2, none);
    }
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // Level-up (`vitals.md` §4.3 → §3): 100 experience reaches level 2
    // (thresholds 0, 100, 1500): level 2, next threshold 1500, the
    // sorceress' 5 stat points and 1 skill point per level, mana refilled
    // to its maximum (4000); life is not refilled (life 0 in this
    // fixture). Then the level-up seams (`Pending::level_up_notify`,
    // `level_up_event`).
    assert_eq!(fx.stat(player, LEVEL), 2);
    assert_eq!(fx.stat(player, NEXTEXP), 1500);
    assert_eq!(fx.stat(player, STATPTS), 5);
    assert_eq!(fx.stat(player, NEWSKILLS), 1);
    assert_eq!(fx.stat(player, 8), 4000);

    // 7. A stat point (C→S 0x3A, `vitals.md` §2): stat 0 (strength),
    // count − 1 = 0 (Open question 4 reads byte +2 so): one `spend`:
    // stat points 5 → 4, strength 0 → 1, result 0. No message (none is
    // written for it).
    let point = bytes(&AddStatPoint {
        stat: STRENGTH as u8,
        repeat: 0,
    });
    assert_eq!(point, [0x3A, 0, 0]);
    record(&mut fx, &mut frames, vec![point]);
    let done = Some(ResultCode::Done);
    assert_eq!(frames[15].1.codes, [(0x3A, done)]);
    assert_eq!(frames[15].2, none);
    assert_eq!(fx.stat(player, STATPTS), 4);
    assert_eq!(fx.stat(player, STRENGTH), 1);

    // 5b. Pick-up of the kill's gold (C→S 0x16 cursor 0, `inventory-moves.md`
    // §7.1 → §8.1 → §10.1) through the item-move handler. The drop
    // created the pile in the game's one item store, so the inventory
    // model finds it: the staged distance 3 (< 5); not busy; can-pick
    // (§8.4: an inventory, not a quest item); the sound event on the
    // player (§8.1 step 3); gold → §10.1: limit = level 2 × 10000, g +
    // p ≤ limit, so take = p; no pile owner, no party share: stat 14 +=
    // take; the pile leaves its room and is freed. Result 0. Only the
    // pick-up sound message: inventory gold reaches the client through the vitals sync (§10.3,
    // no owner spec).
    let gold_guid = fx.guid(gold);
    let pick = bytes(&PickItem {
        type_: 4,
        id: gold_guid,
        cursor: 0,
    });
    record(&mut fx, &mut frames, vec![pick]);
    let done = Some(ResultCode::Done);
    assert_eq!(frames[16].1.codes, [(0x16, done)]);
    // The pick-up sound S→C 0x2C on the player is the one message
    // (recorded 1.14d, REC-1402..1404: items-pickup-ama packets MATCH).
    let mut sound = vec![0x2C, 0];
    sound.extend_from_slice(&fx.guid(player).to_le_bytes());
    sound.extend_from_slice(&[1, 0]);
    assert_eq!(frames[16].2, vec![sound]);
    assert!(fx.sim_ref().unhandled.is_empty());
    assert!(fx.sim_ref().game.lists.unit(gold).is_none(), "freed");
    assert!(!fx.items().contains(gold));
    let mut gold_now = PLAYER_GOLD + amount;
    assert_eq!(fx.stat(player, GOLD), gold_now);
    let pg = fx.guid(player);
    assert_eq!(
        fx.inv.with(|r| std::mem::take(&mut r.log)),
        [format!("pickup_sound {pg} {gold_guid}")]
    );
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // 8. NPC talk (C→S 0x13, `npc.md` §2) with Akara: distance 3 (the
    // unit spec's distance, staged), the talk starts: interact unit (1,
    // GUID), S→C 0x27, 0x29, 0x28 in that order (§2 start step 5). 0x27
    // bytes 6–39 are the text-list encoder `0x00661480`'s
    // (`server-messages.tsv` 0x27 `partial`, staged zeros).
    let ng = fx.guid(fx.npc);
    let talk = bytes(&InteractWithEntity { type_: 1, id: ng });
    record(&mut fx, &mut frames, vec![talk.clone()]);
    assert_eq!(frames[17].1.codes, [(0x13, done)]);
    let mut npc_info = vec![0x27, 1];
    npc_info.extend_from_slice(&ng.to_le_bytes());
    npc_info.extend_from_slice(&[0; 34]);
    let mut game_quests = vec![0x29];
    game_quests.extend_from_slice(&fx.sim_ref().world.quests.game.0);
    let mut quest_info = vec![0x28, 1];
    quest_info.extend_from_slice(&ng.to_le_bytes());
    quest_info.push(0);
    quest_info.extend_from_slice(&fx.sim_ref().world.rest.quests[&player].flags[0].0);
    assert_eq!(frames[17].2, [npc_info, game_quests, quest_info]);
    let rec = fx.sim_ref().events.action.sys.units.get(player).unwrap();
    assert_eq!(rec.interact.get(), Some((1, ng)));

    // 9. Chat (C→S 0x2F, §3): the heal hook (§5; nothing to heal). No
    // message.
    record(
        &mut fx,
        &mut frames,
        vec![bytes(&InitEntityChat { id: ng })],
    );
    // The client's own 0x2F (T 1, its 0x28 handler, `client/msg-ui.md`
    // §16 r4; held behind the unanswered dialog slot until this frame)
    // comes first, then the scenario's.
    assert_eq!(frames[18].1.codes, [(0x2F, done), (0x2F, done)]);
    assert_eq!(frames[18].2, none);

    // 10. Trade (C→S 0x38 action 1, `vendors.md` §4 → §3): the store is
    // generated on the NPC-control seed, its items made by the economy
    // wiring on the game seed (two steps per item, `rng.md` §5.3): 1–3
    // bucklers (Min 1, Max 3), then the permanent cap, each identified.
    // S→C 0x9C action 11: one per store item (§4 step 3).
    let seed_before = fx.sim_ref().events.action.sys.hooks.game_seed;
    let trade = bytes(&EntityAction {
        action: 1,
        npc: ng,
        item: 0,
    });
    record(&mut fx, &mut frames, vec![trade]);
    assert_eq!(frames[19].1.codes, [(0x38, done)]);
    let store = {
        let w = &fx.sim_ref().world;
        let rec = &w.state.vendors[w.state.vendor_index(class::AKARA).unwrap()];
        assert!(rec.has_traded && rec.store_generated);
        rec.store.clone()
    };
    assert!((2..=4).contains(&store.len()), "{store:?}");
    let mut seed = seed_before;
    for _ in 0..2 * store.len() {
        seed.step();
    }
    assert_eq!(fx.sim_ref().events.action.sys.hooks.game_seed, seed);
    let mut store_rows = Vec::new();
    for &item in &store {
        let guid = fx.guid(item);
        let ac = fx.stat(item, ARMORCLASS);
        let it = fx.items().get(item).unwrap().clone();
        assert_ne!(it.flags & flag::IDENTIFIED, 0);
        store_rows.push((guid, it.record, it.item_seed, ac));
    }
    assert_eq!(store_rows.last().unwrap().1, CAP, "permanent codes last");
    assert!(store_rows[..store.len() - 1].iter().all(|r| r.1 == BUC));
    // One 0x9C action 11 per store item, in store order (§4 step 3).
    let shown: Vec<(u8, u8, u32)> = frames[19]
        .2
        .iter()
        .map(|m| (m[0], m[1], u32::from_le_bytes(m[4..8].try_into().unwrap())))
        .collect();
    let want: Vec<(u8, u8, u32)> = store_rows.iter().map(|r| (0x9C, 11, r.0)).collect();
    assert_eq!(shown, want);

    // 11–16. Item moves (`inventory-moves.md` §7) on the game's inventory
    // model, after the player leaves Akara (C→S 0x30 in step 11's frame,
    // `npc.md` §3: the node freed, the interact unit reset, no message):
    // with the interaction active the player is busy (`0x00535060`) and a
    // pickup to the cursor does nothing (§8.2). A cap on the ground beside
    // the player, made
    // by the economy wiring on the game seed into the game's one item
    // store, identified, at (x + 1, y + 1).
    let cap = fx.ground_cap();
    let cg = fx.guid(cap);
    // The deferred item messages of §6 and §11 (the item bit stream is
    // the unwritten serialization spec's, `inventory.md` OQ1: empty;
    // category 0: no `component`), then 0x47 and 0x48, in the frame's
    // tick (§6.1).
    let x9c = |action: u8, g: u32| {
        let mut b = vec![0x9C, action, 8, 0];
        b.extend_from_slice(&g.to_le_bytes());
        b
    };
    let x9d = |action: u8, g: u32| {
        let mut b = vec![0x9D, action, 13, 0];
        b.extend_from_slice(&g.to_le_bytes());
        b.push(0);
        b.extend_from_slice(&pg.to_le_bytes());
        b
    };
    let relators = || {
        let mut r = vec![0x47, 0, 0];
        r.extend_from_slice(&pg.to_le_bytes());
        r.extend_from_slice(&[0; 4]);
        let mut r2 = r.clone();
        r2[0] = 0x48;
        [r, r2]
    };
    let pass = |m: Vec<Vec<u8>>| {
        let mut v = m;
        v.extend(relators());
        v
    };

    // 11. The chat closed (C→S 0x30), then the pick-up to the cursor
    // (C→S 0x16 cursor 1, §7.1 → §8.2): the staged distance 3 (< 5), the
    // cap leaves the room for the cursor (mode 4) → 0x9C action 1.
    let pick_cap = bytes(&PickItem {
        type_: 4,
        id: cg,
        cursor: 1,
    });
    let close = bytes(&TerminateEntityChat { id: ng });
    record(&mut fx, &mut frames, vec![close, pick_cap.clone()]);
    assert_eq!(frames[20].1.codes, [(0x30, done), (0x16, done)]);
    // The pick-up also sends the sound S→C 0x2C on the player (recorded
    // 1.14d, REC-1402..1404: items-pickup-ama packets MATCH).
    let mut sound = vec![0x2C, 0];
    sound.extend_from_slice(&pg.to_le_bytes());
    sound.extend_from_slice(&[1, 0]);
    let mut picked = pass(vec![x9c(0x01, cg)]);
    picked.push(sound);
    assert_eq!(streams(&fx, &frames[20].2), picked);
    assert_eq!(fx.mode(cap), 4);
    assert_eq!(fx.sim_ref().game.lists.unit(cap).unwrap().room(), None);

    // 12. Inventory placement (C→S 0x18, §7.3 → §2.4) at (8, 0) of page
    // 0 of the sorceress' 10 × 4 grid (record 1), free beside the
    // stored buckler, cap and cube: mode 0 → 0x9C action 4.
    let (px, py) = (8u32, 0u32);
    assert!(fx.page0_free(px, py, 2, 2));
    let insert = bytes(&InsertItemInBuffer {
        item: cg,
        x: px,
        y: py,
        page: 0,
    });
    record(&mut fx, &mut frames, vec![insert.clone()]);
    assert_eq!(frames[21].1.codes, [(0x18, done)]);
    assert_eq!(streams(&fx, &frames[21].2), pass(vec![x9c(0x04, cg)]));
    assert_eq!(fx.mode(cap), 0);
    assert_eq!(fx.items().get(cap).unwrap().inv_page, 0);

    // 13. Back to the cursor (C→S 0x19, §7.4) → 0x9D action 5 (owner the
    // player).
    let lift = bytes(&RemoveItemFromBuffer { item: cg });
    record(&mut fx, &mut frames, vec![lift]);
    assert_eq!(frames[22].1.codes, [(0x19, done)]);
    assert_eq!(streams(&fx, &frames[22].2), pass(vec![x9d(0x05, cg)]));
    assert_eq!(fx.mode(cap), 4);

    // 14. Equip on the head (C→S 0x1A location 1, §7.5 → §4.6): mode 1
    // → 0x9D action 6.
    let equip = bytes(&EquipItem {
        item: cg,
        bodyloc: 1,
    });
    record(&mut fx, &mut frames, vec![equip]);
    assert_eq!(frames[23].1.codes, [(0x1A, done)]);
    assert_eq!(streams(&fx, &frames[23].2), pass(vec![x9d(0x06, cg)]));
    assert_eq!(fx.mode(cap), 1);

    // 15. Unequip (C→S 0x1C location 1, §7.7): to the cursor → 0x9D
    // action 8.
    let unequip = bytes(&RemoveBodyItem { bodyloc: 1 });
    record(&mut fx, &mut frames, vec![unequip]);
    assert_eq!(frames[24].1.codes, [(0x1C, done)]);
    assert_eq!(streams(&fx, &frames[24].2), pass(vec![x9d(0x08, cg)]));
    assert_eq!(fx.mode(cap), 4);

    // 16. Drop (C→S 0x17, §7.2 → §9.1): no room at (x + 2, y + 3) (the
    // staged answer), so the search starts at the player; the staged
    // free-spot search answers that spot: the cap on the ground (mode 3,
    // in the player's room, at the player's position), the ITEMDROPPED
    // hook. No owner refresh, so no update pass; the ground message
    // (§6.3) is not built on real units (`wire-inventory-sim.md` WV1).
    let drop_msg = bytes(&DropItem { item: cg });
    record(&mut fx, &mut frames, vec![drop_msg]);
    assert_eq!(frames[25].1.codes, [(0x17, done)]);
    assert_eq!(frames[25].2, none);
    assert_eq!(fx.mode(cap), 3);
    let room = fx.sim_ref().game.lists.unit(player).unwrap().room();
    assert_eq!(fx.sim_ref().game.lists.unit(cap).unwrap().room(), room);
    assert_eq!(
        fx.inv.with(|r| std::mem::take(&mut r.log)),
        [
            format!("quest_item_picked {cg}"),
            format!("pickup_sound {pg} {cg}"),
            format!("quest_item_dropped {cg}"),
        ]
    );

    // 17–18. The cap again: picked to the cursor (0x16 → 0x9C action 1)
    // and placed by 0x18 at (8, 0) (→ 0x9C action 4): an item of the
    // inventory model, as the vendor sees it next.
    record(&mut fx, &mut frames, vec![pick_cap]);
    assert_eq!(frames[26].1.codes, [(0x16, done)]);
    // The pick-up sound S→C 0x2C on the player follows (REC-1402..1404).
    let mut sound = vec![0x2C, 0];
    sound.extend_from_slice(&pg.to_le_bytes());
    sound.extend_from_slice(&[1, 0]);
    let mut picked = pass(vec![x9c(0x01, cg)]);
    picked.push(sound);
    assert_eq!(streams(&fx, &frames[26].2), picked);
    record(&mut fx, &mut frames, vec![insert]);
    assert_eq!(frames[27].1.codes, [(0x18, done)]);
    assert_eq!(streams(&fx, &frames[27].2), pass(vec![x9c(0x04, cg)]));
    assert_eq!(fx.mode(cap), 0);
    assert!(fx.inventory().contains(&cap));
    assert!(fx.inv.with(|r| r.log.len()) == 2);
    fx.inv.with(|r| r.log.clear());

    // 19. Talk to Akara again (C→S 0x13: the interact unit, 0x27, 0x29,
    // 0x28 as step 8), then sell (C→S 0x33) the cap placed by 0x18
    // (`vendors.md` §7.2; rule 2: Akara is the interact unit): the
    // player's per its inventory (rule 3, the model), mode 0 (rule
    // 4), one of Akara's permanent codes, so no copy (rule 8); rule 9
    // removes it (stored: `0x0055DF10`: unlinked from the inventory,
    // freed); rule 10 receives the price (§9.1, §9.2 by hand: B =
    // 100·AC/5, buy mult 512 → B·512/1024): 0x2A kind 3, code 1, the
    // cap's GUID, the new gold.
    let sell = |item| {
        bytes(&SellItem {
            npc: ng,
            item,
            item_mode: 0,
            client_price: 0,
        })
    };
    let sold = (100 * fx.stat(cap, ARMORCLASS) / 5) * 512 / 1024;
    assert!(sold > 0);
    record(&mut fx, &mut frames, vec![talk.clone(), sell(cg)]);
    assert_eq!(frames[28].1.codes, [(0x13, done), (0x33, done)]);
    gold_now += sold;
    // The talk's 0x27, 0x29, 0x28 (as step 8), then the sale's 0x9D
    // action 5 (the stored cap, `vendors.md` §7.2 rule 9) and its 0x2A.
    let talk_msgs = frames[17].2.clone();
    let got = &frames[28].2;
    assert_eq!(got.len(), talk_msgs.len() + 2, "{got:02X?}");
    assert_eq!(got[..talk_msgs.len()], talk_msgs[..]);
    let n9d = &got[talk_msgs.len()];
    assert_eq!((n9d[0], n9d[1]), (0x9D, 0x05));
    assert_eq!(n9d[4..8], cg.to_le_bytes());
    assert_eq!(got[talk_msgs.len() + 1], tx(3, 1, cg, gold_now));
    assert_eq!(fx.stat(player, GOLD), gold_now);
    assert!(!fx.inventory().contains(&cap));
    assert!(fx.sim_ref().game.lists.unit(cap).is_none(), "freed");
    assert!(fx.page0_free(px, py, 2, 2), "its cells cleared");

    // 20. Buy (C→S 0x32) the store's cap with enough gold: rules 1–8
    // pass (in the NPC inventory, the price, gold, no cursor item in the
    // player's inventory); the purchase loop (§7.1 rule 9) copies the
    // store cap (§7.3, on the inventory model), pays (§9.1, §9.2 by
    // hand: 100·AC/5, sell mult 1024), and, no weapon in use and the
    // head empty, the equip try of §7.1.1 puts the copy on the head
    // (`inventory.md` §4.9): 0x2A code 0, kind 4, the copy's GUID; the
    // copy's 0x9D action 6 in the tick's update pass (`vendors.md` OQ3's
    // expectation). The permanent cap stays in the store (rule 12).
    let price = 100 * fx.stat(*store.last().unwrap(), ARMORCLASS) / 5;
    let store_cap = fx.guid(*store.last().unwrap());
    let buy = bytes(&BuyItem {
        npc: ng,
        item: store_cap,
        transaction: 0,
        client_price: 0,
    });
    record(&mut fx, &mut frames, vec![buy]);
    // The client's own 0x2F (its 0x28 handler of step 19, as step 9)
    // comes first.
    assert_eq!(frames[29].1.codes, [(0x2F, done), (0x32, done)]);
    let bought = *fx.inventory().last().unwrap();
    assert!(!store.contains(&bought), "a new unit");
    let bg = fx.guid(bought);
    gold_now -= price;
    let mut want = vec![tx(4, 0, bg, gold_now)];
    want.extend(pass(vec![x9d(0x06, bg)]));
    assert_eq!(streams(&fx, &frames[29].2), want);
    assert_eq!(fx.stat(player, GOLD), gold_now);
    assert_eq!(fx.inventory(), [fx.buckler, fx.cap, fx.cube, bought]);
    assert_eq!(fx.mode(bought), 1, "worn");

    // 21. Sell the player's stored buckler (re-sellable, not a
    // permanent code): §7.2 rule 8 copies it into the store (restored,
    // §7.3); rule 9 removes it (stored: unlinked, freed); rule 10: 0x2A
    // kind 3, code 1, its GUID, the new gold (§9.2 by hand: 80·AC/6,
    // buy mult 512; the restored copy's price is the same).
    let buckler = fx.guid(fx.buckler);
    let buc_sold = (80 * fx.stat(fx.buckler, ARMORCLASS) / 6) * 512 / 1024;
    record(&mut fx, &mut frames, vec![sell(buckler)]);
    assert_eq!(frames[30].1.codes, [(0x33, done)]);
    gold_now += buc_sold;
    assert_stored_sale(&frames[30].2, buckler, tx(3, 1, buckler, gold_now));
    assert_eq!(fx.stat(player, GOLD), gold_now);
    assert!(!fx.inventory().contains(&fx.buckler));
    assert!(fx.sim_ref().game.lists.unit(fx.buckler).is_none(), "freed");

    // 22. Sell the player's stored cap (stored at creation, §2.4): as
    // step 19: 0x2A kind 3, code 1, its GUID, the new gold.
    let scap = fx.guid(fx.cap);
    let sold = (100 * fx.stat(fx.cap, ARMORCLASS) / 5) * 512 / 1024;
    record(&mut fx, &mut frames, vec![sell(scap)]);
    assert_eq!(frames[31].1.codes, [(0x33, done)]);
    gold_now += sold;
    assert_stored_sale(&frames[31].2, scap, tx(3, 1, scap, gold_now));
    assert_eq!(fx.stat(player, GOLD), gold_now);
    assert_eq!(fx.inventory(), [fx.cube, bought]);
    let copies = fx.sim_ref().world.rest.log.iter();
    let copies: Vec<&String> = copies.filter(|l| l.starts_with("copy")).collect();
    assert!(copies.is_empty(), "both copies on the inventory model");
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // TODO(after the quest-host merge): quest messages 0x31, 0x40, 0x58
    // on `WiredWorld` (`QuestCall`) are being added in parallel; until
    // then they stay stubs and this run sends none. The step goes here.

    // 23. The player leaves Akara (C→S 0x30, as step 11), then the ring
    // on the ground beside the player picked to the cursor (C→S 0x16
    // cursor 1, §8.2) → 0x9C action 1.
    let (cube, ring) = (fx.cube, fx.ring);
    let rg = fx.guid(ring);
    record(
        &mut fx,
        &mut frames,
        vec![
            bytes(&TerminateEntityChat { id: ng }),
            bytes(&PickItem {
                type_: 4,
                id: rg,
                cursor: 1,
            }),
        ],
    );
    assert_eq!(frames[32].1.codes, [(0x30, done), (0x16, done)]);
    // The buckler sold in step 21 joined the store (`vendors.md` §7.2
    // rule 8); its 0x9C action 11 leaves with the next NPC call, this one.
    let got = streams(&fx, &frames[32].2);
    let copy = {
        let w = &fx.sim_ref().world;
        *w.state.vendors[w.state.vendor_index(class::AKARA).unwrap()]
            .store
            .last()
            .unwrap()
    };
    assert_eq!(got[0][..2], [0x9C, 11]);
    assert_eq!(got[0][4..8], fx.guid(copy).to_le_bytes());
    // The pick-up sound S→C 0x2C on the player follows (REC-1402..1404).
    let mut sound = vec![0x2C, 0];
    sound.extend_from_slice(&pg.to_le_bytes());
    sound.extend_from_slice(&[1, 0]);
    let mut picked = pass(vec![x9c(0x01, rg)]);
    picked.push(sound);
    assert_eq!(got[1..], picked[..]);
    assert_eq!(fx.mode(ring), 4);
    // §8.2: the quest hook ITEMPICKEDUP, then the pickup sound.
    assert_eq!(
        fx.inv.with(|r| std::mem::take(&mut r.log)),
        [
            format!("quest_item_picked {rg}"),
            format!("pickup_sound {pg} {rg}"),
        ]
    );

    // 24. Cube (C→S 0x2A, `cube.md` §2): the cursor ring into the
    // player's cube: the checks of `inventory.md` §5.1 on the model pass
    // (the ring is the cursor item; the cube is stored in the player's
    // inventory), the targeting reset (§5.3), page 3, the placement
    // (§2.4, free position and "send": the cube's 3 × 4 grid, record 9);
    // result 0; the placement's 0x9C action 4 in the tick's update pass.
    let mut put = vec![0x2A];
    put.extend_from_slice(&rg.to_le_bytes());
    put.extend_from_slice(&fx.guid(cube).to_le_bytes());
    assert_eq!(
        put,
        bytes(&ItemToCube {
            item: rg,
            cube: fx.guid(cube)
        })
    );
    record(&mut fx, &mut frames, vec![put]);
    assert_eq!(frames[33].1.codes, [(0x2A, done)]);
    assert_eq!(streams(&fx, &frames[33].2), pass(vec![x9c(0x04, rg)]));
    assert_eq!(fx.items().get(ring).unwrap().inv_page, CUBE_PAGE);
    assert_eq!(fx.mode(ring), 0);
    assert_eq!(fx.inventory(), [cube, bought, ring]);

    // 25. Transmute (C→S 0x4F button 0x18, `cube.md` §1, §3, §8) with
    // the cube open. The cube's opening (item use, `cube.md` §10) has no
    // spec: the interaction (type 4, the cube's GUID) is staged on the
    // player's interact info (the unit record). The ring matches the recipe: the amulet is
    // created; the ring gets 0x9D action 5 now (§8 step 1, `inventory-moves.md`
    // §6.4: owner the player) and is removed from the inventory and
    // freed; sound 4; the amulet is placed on page 3 (§2.4, "send"),
    // identified: its 0x9C action 4 in the tick's update pass, then the
    // player's update with the sound (0x2C).
    let cg2 = fx.guid(cube);
    stage_interact(&mut fx, player, (4, cg2));
    let click = bytes(&ClickButton {
        button: 0x18,
        p1: 0,
        p2: 0,
    });
    assert_eq!(click, [0x4F, 0x18, 0, 0, 0, 0, 0]);
    record(&mut fx, &mut frames, vec![click]);
    assert_eq!(frames[34].1.codes, [(0x4F, done)]);
    let inv = fx.inventory();
    assert_eq!(inv.len(), 3, "{inv:?}");
    let amulet = inv[2];
    let ag = fx.guid(amulet);
    let mut want = vec![x9d(0x05, rg)];
    want.extend(pass(vec![x9c(0x04, ag)]));
    // Sound 4 reaches the wire as S→C 0x2C in the player's unit update,
    // to the acting player's client (`cube.md` §8 "Exact" item 3, Open
    // question 2; `audio/triggers-2.md` §14).
    let mut snd = vec![0x2C, 0];
    snd.extend_from_slice(&fx.guid(player).to_le_bytes());
    snd.extend_from_slice(&4u16.to_le_bytes());
    want.push(snd);
    assert_eq!(streams(&fx, &frames[34].2), want);
    assert!(!fx.items().contains(ring));
    assert!(fx.sim_ref().game.lists.unit(ring).is_none(), "freed");
    let it = fx.items().get(amulet).unwrap().clone();
    assert_eq!(
        (it.record, it.quality, it.inv_page),
        (AMULET, q::NORMAL, CUBE_PAGE)
    );
    assert_eq!(fx.mode(amulet), 0);
    assert_ne!(it.flags & flag::IDENTIFIED, 0);
    assert_eq!(fx.cube_parts().staged.sounds, [(player, 4)]);
    assert!(fx.cube_rest.0.lock().unwrap().is_empty());
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    assert!(fx.sim_ref().unhandled.is_empty());

    // 6. Waypoint travel (C→S 0x49, `waypoints.md` §6–§7): accepted,
    // the interaction closed (rule 2), the destination bit tested (rule
    // 3), tile code 0 (rule 4), the warp called (rule 5), the spawn
    // search streamed the destination's room (rule 7's `0x00619E50`: 5
    // active rooms), the arrival node prepended (rule 8). STOP: the
    // warp's same-act placement `0x00554EA0` (`path-placement.md` §11)
    // is the path provider's, off in this run (WP1), so `Pending::warp`
    // logs it, the player stays in the ISLE room and rule 7's room test
    // sends no S→C 0x0D (provider on: `e2e_walk.rs`).
    stage_interact(&mut fx, player, (2, wp));
    let travel = bytes(&TakeOrCloseWp {
        wp,
        level: GATE as u16,
    });
    let mut want = vec![0x49];
    want.extend_from_slice(&wp.to_le_bytes());
    want.extend_from_slice(&[GATE as u8, 0, 0, 0]);
    assert_eq!(travel, want);
    record(&mut fx, &mut frames, vec![travel]);
    assert_eq!(frames[35].1.codes, [(0x49, done)]);
    assert_eq!(frames[35].2, none);
    let rec = fx.sim_ref().events.action.sys.units.get(player).unwrap();
    assert_eq!(rec.interact.get(), None);
    let log = fx.pending().log.clone();
    assert_eq!(log.last(), Some(&format!("warp {} {GATE} 0", player.0)));
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 5);
    let arrivals = &fx.sim_ref().events.action.sys.hooks.arrivals.0;
    assert_eq!(arrivals.len(), 1);
    assert_eq!((arrivals[0].x, arrivals[0].y), PLAYER_AT);
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    assert_eq!(fx.inv.with(|r| r.log.clone()), Vec::<String>::new());

    // The client: 37 frames, 36 server ticks. The S→C messages it got:
    // 0x27, 0x29, 0x28 twice (frames 17, 28), 0x2A four times (frames
    // 28–31), handled
    // (`client/msg-ui.md` §5, §12, §16, §18), and Akara's harness add
    // (0xAC, `akara_add`); 0x9C seven times (frames 20, 21, 26,
    // 27, 32, 33, 34), 0x9D five times (22, 23, 24, 29, 34), 0x47 and
    // 0x48 eleven times each are applied (`client/msg-stats-items.md`).
    // The 0x9C made the three items it names; 0x9D (the bought cap's too) needs the local player, which
    // this staged game never announces (no 0x59 / 0x0B), so it changes
    // nothing (§2 rule 3); the join's four 0x07 (frame 2) are rejected,
    // fatal 0x58A (no client act: this staged game sends no 0x03); the
    // join's 0x51 made the waypoint (`intents-events.md` §7.8 rule 2);
    // nothing discarded.
    let w = fx.bridge.world();
    let client = (w.frames, w.server_ticks, w.units.len());
    // + the store items the trade open and the sold buckler showed
    // (each 0x9C action 11 makes a unit; the seed sets how many).
    let shown: Vec<&Vec<u8>> = frames
        .iter()
        .flat_map(|f| f.2.iter())
        .filter(|m| m[0] == 0x9C && m[1] == 11)
        .collect();
    assert_eq!(client, (37, 36, 5 + shown.len()));
    assert_eq!(w.local_player, None);
    let object = d2_client::bridge::world::UnitKey::new(d2_client::bridge::world::OBJECT, wp);
    assert!(w.units.contains_key(&object));
    let akara = d2_client::bridge::world::UnitKey::new(1, fx.guid(fx.npc));
    assert!(w.units.contains_key(&akara));
    for (k, u) in w
        .units
        .iter()
        .filter(|(k, _)| **k != object && **k != akara)
    {
        assert_eq!(k.unit_type, d2_client::bridge::world::ITEM);
        let d2_client::bridge::world::KindData::Item(d) = &u.kind else {
            panic!("item data");
        };
        assert_eq!(d.last.as_ref().map(|r| r.id), Some(0x9C));
    }
    let log = fx.bridge.log();
    assert!(log.unowned.is_empty(), "{:?}", log.unowned);
    // 35 before (the buy's 0x9C, 0x47, 0x48 among them) + 0x27, 0x28,
    // 0x29 ×2 + 0x2A ×4 + Akara's 0xAC + the three stored sales' 0x9D
    // action 5 (`vendors.md` §7.2 rule 9), + the join's monster adds
    // (`intents-events.md` §7.2: 0xAC ×2, 0xAA ×2), + the transmute's
    // sound 0x2C (step 25, `cube.md` §8 "Exact" item 3).
    // + the four pick-up sounds 0x2C (gold, cap twice, ring; REC-1402..1404).
    // + the 0x9C action 11 of the store items (trade open, sold copy).
    assert_eq!(log.handled, 58 + shown.len() as u64);
    let rejected: Vec<(u8, String)> = log
        .rejected
        .iter()
        .map(|r| (r.id, r.error.to_string()))
        .collect();
    assert_eq!(rejected, vec![(0x07, "fatal assert 0x58A".to_owned()); 4]);
    assert!(log.discarded.is_empty());
    assert!(log.dropped.is_empty() && log.queued == 0);

    let player_mana = fx.stat(player, 8);
    let player_exp = fx.stat(player, 13);
    let drops = fx
        .drops()
        .into_iter()
        .map(|(u, spot)| {
            let r = fx.sim_ref().events.action.sys.units.get(u).unwrap();
            (fx.guid(u), r.seed, spot.x, spot.y, r.mode)
        })
        .collect::<Vec<_>>();
    let gold = fx.drops().iter().map(|&(u, _)| fx.stat(u, 14)).collect();
    let skill_log = fx.book.get().log.clone();
    let player_stats = [LEVEL, STATPTS, STRENGTH, GOLD]
        .iter()
        .map(|&st| fx.stat(player, st))
        .collect();
    let cube_log = fx.cube_rest.0.lock().unwrap().clone();
    let inv_log = fx.inv.with(|r| r.log.clone());
    let inventory = fx.inventory();
    let s = fx.sim_ref();
    let x = &s.events.action.sys;
    Transcript {
        game_frame: s.game.frame,
        game_seed: x.hooks.game_seed,
        monsters: fx
            .monsters()
            .iter()
            .map(|&m| {
                (
                    fx.guid(m),
                    x.units.get(m).unwrap().seed,
                    x.hooks.x.pos[&m],
                    x.units.get(m).unwrap().mode,
                )
            })
            .collect(),
        active_rooms: s.game.lists.active_rooms(0),
        player_mode: fx.mode(player),
        player_mana,
        player_exp,
        drops,
        gold,
        pending_log: x.hooks.x.log.clone(),
        skill_log,
        player_stats,
        store: store_rows,
        npc_seed: s.world.npc.seed,
        rest_log: s.world.rest.log.clone(),
        cube_log,
        inv_log,
        inventory,
        unhandled: s.unhandled.clone(),
        client,
        errors: fx.errors(),
        frames,
    }
}

// Covers: specs/client/bridge.md §3 r1, §3 r2, §3 r3
#[test]
fn single_player_end_to_end() {
    let t = run();
    assert_eq!(t.game_frame, 36);
    assert_eq!(t.frames.len(), 36);
    // The cube, the bought cap and the transmuted amulet: one inventory
    // for moves, vendor and cube.
    assert_eq!(t.inventory.len(), 3);
    assert_eq!(t.player_exp, 100);
    assert_eq!(t.drops.len(), 1);
    // Level 2, 4 stat points left, strength 1, gold after the pickup and
    // the buy and the three sales.
    assert_eq!(t.player_stats[..3], [2, 4, 1]);
    assert!(t.player_stats[3] > PLAYER_GOLD);
}

/// Same seeds → the same run: every C→S byte, result code, S→C chunk,
/// seed, unit, room and log, twice.
#[test]
fn same_seed_same_run() {
    assert_eq!(run(), run());
}

/// The comparison sees the seed: another game seed gives other unit
/// seeds (`rng.md` §5.3), so the transcripts differ.
#[test]
fn other_seed_other_run() {
    let (a, b) = (run(), run_with(GAME_SEED + 1));
    assert_ne!(a.game_seed, b.game_seed);
    assert_ne!(a.monsters, b.monsters);
    assert_ne!(a.npc_seed, b.npc_seed);
    assert_ne!(a.store, b.store);
    // Up to the trade the wire is seed-independent; the store (its
    // size, so the GUIDs after it, and the ACs, so the prices) is not.
    assert_eq!(a.frames[..19], b.frames[..19]);
    let codes = |t: &Transcript| {
        t.frames
            .iter()
            .map(|f| f.1.codes.clone())
            .collect::<Vec<_>>()
    };
    assert_eq!(codes(&a), codes(&b));
}
