// Spec: specs/client/bridge.md §3; specs/sim/intents-events.md §1–§3; specs/sim/tick.md §3, §4; specs/drlg/levels.md §5; specs/drlg/preset.md §3, §8, §9; specs/drlg/rooms.md §4.1; specs/monsters/population.md §11.1; specs/skills/use.md §1, §4, §5.2, §5.4; specs/formats/animdata.md §5; specs/sim/units.md §4.1, §4.2, §4.6; specs/missiles/missiles.md §R2–§R6; specs/combat/damage.md §5.2, §7.1, §7.2; specs/combat/vitals.md §2, §3, §4.2, §4.3; specs/items/treasure.md §3, §7, §8; specs/world/npc.md §2, §3, §9; specs/world/vendors.md §3, §4, §7, §9; specs/world/quests.md §1.5; specs/world/cube.md §1, §2, §3, §8; specs/world/waypoints.md §6, §7; specs/items/inventory.md §6, §7, §11 (end to end)
//! End-to-end single player: the bridge (`d2_client::bridge`) on its
//! local link (`bridge::local::LocalLink`) over the in-process
//! `d2-server` host, whose game is `SimGame` on the fully wired `d2-sim`
//! (`wiring::worldgen::WorldSim` around `wiring::action::ActionSim`),
//! from synthetic tables and synthetic DS1 files (no game files).
//!
//! The run, step by step (`docs/handoff/e2e-single-player.md` lists
//! where each step stops and why):
//!
//! 1. game creation on a fixed seed: act 0's DRLG through the level-type
//!    dispatcher (`WorldTypes`: the Act I outdoor placer, preset inits),
//!    the regions on the game seed;
//! 2. a preset level generated by the real generator (`drlg::preset`),
//!    one of its rooms streamed for the player;
//! 3. the player joins; the first host tick runs the client room change
//!    (`rooms.md` §4.1: rooms near the player become active) and the room
//!    pass (`population.md` §11.1: the DS1's preset monster is created);
//! 4. a right-skill cast at the monster (C→S 0x0C): the handler runs, the
//!    mode starts and its animation schedule (`units.md` §4.1–§4.2)
//!    reads the AnimData record of the unit's composed COF name
//!    (`animdata.md` §5); the action frame (event 0) runs the do
//!    function and the real missile creation; the missile flies, hits,
//!    kills (`damage.md` §5.2, §7.1, §7.2): the death mode with its
//!    target and the player's experience (`vitals.md` §4);
//! 5. (a) the death start drops gold through the treasure walk as a real
//!    item unit in the monster's room (`treasure.md` §3, §7, §8); the
//!    kill's experience levels the player up (`vitals.md` §4.3 → §3);
//!    then (step 7) a stat point is spent (C→S 0x3A, `vitals.md` §2);
//!    (step 5b) pick-up of that gold (C→S 0x16) runs the item-move
//!    handler (`inventory.md` §7.1) and **stops** at the item lookup:
//!    the drop's item record is in the death drop's own item store, not
//!    the host's (`docs/handoff/host-merge.md` W-5): result 1;
//! 8. (steps 8–13) Akara on the server's `WiredWorld` (the same units): talk
//!    (C→S 0x13: S→C 0x27, 0x29, 0x28, `npc.md` §2), chat (0x2F), trade
//!    (0x38: the store generated, `vendors.md` §3, §4), buy (0x32)
//!    **stops at the item copy** `0x0055A2A0` (§7.1 rule 9.2: S→C 0x2A
//!    code 9), sell of a buckler **stops at the same copy** (§7.2 rule
//!    8), sell of the cap runs (§7.2 rules 8–10: S→C 0x2A kind 3);
//!    quests (0x31, 0x40, 0x58) are a marked step for after the
//!    quest-host merge;
//! 9. (steps 14–15) the cube (C→S 0x2A, 0x4F, `cube.md` §1, §2, §3,
//!    §8) on the same host, units and item store;
//! 10. (step 6) a waypoint travel (C→S 0x49) runs through the
//!     handler, the warp seam and the destination's spawn search, **then
//!     stops**: the same-act placement belongs to the unwritten path
//!     spec, so the player is not moved and `waypoints.md` §7 rule 7
//!     sends no S→C 0x0D;
//! 11. (steps 16–21) item moves on the host's inventories
//!     (`inventory.md` §7, `d2_sim::wiring::inventory` under
//!     `handlers::items::moves`): a cap in the host's item store is
//!     picked to the cursor (0x16), placed in the grid (0x18), lifted
//!     (0x19), equipped (0x1A), unequipped (0x1C) and dropped (0x17);
//!     each frame's tick sends the deferred item messages (§6, §11:
//!     0x9C / 0x9D with an empty item bit stream, OQ1) and 0x47, 0x48.
//!
//! The S→C messages the specs lay out (0x27, 0x29, 0x28, 0x2A, 0x9C,
//! 0x9D, 0x47, 0x48) are asserted byte for byte; every other frame's
//! received bytes are asserted empty: the wiring sends no S→C message on
//! the other paths (no written spec ties a mode, missile, death, stat or
//! cube message to them yet). Where a step needs behaviour no written spec
//! owns (the COF-name composer, the animation rate, the missile's path
//! and damage setup, the death start's body, the free-spot search, the
//! inventories other than the move handlers' (the vendor's and the
//! cube's staged lists), the item copy, the cube's opening, the
//! item-move seams of `InvFx`), the fixture answers
//! the seam and says so at the answer (`docs/handoff/e2e-next.md`).
//!
//! The whole run is repeated: same seed → byte-identical transcript.

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, MutexGuard};

use d2_client::bridge::dispatch::Dispatch;
use d2_client::bridge::link::{LinkError, Pumped, SendQueue, Sent, ServerLink};
use d2_client::bridge::local::{LocalLink, PendingSession};
use d2_client::bridge::{Bridge, FrameReport};
use d2_data::bin::BinTable;
use d2_data::fixup::records::stat_ops;
use d2_data::tables::{Difficultylevels, Itemstatcost, Levels, Monlvl, Objects, Record};
use d2_proto::client::{
    AddStatPoint, BuyItem, ClickButton, DropItem, EntityAction, EquipItem, InitEntityChat,
    InsertItemInBuffer, InteractWithEntity, ItemToCube, PickItem, RemoveBodyItem,
    RemoveItemFromBuffer, RightSkill, SellItem, TakeOrCloseWp,
};
use d2_server::adapters::handlers::items::moves::InvParts;
use d2_server::adapters::handlers::items::{CubeParts, Inventory, ItemPending};
use d2_server::adapters::handlers::skills::wired::WiredSkills;
use d2_server::adapters::handlers::skills::LearnRest;
use d2_server::adapters::handlers::world::{ActionWorld, Outbox, WiredWorld};
use d2_server::adapters::{PlayerData, PlayerFields, ProtoSizes, SimGame, UnitFacts};
use d2_server::dispatch::Outcome;
use d2_server::host::{Handled, Host};
use d2_server::seams::{Clock, PlayerGate, Pos, ResultCode};
use d2_sim::bench_fixtures::combat::{
    anim_data, arrow, combat_tables, drop_tables, monster_class, skills, vitals, MONSTER_DT, MULTI,
    PLAYER_SC,
};
use d2_sim::drlg::collision::bits;
use d2_sim::drlg::maze::{Maze, MazeData, MazeRow, Specials};
use d2_sim::drlg::outdoor::{OutdoorData, PresetDef as OutdoorPreset, SubDefs, SubFileMap};
use d2_sim::drlg::preset::{
    Ds1Input, Ds1ObjectInput, Ds1Source, PresetData, PresetDef, PresetTables,
};
use d2_sim::drlg::tiles::{cell, FIXED_LIBRARY};
use d2_sim::drlg::{Drlg, DrlgData, DrlgRoomId, Dungeon, LevelDef, TileInfo, TileSource};
use d2_sim::game::Game;
use d2_sim::items::inventory::tables::{GridRec, InvItemRec, InvTypeRec};
use d2_sim::items::inventory::{InvItem, InvTables, UnitKind as InvKind};
use d2_sim::items::moves::Owner;
use d2_sim::items::tables::ItemRec;
use d2_sim::items::{flag, q, ty, ItemRequest, ItemTables};
use d2_sim::missiles::{param_flags, unit_flag, MissileParams};
use d2_sim::monsters::init::{GameInfo, MonstatsExtra};
use d2_sim::monsters::population::PopTables;
use d2_sim::rng::Seed;
use d2_sim::skills::use_::{MissileAim, ModeTarget, ServerMsg, UseState};
use d2_sim::skills::SkillEntry;
use d2_sim::stats::{StatData, StatTable};
use d2_sim::units::hooks::{MonsterInfo, Sim as USim, UnitData};
use d2_sim::units::lifecycle::AllocRequest;
use d2_sim::units::lists::client_state;
use d2_sim::units::modes;
use d2_sim::units::{RoomId, UnitId, UnitType};
use d2_sim::wiring::action::{ActionHooks, ActionTables, DrlgWorld, KillStep, Pending, SkillEvent};
use d2_sim::wiring::economy::{
    monster_death_drop, DeathDrops, DropSpot, FreeSpot, GameFields, ItemSpawn, ItemStore,
};
use d2_sim::wiring::interaction::{skill_events, UseRest};
use d2_sim::wiring::worldgen::{
    SharedTypes, WorldPending, WorldSim, WorldState, WorldTables, WorldTypes,
};
use d2_sim::world::cube::{
    input_flags, kind, CraftMod, CubeData, InputSlot, ItemRecord, OutputSlot, Recipe, CUBE_PAGE,
};
use d2_sim::world::npc::{class, NpcControl};
use d2_sim::world::quests::{PlayerQuests, QuestControl, QuestTables};
use d2_sim::world::waypoints::{WaypointData, NO_WAYPOINT};

mod e2e_support;
use e2e_support::{blank, item_tables, monstats as npc_monstats, tx, vendor_tables, Rest};
use e2e_support::{InvFx, BUC, CAP, N_MONSTATS};

// ---- constants -----------------------------------------------------------------------

/// The DRLG init seed of `outdoor.md`'s recorded Act I placement
/// (`dwStartSeed` 4014346869): act 0's levels are allocated by the real
/// level types from it.
const DRLG_SEED: u32 = 644_409_375;
/// The game seed (`rng.md` §5.3).
const GAME_SEED: u32 = 1234;
/// A preset level outside the Act I chain (40 × 18 tiles at (8000,
/// 8000)): the player's level, with a waypoint and the DS1 monster.
const ISLE: u32 = 30;
const ISLE_DEF: u32 = 1104;
/// The preset level the waypoint travels to: also outside the Act I
/// chain (40 × 18 at (9000, 9000)). A chain level (e.g. the Monastery
/// Gate) would generate its outdoor neighbours, which need `lvlsub` rows
/// this fixture does not have.
const GATE: u32 = 31;
const GATE_DEF: u32 = 1105;
/// Akara's position, beside the player.
const NPC_AT: (i32, i32) = (40_022, 40_022);
/// The player's gold before the trade.
const PLAYER_GOLD: i32 = 5000;
/// Stat ids (`itemstatcost`).
const STATPTS: u16 = 4;
const NEWSKILLS: u16 = 5;
const STRENGTH: u16 = 0;
const DEXTERITY: u16 = 2;
const LEVEL: u16 = 12;
const GOLD: u16 = 14;
const NEXTEXP: u16 = 30;
const ARMORCLASS: u16 = 31;
/// Waypoint indices (`levels.txt` `Waypoint`).
const ISLE_WP: u8 = 2;
const GATE_WP: u8 = 1;
/// The ISLE DS1's monster: DS1 sub-tile (12, 10), class 0.
const ISLE_MONSTER: (u32, u32) = (12, 10);
/// The player's position: room (8000, 8000)'s sub-tiles start at
/// (40000, 40000) (`rooms.md` §9.2, 5 sub-tiles per tile).
const PLAYER_AT: (i32, i32) = (40_020, 40_020);
/// The waypoint object's position.
const WP_AT: (i32, i32) = (40_024, 40_020);
/// Skills of the synthetic table: attack, and a right skill (srvst 4,
/// mana 4 + 1 per level, shift 8; `use.md`'s Multiple Shot vector).
const ATTACK: i32 = 0;

// ---- seams without a provider --------------------------------------------------

/// The action and world-generation seams no written spec provides yet
/// (positions and a straight-line path, warp, arrival mode, transport,
/// the DRLG population reads, the COF-name composer and the animation
/// rate, the monster death start's body), the skill use pipeline's rest
/// ([`UseRest`]: the player's skill state in [`Book`], for the message
/// and the timer paths alike), the drop state, and a log of the calls
/// that change something. The answers are the narrowest ones
/// (`Pending`'s defaults) except those the test stages (see each). The
/// player's interaction is the server host's (the NPC rest, `Rest`).
#[derive(Default)]
struct TestPending {
    pos: BTreeMap<UnitId, (i32, i32)>,
    sent: Vec<(UnitId, Vec<u8>)>,
    log: Vec<String>,
    /// Missile target points (`0x00648AD0`) and the sub-tiles each step
    /// crossed.
    aim: BTreeMap<UnitId, (i32, i32)>,
    crossed: BTreeMap<UnitId, Vec<(i32, i32)>>,
    velocity: BTreeMap<UnitId, i32>,
    /// The point the cast aims its missile at (the skill missile
    /// helpers' record fill, `use.md` §5.4 step 7, is not specified).
    aim_at: (i32, i32),
    book: Book,
    /// The game's drop state (`treasure.md` §3), lent out during a drop.
    drops: Option<DeathDrops>,
}

impl Pending for TestPending {
    fn anim_name(&self, _: UnitId, ty: UnitType, _: u32, mode: u32) -> Option<[u8; 8]> {
        match (ty, mode) {
            (UnitType::Player, 10) => Some(*PLAYER_SC),
            (UnitType::Monster, 0) => Some(*MONSTER_DT),
            _ => None,
        }
    }
    /// The rate formula `0x00623F50` is not written: the AnimData speed
    /// as is (no rate stats in this game).
    fn anim_rate(&self, _: UnitId, speed: Option<u32>) -> i16 {
        speed.map_or(0, |s| s as i16)
    }
    fn position(&self, unit: UnitId) -> (i32, i32) {
        self.pos.get(&unit).copied().unwrap_or_default()
    }
    fn place(&mut self, unit: UnitId, x: i32, y: i32) {
        self.pos.insert(unit, (x, y));
    }
    fn size(&self, _: UnitId) -> i32 {
        1
    }
    fn has_path(&self, _: UnitId) -> bool {
        true
    }
    fn set_velocity(&mut self, unit: UnitId, v: i32) {
        self.velocity.insert(unit, v);
    }
    fn velocity(&self, unit: UnitId) -> i32 {
        self.velocity.get(&unit).copied().unwrap_or(0)
    }
    fn set_target_point(&mut self, unit: UnitId, x: i32, y: i32) {
        self.aim.insert(unit, (x, y));
    }
    fn target_distance(&self, _: UnitId) -> i32 {
        10
    }
    /// One sub-tile toward the target point on each axis.
    fn step(&mut self, _: &mut Game, unit: UnitId) -> bool {
        let (x, y) = self.position(unit);
        let (tx, ty) = self.aim.get(&unit).copied().unwrap_or((x + 1, y));
        let p = (x + (tx - x).signum(), y + (ty - y).signum());
        self.pos.insert(unit, p);
        self.crossed.insert(unit, vec![p]);
        true
    }
    fn crossed_subtiles(&self, unit: UnitId) -> Vec<(i32, i32)> {
        self.crossed.get(&unit).cloned().unwrap_or_default()
    }
    fn may_attack(&self, a: UnitId, d: UnitId) -> bool {
        a != d
    }
    fn class_has_mode(&self, _: i32, _: u8) -> bool {
        true
    }
    fn skill_list(&self, _: UnitId) -> Vec<SkillEntry> {
        self.book.get().list.clone()
    }
    fn used_skill(&self, _: UnitId) -> Option<SkillEntry> {
        self.book.get().used
    }
    fn unit_event(
        &mut self,
        event: u8,
        unit: Option<UnitId>,
        _: Option<UnitId>,
        _: Option<&mut d2_sim::combat::DamageRecord>,
    ) {
        self.log
            .push(format!("event {event} {:?}", unit.map(|u| u.0)));
    }
    fn reaction(&mut self, a: UnitId, d: UnitId, r: &mut d2_sim::combat::DamageRecord) {
        self.log
            .push(format!("reaction {} {} {:#x}", a.0, d.0, r.result));
    }
    fn kill_step(&mut self, _: &mut Game, step: KillStep, d: UnitId, a: UnitId) {
        self.log.push(format!("kill {step:?} {} {}", d.0, a.0));
    }
    fn send(&mut self, player: UnitId, msg: &[u8]) {
        self.sent.push((player, msg.to_vec()));
    }
    fn warp(&mut self, _: &mut Game, player: UnitId, level: u32, tile_code: u8) {
        self.log
            .push(format!("warp {} {level} {tile_code}", player.0));
    }
    fn set_player_mode_arrival(&mut self, _: &mut Game, player: UnitId) {
        self.log.push(format!("arrival mode {}", player.0));
    }
    fn level_up_event(&mut self, unit: UnitId) {
        self.log.push(format!("level up {}", unit.0));
    }
    fn skill_event(h: &mut ActionHooks<Self>, sim: &mut USim<'_>, ev: SkillEvent) {
        skill_events::route(h, sim, ev);
    }
    fn action_frame(
        h: &mut ActionHooks<Self>,
        sim: &mut USim<'_>,
        u: UnitId,
        a1: u32,
        a2: u32,
    ) -> u32 {
        h.x.log.push(format!("action frame {} {a1} {a2}", u.0));
        skill_events::action_frame(h, sim, u, a1, a2)
    }
    /// The death start's body is not written: the fixture sets mode DT
    /// (a start function sets its mode, monster spec) and runs the drop
    /// gate and drop it is known to call (`treasure.md` §3.1).
    fn monster_death_start(
        h: &mut ActionHooks<Self>,
        sim: &mut USim<'_>,
        unit: UnitId,
        target: Option<UnitId>,
    ) -> bool {
        h.x.log.push(format!(
            "death start {} target {:?}",
            unit.0,
            target.map(|t| t.0)
        ));
        modes::set_mode(sim, h, unit, 0).expect("mode DT");
        if let Some(mut d) = h.x.drops.take() {
            monster_death_drop(h, sim, &mut d, &mut Spot, unit, target);
            h.x.drops = Some(d);
        }
        true
    }
}

/// The free-spot search `0x0064E810` (collision spec, not written): the
/// start spot as is.
struct Spot;

impl FreeSpot for Spot {
    fn free_spot(
        &mut self,
        room: Option<RoomId>,
        start: (i32, i32),
        _: (i32, i32),
    ) -> Option<DropSpot> {
        Some(DropSpot {
            room,
            x: start.0,
            y: start.1,
        })
    }
}

impl WorldPending for TestPending {
    fn preset_created(&mut self, unit: UnitId, p: &d2_sim::monsters::population::PresetUnit) {
        self.log.push(format!(
            "preset {} class {} at {},{}",
            unit.0, p.class, p.x, p.y
        ));
    }
}

impl Outbox for TestPending {
    fn take_sent(&mut self) -> Vec<(UnitId, Vec<u8>)> {
        std::mem::take(&mut self.sent)
    }
}

/// The skill use pipeline's rest (the message path through the server's
/// skill handlers, the action frame on the timer path): the player's
/// skill state from [`Book`], the rest narrowest.
impl UseRest for TestPending {
    fn send(&mut self, u: UnitId, msg: ServerMsg) {
        self.log.push(format!("send {} {msg:?}", u.0));
    }
    fn has_player_data(&self, _: UnitId) -> bool {
        true
    }
    fn last_point_frame(&self, _: UnitId) -> i32 {
        0
    }
    fn set_last_point_frame(&mut self, _: UnitId, _: i32) {}
    fn cursor_item(&self, _: UnitId) -> bool {
        false
    }
    fn in_own_inventory(&self, _: UnitId, _: UnitId) -> bool {
        false
    }
    fn within_reach(&self, _: UnitId, _: UnitId) -> bool {
        true
    }
    fn owner(&self, _: UnitId) -> Option<UnitId> {
        None
    }
    fn is_pet(&self, _: UnitId, _: UnitId) -> bool {
        false
    }
    fn is_ally(&self, _: UnitId, _: UnitId) -> bool {
        false
    }
    fn left_skill(&self, _: UnitId) -> Option<SkillEntry> {
        None
    }
    fn right_skill(&self, _: UnitId) -> Option<SkillEntry> {
        self.book.get().right
    }
    fn set_left_skill(&mut self, _: UnitId, _: SkillEntry) {}
    fn set_right_skill(&mut self, _: UnitId, e: SkillEntry) {
        self.book.get().right = Some(e);
    }
    fn find_entry(&self, u: UnitId, skill: i32) -> Option<SkillEntry> {
        self.book.find_entry(u, skill)
    }
    fn find_entry_owned(&self, _: UnitId, _: i32, _: i32) -> Option<SkillEntry> {
        None
    }
    fn owns_skill(&self, u: UnitId, skill: i32) -> bool {
        self.book.find_entry(u, skill).is_some()
    }
    fn set_used_skill(&mut self, _: UnitId, e: Option<SkillEntry>) {
        self.book.get().used = e;
    }
    fn used_skill_flags(&self, _: UnitId) -> u32 {
        0
    }
    fn set_used_skill_flags(&mut self, _: UnitId, _: u32) {}
    fn entry_mode(&self, u: UnitId, e: &SkillEntry) -> u32 {
        self.book.entry_mode(u, e)
    }
    fn attack_param4(&self, _: UnitId) -> i32 {
        0
    }
    fn set_attack_param4(&mut self, _: UnitId, _: i32) {}
    fn use_state(&mut self, _: UnitId, _: &SkillEntry) -> UseState {
        UseState::Usable
    }
    fn dec_quantity(&mut self, _: UnitId, _: i32) {}
    fn shapeshifted(&self, _: UnitId) -> bool {
        false
    }
    fn consume_charges(&mut self, _: UnitId, _: &SkillEntry) -> bool {
        true
    }
    fn pay_life(&mut self, _: UnitId, _: i32) -> bool {
        true
    }
    fn can_dual_wield(&self, _: UnitId) -> bool {
        false
    }
    fn equippable(&self, _: UnitId) -> bool {
        false
    }
    fn bow_equipped(&self, _: UnitId) -> bool {
        false
    }
    fn state_mask(&self, _: UnitId, _: u32) -> bool {
        false
    }
    fn start_mode(&mut self, _: &mut Game, _: UnitId, _: u32, _: ModeTarget<UnitId>) {}
    fn run_to(&mut self, _: UnitId, _: UnitId, _: SkillEntry) {}
    fn target(&self, _: UnitId) -> Option<UnitId> {
        None
    }
    fn clear_target(&mut self, _: UnitId) {}
    fn event_arg(&self, _: UnitId) -> i32 {
        0
    }
    fn set_event_arg(&mut self, _: UnitId, _: i32) {}
    fn step_path(&mut self, _: UnitId) -> i32 {
        0
    }
    fn target_position(&self, _: UnitId) -> Option<(i32, i32)> {
        Some(self.aim_at)
    }
    fn line_clear(&self, _: UnitId, _: (i32, i32), _: u32) -> bool {
        true
    }
    fn set_aura_state(&mut self, _: UnitId, _: u16, _: i32, _: i32) {}
    /// The helpers' record fill is not specified: aimed at the cast's
    /// target point, absolute.
    fn skill_missile_fill(&self, _: UnitId, _: bool, _: MissileAim, p: &mut MissileParams) {
        p.flags |= param_flags::TARGET_ABSOLUTE;
        (p.target_x, p.target_y) = self.aim_at;
    }
    fn srvst(&mut self, index: u16, u: UnitId, skill: i32, lvl: i32) -> i32 {
        self.book.srvst(index, u, skill, lvl)
    }
    fn srvdo(&mut self, i: u16, u: UnitId, s: i32, l: i32, c: bool, it: bool, a: bool) -> i32 {
        self.book.srvdo(i, u, s, l, c, it, a)
    }
}

/// The skill-point calls (`levels.md` §6.4): not reached in this run.
impl LearnRest for TestPending {
    fn is_class_skill(&self, _: UnitId, _: i32) -> bool {
        false
    }
    fn add_skill_level(&mut self, _: UnitId, _: i32, _: i32) {}
    fn after_skill_point(&mut self, _: UnitId) {}
}

/// The skill pipeline's state without a provider (skill list, skill
/// bodies: `use.md` OQ10): the player's skill list and a call log,
/// shared with the test.
#[derive(Default)]
struct Inner {
    list: Vec<SkillEntry>,
    right: Option<SkillEntry>,
    used: Option<SkillEntry>,
    log: Vec<String>,
}

#[derive(Clone, Default)]
struct Book(Arc<Mutex<Inner>>);

impl Book {
    fn get(&self) -> MutexGuard<'_, Inner> {
        self.0.lock().unwrap()
    }
    fn find_entry(&self, _: UnitId, skill: i32) -> Option<SkillEntry> {
        self.get().list.iter().copied().find(|e| e.skill == skill)
    }
    fn entry_mode(&self, _: UnitId, e: &SkillEntry) -> u32 {
        // Skill entry +8 (`use.md` §4): attack 7 (A1), the right skill
        // 10 (SC).
        if e.skill == MULTI {
            10
        } else {
            7
        }
    }
    fn srvst(&self, index: u16, _: UnitId, skill: i32, lvl: i32) -> i32 {
        self.get().log.push(format!("srvst {index} {skill} {lvl}"));
        1
    }
    /// The do bodies are catalogued only (`use.md` OQ10): logged, result
    /// 0 (the generic `srvmissile` creation of §5.4 step 7 still runs).
    #[allow(clippy::too_many_arguments)]
    fn srvdo(&self, i: u16, _: UnitId, s: i32, l: i32, c: bool, it: bool, a: bool) -> i32 {
        self.get()
            .log
            .push(format!("srvdo {i} {s} {l} {c} {it} {a}"));
        0
    }
}

// ---- DS1 / DT1 sources ---------------------------------------------------------------

#[derive(Default)]
struct Ds1s(BTreeMap<Vec<u8>, Ds1Input>);

impl Ds1Source for Ds1s {
    fn ds1(&self, path: &[u8]) -> Option<&Ds1Input> {
        self.0.get(path)
    }
}

/// A v18 DS1 of `w × h` tiles: one layer of plain floors, an empty
/// shadow layer, monsters (id = class) at DS1 sub-tile positions.
fn ds1(w: u32, h: u32, monsters: &[(u32, u32, u32)]) -> Ds1Input {
    let cells = ((w + 1) * (h + 1)) as usize;
    Ds1Input {
        version: 18,
        width: w,
        height: h,
        act: 0,
        tag_type: 0,
        walls: Vec::new(),
        orientations: Vec::new(),
        floors: vec![vec![cell::FLOOR; cells]],
        shadow: vec![0; cells],
        objects: monsters
            .iter()
            .map(|&(id, x, y)| Ds1ObjectInput {
                kind: 1,
                id,
                x,
                y,
                flags: 0,
            })
            .collect(),
        paths: Vec::new(),
    }
}

fn ds1s() -> Ds1s {
    let (x, y) = ISLE_MONSTER;
    Ds1s(BTreeMap::from([
        (
            format!("def{ISLE_DEF}.ds1").into_bytes(),
            ds1(40, 18, &[(0, x, y)]),
        ),
        (format!("def{GATE_DEF}.ds1").into_bytes(), ds1(40, 18, &[])),
    ]))
}

fn tile(o: u32, main: u32, sub: u32, rarity: u32) -> TileInfo {
    TileInfo {
        orientation: o,
        main,
        sub,
        rarity,
        material: 0,
        subtile_flags: [0; 25],
    }
}

struct Tiles(BTreeMap<Vec<u8>, Vec<TileInfo>>);

impl TileSource for Tiles {
    fn dt1(&self, path: &[u8]) -> Option<&[TileInfo]> {
        self.0.get(path).map(Vec::as_slice)
    }
}

fn tiles() -> Tiles {
    let mut t = BTreeMap::new();
    t.insert(b"floor.dt1".to_vec(), vec![tile(0, 0, 0, 1); 4]);
    let blank_tile = |sub| {
        let mut x = tile(0, 30, sub, 0);
        x.subtile_flags = [0x20; 25];
        x
    };
    t.insert(
        FIXED_LIBRARY[0].to_vec(),
        vec![blank_tile(0), blank_tile(1)],
    );
    t.insert(FIXED_LIBRARY[1].to_vec(), vec![]);
    t.insert(FIXED_LIBRARY[2].to_vec(), vec![tile(10, 0, 0, 0)]);
    Tiles(t)
}

// ---- tables -----------------------------------------------------------------------------

/// Act I sizes, offsets and Vis of `outdoor.md`'s recorded placement,
/// plus [`ISLE`] and the maze level 8; level types 1 and 3 with one DT1.
fn drlg_data() -> DrlgData {
    let mut d = DrlgData {
        levels: vec![LevelDef::default(); 150],
        ..DrlgData::default()
    };
    for l in &mut d.levels {
        l.warp = [-1; 8];
        l.level_type = 1;
    }
    let set = |d: &mut DrlgData, id: usize, ty: u32, size: (i32, i32), off: (i32, i32)| {
        d.levels[id].drlg_type = ty;
        d.levels[id].size = [size; 3];
        d.levels[id].offset = off;
    };
    set(&mut d, 1, 2, (56, 40), (0, 0));
    set(&mut d, 2, 3, (56, 96), (0, 0));
    set(&mut d, 3, 3, (80, 80), (0, 0));
    set(&mut d, 4, 3, (80, 80), (1000, 1000));
    set(&mut d, 5, 3, (80, 80), (0, 0));
    set(&mut d, 6, 3, (80, 80), (0, 0));
    set(&mut d, 7, 3, (80, 80), (0, 0));
    set(&mut d, 8, 1, (200, 200), (1500, 1000));
    set(&mut d, 17, 3, (40, 48), (0, 0));
    set(&mut d, 26, 2, (40, 18), (3000, 1000));
    set(&mut d, 27, 2, (40, 40), (0, 0));
    set(&mut d, 39, 3, (64, 64), (5000, 1148));
    set(&mut d, ISLE as usize, 2, (40, 18), (8000, 8000));
    set(&mut d, GATE as usize, 2, (40, 18), (9000, 9000));
    d.levels[8].level_type = 3;
    d.levels[2].vis = [1, 3, 0, 0, 0, 0, 0, 0];
    d.levels[3].vis = [2, 4, 17, 0, 0, 0, 0, 0];
    d.levels[1].vis = [2, 0, 0, 0, 0, 0, 0, 0];
    d.levels[4].vis = [3, 0, 0, 0, 0, 0, 0, 0];
    d.levels[17].vis = [3, 0, 0, 0, 0, 0, 0, 0];
    let mut files = vec![Vec::new(); 32];
    files[0] = b"floor.dt1".to_vec();
    d.lvltypes = vec![
        vec![Vec::new(); 32],
        files.clone(),
        vec![Vec::new(); 32],
        files,
    ];
    d
}

/// lvlprest rows 0..1199 (`Files` 1, DT1 mask 1), the preset levels'
/// rows (town Files 0, Monastery Gate, Outer Cloister Files 3, ISLE, the
/// travel level) and
/// the outdoor cell row 1103 (16 × 16, Files 2).
fn preset_data() -> PresetData {
    let mut defs: Vec<PresetDef> = (0..1200)
        .map(|i| PresetDef {
            def: i,
            files: 1,
            dt1_mask: 1,
            populate: 1,
            file: Default::default(),
            ..PresetDef::default()
        })
        .collect();
    for d in &mut defs {
        d.file[0] = format!("def{}.ds1", d.def).into_bytes();
    }
    for (i, level, files) in [
        (1100, 1, 0),
        (1101, 26, 1),
        (GATE_DEF, GATE, 1),
        (1102, 27, 3),
        (ISLE_DEF, ISLE, 1),
        (1103, 0, 2),
    ] {
        defs[i as usize].level_id = level;
        defs[i as usize].files = files;
    }
    defs[1103].size_x = 16;
    defs[1103].size_y = 16;
    PresetData {
        defs,
        monpreset_acts: Default::default(),
        monpreset: Vec::new(),
        monstats_count: 1,
        superuniques_count: 0,
        hdm_item: -1,
        tables: PresetTables::spec().expect("preset-tables.tsv"),
    }
}

fn outdoor_data(pd: &PresetData) -> OutdoorData {
    OutdoorData {
        levels: vec![
            SubDefs {
                sub_type: -1,
                sub_theme: -1,
                sub_waypoint: -1,
                sub_shrine: -1,
            };
            150
        ],
        presets: pd
            .defs
            .iter()
            .map(|d| OutdoorPreset {
                size_x: d.size_x as i32,
                size_y: d.size_y as i32,
                files: d.files,
            })
            .collect(),
        subs: Vec::new(),
    }
}

fn maze_data() -> MazeData {
    MazeData {
        rows: vec![MazeRow {
            level: 8,
            rooms: [1; 3],
            size_x: 24,
            size_y: 24,
            merge: 0,
        }],
        prest_files: (0..1200).map(|d| (d, 1)).collect(),
        specials: Specials::shipped(),
    }
}

/// levels.txt: no monsters, act by level id; waypoints at [`ISLE`] and
/// [`GATE`] only.
fn levels() -> Vec<Levels> {
    let mut v: Vec<Levels> = vec![blank(); 150];
    for (i, l) in v.iter_mut().enumerate() {
        for m in [
            &mut l.mon1,
            &mut l.mon2,
            &mut l.mon3,
            &mut l.mon4,
            &mut l.mon5,
            &mut l.mon6,
            &mut l.mon7,
            &mut l.mon8,
            &mut l.mon9,
            &mut l.mon10,
            &mut l.mon11,
            &mut l.mon12,
            &mut l.mon13,
            &mut l.mon14,
            &mut l.mon15,
            &mut l.mon16,
            &mut l.mon17,
            &mut l.mon18,
            &mut l.mon19,
            &mut l.mon20,
            &mut l.mon21,
            &mut l.mon22,
            &mut l.mon23,
            &mut l.mon24,
            &mut l.mon25,
            &mut l.nmon1,
            &mut l.umon1,
        ] {
            *m = 0xFFFF;
        }
        l.act = d2_sim::drlg::act_of_level(i as u32);
        l.waypoint = NO_WAYPOINT;
    }
    v[ISLE as usize].waypoint = ISLE_WP;
    v[GATE as usize].waypoint = GATE_WP;
    v
}

/// A synthetic itemstatcost: 359 stats, no ops, fixed up.
fn stat_data() -> Arc<StatData> {
    let (n, size) = (359, Itemstatcost::SIZE);
    let mut records = vec![0u8; n * size];
    for (s, r) in records.chunks_mut(size).enumerate() {
        for o in [0x32, 0x48, 0x4A, 0x56, 0x58, 0x5A, 0x5C] {
            r[o..o + 2].copy_from_slice(&0xFFFFu16.to_le_bytes());
        }
        r[0..2].copy_from_slice(&(s as u16).to_le_bytes());
    }
    let mut t = BinTable {
        name: "itemstatcost".into(),
        source: "synthetic".into(),
        count: n,
        record_size: size,
        records,
    };
    stat_ops(&mut t);
    Arc::new(StatData {
        stats: StatTable::from_fixed(&t).expect("itemstatcost"),
        ..StatData::default()
    })
}

/// One waypoint object class (0): operate 23, init 17.
fn waypoint_data() -> WaypointData {
    let mut o: Objects = blank();
    o.operatefn = 23;
    o.initfn = 17;
    o.framecnt1 = 15 << 8;
    WaypointData::new(&levels(), &[o])
}

// ---- the cube's item world --------------------------------------------------------------

/// Item types of the cube's items (`cube.md` V12 shape).
const T_RING: u16 = 10;
const T_BOX: u16 = 11;
const T_AMULET: u16 = 12;
/// The cube's item records, after the vendor items (`CAP`, `BUC`) in the
/// game's one item table.
const CUBE_BOX: usize = 2;
const RING: usize = 3;
const AMULET: usize = 4;

/// The game's item tables: the vendor items (`e2e_support::item_tables`:
/// cap, buckler) and the cube's items (`box `, a ring, an amulet; each
/// type is its own and type 0's).
fn game_item_tables() -> ItemTables {
    let mut t = item_tables();
    let rec = |ty: u16, code: &[u8; 4]| ItemRec {
        code: *code,
        type_: ty as i16,
        level: 1,
        ..ItemRec::default()
    };
    t.items.extend([
        rec(T_BOX, b"box "),
        rec(T_RING, b"rin "),
        rec(T_AMULET, b"amu "),
    ]);
    t
}

/// The inventory tables over the game's items (`InvTables`): the
/// measured grid records of `inventory.md` §1.3 (0–15) and the belt
/// boxes; the items' codes and types of [`game_item_tables`], with
/// synthetic sizes (cap, buckler, cube 2 × 2; ring, amulet 1 × 1) and no
/// requirement; helm to the head (1), shield to either hand.
fn inv_tables(t: &ItemTables) -> InvTables {
    let g = |x, y| GridRec {
        grid_x: x,
        grid_y: y,
    };
    let mut grids = vec![g(10, 4); 16];
    grids[5] = g(10, 10);
    grids[8] = g(6, 4);
    grids[9] = g(3, 4);
    grids[12] = g(6, 8);
    grids[13] = g(0, 0);
    let mut itemtypes = vec![
        InvTypeRec {
            class: 7,
            ..InvTypeRec::default()
        };
        t.itemtypes.len()
    ];
    for (ty, loc1, loc2) in [(ty::HELM, 1, 1), (ty::SHIE, 5, 4)] {
        let r = &mut itemtypes[usize::from(ty)];
        r.body = 1;
        r.bodyloc1 = loc1;
        r.bodyloc2 = loc2;
    }
    let sizes = [(2, 2), (2, 2), (2, 2), (1, 1), (1, 1)];
    InvTables {
        grids,
        belts: vec![12, 8, 4, 16, 8, 12, 16, 12, 8, 4, 16, 8, 12, 16],
        items: t
            .items
            .iter()
            .zip(sizes)
            .map(|(r, (w, h))| InvItemRec {
                code: r.code,
                type_: r.type_,
                invwidth: w,
                invheight: h,
                ..InvItemRec::default()
            })
            .collect(),
        itemtypes,
        equiv: t.equiv.clone(),
    }
}

/// One recipe (`cube.md` V12 shape without mods): one ring → a normal
/// amulet.
fn cube_data(t: &ItemTables) -> CubeData {
    let mut inputs = [InputSlot::default(); 7];
    inputs[0] = InputSlot {
        flags: input_flags::USEANY,
        item: RING as u16,
        ..InputSlot::default()
    };
    let out = OutputSlot {
        kind: kind::ITEMCODE,
        item: AMULET as u16,
        quality: q::NORMAL,
        mods: [CraftMod {
            property: -1,
            ..CraftMod::default()
        }; 5],
        ..OutputSlot::default()
    };
    CubeData {
        recipes: vec![Recipe {
            enabled: 1,
            class: 0xFF,
            numinputs: 1,
            inputs,
            outputs: [out, OutputSlot::default(), OutputSlot::default()],
            ..Recipe::default()
        }],
        items: t
            .items
            .iter()
            .map(|r| ItemRecord {
                code: r.code,
                level: r.level,
                spawnable: 1,
                ..ItemRecord::default()
            })
            .collect(),
        valshift: vec![0; 359],
        max_level: 99,
    }
}

/// The cube's calls no written spec owns (`ItemPending`: inventory
/// placement and removal `0x00560200` / `0x0055DF10`, the inventory
/// pass): placement appends to the staged list, removal drops from it;
/// every call is logged.
#[derive(Clone, Default)]
struct CubeRest(Arc<Mutex<Vec<String>>>);

impl CubeRest {
    fn log(&self, s: String) {
        self.0.lock().unwrap().push(s);
    }
}

impl ItemPending for CubeRest {
    fn inventory_pass(&mut self, _: UnitId, _: &mut Vec<Vec<u8>>) {
        self.log("inventory pass".into());
    }
    fn place(
        &mut self,
        inv: &mut Inventory,
        _: UnitId,
        item: UnitId,
        _: &mut Vec<Vec<u8>>,
    ) -> bool {
        inv.items.push(item);
        if inv.cursor == Some(item) {
            inv.cursor = None;
        }
        self.log(format!("place {}", item.0));
        true
    }
    fn remove_cube_item(
        &mut self,
        inv: &mut Inventory,
        _: UnitId,
        item: UnitId,
        _: &mut Vec<Vec<u8>>,
    ) {
        inv.items.retain(|&i| i != item);
        self.log(format!("remove {}", item.0));
    }
    fn socketed(&self, _: UnitId) -> Vec<UnitId> {
        Vec::new()
    }
    fn duplicate(&mut self, _: UnitId, _: bool) -> Option<UnitId> {
        None
    }
    fn tempered_affix(&mut self, _: UnitId, _: bool) -> u16 {
        0
    }
    fn drop_runeword_stats(&mut self, _: UnitId) {}
    fn repair(&mut self, _: UnitId) {}
    fn recharge(&mut self, _: UnitId) {}
    fn quest_item_hook(&mut self, _: UnitId, _: UnitId, _: [u8; 4]) {}
    fn cow_portal(&mut self, _: UnitId) -> bool {
        false
    }
}

// ---- the game --------------------------------------------------------------------------

type Sim = SimGame<WorldSim<TestPending>, WiredWorld<Rest, WiredSkills>>;

/// Manual host clock (ms), injected into the host (`tick.md` §8).
struct Ms(u32);

impl Clock for Ms {
    fn now_ms(&mut self) -> u32 {
        self.0
    }
}

type Link = LocalLink<Sim, ProtoSizes, PendingSession, Ms>;

/// The local link, recording every S→C chunk the bridge receives.
struct Tap {
    inner: Link,
    chunks: Vec<Vec<u8>>,
}

impl ServerLink for Tap {
    fn protocol_version(&self) -> u32 {
        self.inner.protocol_version()
    }
    fn send(&mut self, queue: SendQueue, msg: &[u8]) -> Result<Sent, LinkError> {
        self.inner.send(queue, msg)
    }
    fn pump(&mut self) -> Result<Pumped, LinkError> {
        self.inner.pump()
    }
    fn receive(&mut self) -> Vec<Vec<u8>> {
        let got = self.inner.receive();
        self.chunks.extend(got.iter().cloned());
        got
    }
}

const ALIVE: PlayerGate = PlayerGate {
    mode: 1,
    uninterruptable: false,
};

/// Steps 1–3 before the first host frame: game creation, the generated
/// level, the player's room streamed, the player and the waypoint object
/// allocated there, the client joined (its room not yet set: the first
/// tick's room change activates the rooms near the player).
struct Fx {
    bridge: Bridge<Tap>,
    player: UnitId,
    wp: u32,
    book: Book,
    /// The ISLE level's DRLG rooms.
    level_rooms: Vec<DrlgRoomId>,
    /// Akara; the player's buckler (re-sellable) and cap (one of
    /// Akara's permanent codes).
    npc: UnitId,
    buckler: UnitId,
    cap: UnitId,
    /// The cube and the cursor ring.
    cube: UnitId,
    ring: UnitId,
    cube_rest: CubeRest,
    /// The item-move seams' staged answers and log.
    inv: InvFx,
}

impl Fx {
    fn new(game_seed: u32) -> Self {
        // 1. Game creation: act 0's DRLG through the level-type
        // dispatcher on the recorded init seed; regions on the game seed.
        let data = Arc::new(drlg_data());
        let pd = preset_data();
        let types = SharedTypes::new(WorldTypes::new(
            data.clone(),
            Maze::new(maze_data()),
            pd.clone(),
            outdoor_data(&pd),
            Box::new(ds1s()),
            Box::new(SubFileMap::default()),
        ));
        let mut handle = types.clone();
        let drlg = Drlg::create(0, DRLG_SEED, 0, 0, false, &data, &mut handle).expect("act 0");
        let mut dungeon = Dungeon::default();
        dungeon.acts[0] = Some(drlg);
        let world = DrlgWorld {
            dungeon,
            data,
            tiles: Box::new(tiles()),
            types: Box::new(handle),
        };
        let tables = ActionTables {
            missiles: vec![arrow()],
            skills: skills(),
            combat: combat_tables(),
            levels: levels(),
            skill_modes: vec![[0; 3]],
        };
        let book = Book::default();
        let mut hooks = ActionHooks::new(
            Arc::new(tables),
            world,
            Seed::init_low(game_seed),
            TestPending {
                book: book.clone(),
                drops: Some(DeathDrops::new(
                    Arc::new(drop_tables()),
                    GameFields::new(Seed::init_low(game_seed), false),
                )),
                ..TestPending::default()
            },
        );
        hooks.anim_data = Some(Arc::new(anim_data()));
        hooks.vitals = Some(Arc::new(vitals()));
        let wt = WorldTables {
            pop: PopTables::from_records(&levels(), &[monster_class()], &[blank()], &[]),
            monstats: vec![monster_class()],
            monstats2: vec![blank()],
            monlvl: vec![blank::<Monlvl>(); 10],
            levels: levels(),
            difficultylevels: vec![blank::<Difficultylevels>(); 3],
            monstats_extra: vec![MonstatsExtra::default()],
            components: vec![[0; 16]],
            ..WorldTables::default()
        };
        let state = WorldState::new(types, Arc::new(wt), GameInfo::default());
        let unit_data = UnitData {
            // Class 0 (the DS1 monster) moves; the others (Akara) are
            // enabled and stand.
            monsters: (0..N_MONSTATS)
                .map(|c| MonsterInfo {
                    enabled: true,
                    aidel: [15; 3],
                    moves: if c == 0 { 1 << 4 } else { 0 },
                })
                .collect(),
            ..UnitData::default()
        };
        let mut sim = WorldSim::new(stat_data(), unit_data, hooks, state);
        sim.create_regions();
        // The world systems' game-creation seeds: the NPC control (its
        // seed from the game seed, `rng.md` §5.2) and the quests, after
        // the regions (the order among the creation seeds beyond
        // `NpcControl::new` → `QuestControl::new` is not written: a
        // fixture order, `docs/handoff/e2e-next.md` §4).
        let mut seed = sim.action.hooks().game_seed;
        let ctl = NpcControl::new(&npc_monstats(), Vec::new(), false, 0, &mut seed).expect("npc");
        let quests = QuestControl::new(&QuestTables::load().unwrap(), &mut seed).unwrap();
        sim.action.hooks().game_seed = seed;
        let mut game = Game::new();
        game.lists.ensure_act(0).unwrap();

        // 2. The level, by the real preset generator; the player's room
        // streamed (`rooms.md` §9.2).
        let (level_rooms, room) = sim
            .action
            .hooks()
            .drlg
            .with_act(0, &mut game.lists, |d, svc| {
                let l = d.get_or_alloc_level(svc.data, svc.types, ISLE)?;
                d.generate_level(svc.data, svc.types, l)?;
                let rooms = d.level_rooms(l);
                let a = *rooms
                    .iter()
                    .find(|&&r| d.room(r).rect == d2_sim::drlg::TileRect::new(8000, 8000, 8, 8))
                    .expect("room at the level origin");
                let active = d.stream_room(svc, a)?.expect("active");
                Ok::<_, d2_sim::drlg::DrlgError>((rooms, active))
            })
            .expect("act 0")
            .expect("generated");

        // 3. The player (a sorceress, class 1) and the waypoint object.
        let mut alloc = |ty, class, (x, y): (i32, i32)| {
            let req = AllocRequest {
                ty,
                class,
                room: Some(room),
                add: true,
                fixed_guid: None,
                mode: 1,
                allied: ty == UnitType::Player,
            };
            sim.action
                .with(&mut game, |g, v| v.allocate(g, &req, x, y))
                .expect("allocated")
        };
        let object = alloc(UnitType::Object, 0, WP_AT);
        let player = alloc(UnitType::Player, 1, PLAYER_AT);
        // Akara beside the player (allocated as the DS1 monster is; her
        // kind init is the monster spec's, not run here).
        let npc = alloc(UnitType::Monster, u32::from(class::AKARA), NPC_AT);
        // Players are allocated in mode 0; neutral (`units.md` §2).
        sim.action.sys.units.get_mut(player).unwrap().mode = 1;
        // Both waypoints known (`waypoints.md` §2).
        let rec = sim.action.hooks().waypoints.entry(player).or_default();
        rec.get_mut(0).set(ISLE_WP.into()).unwrap();
        rec.get_mut(0).set(GATE_WP.into()).unwrap();
        // Mana and max mana 4000 (1/256 units), gold; dexterity 25
        // (synthetic; the equip requirements, `inventory.md` §4.2, refuse
        // a stat below 1).
        sim.action.with(&mut game, |_, v| {
            v.set_base(player, 8, 4000);
            v.set_base(player, 9, 4000);
            v.set_base(player, GOLD, PLAYER_GOLD);
            v.set_base(player, DEXTERITY, 25);
        });
        let wp = game.lists.unit(object).unwrap().guid;

        // The world host: waypoints and skills (`ActionWorld`), the NPC /
        // vendor / quest systems and the cube on the same units
        // (`WiredWorld`).
        let mut rest = Rest::default();
        rest.quests.insert(player, PlayerQuests::default());
        let action = ActionWorld {
            waypoints: Some(waypoint_data()),
            skills: WiredSkills::default(),
            ..ActionWorld::default()
        };
        let mut world = WiredWorld::new(
            action,
            game_item_tables(),
            quests,
            ctl,
            vendor_tables(),
            rest,
            1000,
        );
        // Monster init embeds the NPC's interaction list (`npc.md` §2).
        world.state.add_npc(npc);
        // The player's buckler and cap (stored, mode 0), then the cube
        // (stored) and a ring on the cursor (mode 4), made by the economy
        // wiring on the game seed into the game's one item store; the
        // inventories that hold them are staged (no inventory spec).
        let (buckler, cap, cube, ring) = world.with_economy(&mut game, &mut sim, |econ, _| {
            let mut make = |record: usize, quality: u8, ilvl: i32, mode: u32| {
                let mut rq = ItemRequest {
                    item: record as i32,
                    ilvl,
                    quality,
                    format: 1,
                    ..ItemRequest::default()
                };
                let spawn = ItemSpawn {
                    room: None,
                    mode,
                    init_flags: 1,
                };
                econ.create_item(&mut rq, false, spawn).expect("item")
            };
            let (buckler, cap) = (make(BUC, 2, 1, 0), make(CAP, 2, 1, 0));
            let cube = make(CUBE_BOX, q::NORMAL, 5, 0);
            let ring = make(RING, q::NORMAL, 5, 4);
            for u in [cube, ring] {
                econ.items.get_mut(u).unwrap().inv_page = 0;
            }
            (buckler, cap, cube, ring)
        });
        world.rest.inventory.extend([buckler, cap]);
        // The cube's parts: its tables, the staged inventory (the cube
        // stored, the ring on the cursor), the local date, the pending
        // inventory calls.
        let cube_rest = CubeRest::default();
        let mut parts = CubeParts::new(cube_data(&world.tables), Box::new(cube_rest.clone()));
        parts.staged.local_date = (15, 3);
        parts.staged.inventories.insert(
            player,
            Inventory {
                items: vec![cube],
                cursor: Some(ring),
            },
        );
        world.cube = Some(parts);
        // The inventories and the item-move seams (`inventory.md`): the
        // player's inventory (`0x0063ABD0` at player creation: the unit
        // spec's, done here), the staged answers of `InvFx`.
        let inv = InvFx::default();
        inv.with(|r| {
            r.distance = 3;
            r.room = Some(room);
            r.pos.insert(
                Owner::player(game.lists.unit(player).unwrap().guid),
                PLAYER_AT,
            );
        });
        let mut parts = InvParts::new(inv_tables(&world.tables), Box::new(inv.clone()));
        let pg = game.lists.unit(player).unwrap().guid;
        parts
            .state
            .add_inventory(player, InvKind::Player { class: 1 }, pg);
        world.inventory = Some(parts);

        let mut s: Sim = SimGame::with_world(game, sim, world);
        s.join(LOCAL_CLIENT_ID, Some(player), None, client_state::IN_GAME)
            .unwrap();
        s.set_player(
            player,
            PlayerFields {
                gate: ALIVE,
                data: Some(PlayerData { last_accept: 0 }),
            },
        );
        s.set_unit(player, facts(PLAYER_AT));
        s.set_unit(object, facts(WP_AT));
        s.set_unit(npc, facts(NPC_AT));
        let multi = SkillEntry {
            skill: MULTI,
            base: 10,
            owner_guid: -1,
            ..SkillEntry::default()
        };
        {
            let mut b = book.get();
            b.list = vec![
                SkillEntry {
                    skill: ATTACK,
                    base: 1,
                    owner_guid: -1,
                    ..SkillEntry::default()
                },
                multi,
            ];
            b.right = Some(multi);
        }

        let link = LocalLink::new(Host::new(
            s,
            ProtoSizes,
            PendingSession::default(),
            Ms(1000),
        ));
        let tap = Tap {
            inner: link,
            chunks: Vec::new(),
        };
        let bridge = Bridge::with_dispatch(tap, Dispatch::from_spec().unwrap()).unwrap();
        Fx {
            bridge,
            player,
            wp,
            book,
            level_rooms,
            npc,
            buckler,
            cap,
            cube,
            ring,
            cube_rest,
            inv,
        }
    }

    /// What the unwritten kind init and movement specs would set for the
    /// monster: its target flags (`missiles.md` §R4.2) and its run-time
    /// collision bit at its position (`rooms.md` §10.6). The player's to-hit
    /// inputs: attack rating 100, level 1 (`hit.md` §3).
    fn stage_combat(&mut self, monster: UnitId) {
        let player = self.player;
        let sim = self.sim();
        sim.events.action.sys.units.get_mut(monster).unwrap().flags |=
            unit_flag::IS_VALID_TARGET | unit_flag::CAN_BE_ATTACKED;
        let (x, y) = sim.events.action.hooks().x.position(monster);
        let room = sim.game.lists.unit(monster).unwrap().room().unwrap();
        let game = &sim.game;
        *sim.events
            .action
            .sys
            .hooks
            .drlg
            .collision_mut(game, room, x, y)
            .expect("in a grid") |= bits::MONSTER;
        sim.events.action.hooks().x.aim_at = (x, y);
        sim.events.action.with(&mut sim.game, |_, v| {
            v.set_base(player, 19, 100);
            v.set_base(player, 12, 1);
        });
    }

    /// The missile units of the game, in id order.
    fn missiles(&self) -> Vec<UnitId> {
        let mut v = self.sim_ref().game.lists.units_of_type(UnitType::Missile);
        v.sort();
        v
    }

    /// The damage setup `0x0059F900` is the skills spec's (`Pending`):
    /// the missile's damage stats (21, 22, 1/256 points) are set here.
    fn set_missile_damage(&mut self, m: UnitId, d: i32) {
        let sim = self.sim();
        sim.events.action.with(&mut sim.game, |_, v| {
            v.set_base(m, 21, d);
            v.set_base(m, 22, d);
        });
    }

    /// The unit's timer events (type, expiry), sorted.
    fn timers(&self, u: UnitId) -> Vec<(u8, i32)> {
        let t = &self.sim_ref().game.timers;
        let mut v: Vec<_> = t
            .unit_timers(u)
            .into_iter()
            .filter_map(|i| Some((t.event(i)?.0, t.expire(i)?)))
            .collect();
        v.sort();
        v
    }

    /// The drops so far: item and spot.
    fn drops(&self) -> Vec<(UnitId, DropSpot)> {
        self.sim_ref()
            .events
            .action
            .sys
            .hooks
            .x
            .drops
            .as_ref()
            .unwrap()
            .placed
            .clone()
    }

    fn sim(&mut self) -> &mut Sim {
        &mut self.bridge.link_mut().inner.host_mut().game
    }

    fn sim_ref(&self) -> &Sim {
        &self.bridge.link().inner.host().game
    }

    fn pending(&mut self) -> &mut TestPending {
        &mut self.sim().events.action.hooks().x
    }

    /// A normal cap on the ground of the player's room at (x + 1, y + 1)
    /// of the player, made by the economy wiring on the game seed into
    /// the host's one item store; identified (callers set 0x10,
    /// `generation.md` §1.4); its position in its item data (§2.2).
    fn ground_cap(&mut self) -> UnitId {
        let room = self.sim_ref().game.lists.unit(self.player).unwrap().room();
        let sim = self.sim();
        let (game, events, world) = (&mut sim.game, &mut sim.events, &mut sim.world);
        let cap = world.with_economy(game, events, |econ, _| {
            let mut rq = ItemRequest {
                item: CAP as i32,
                ilvl: 1,
                quality: q::NORMAL,
                format: 1,
                ..ItemRequest::default()
            };
            let spawn = ItemSpawn {
                room,
                mode: 3,
                init_flags: 1,
            };
            econ.create_item(&mut rq, false, spawn).expect("cap")
        });
        world.items.get_mut(cap).unwrap().flags |= flag::IDENTIFIED;
        let guid = game.lists.unit(cap).unwrap().guid;
        let inv = world.inventory.as_mut().unwrap();
        inv.state.items.insert(
            cap,
            InvItem {
                x: PLAYER_AT.0 + 1,
                y: PLAYER_AT.1 + 1,
                ..InvItem::new(guid, CAP)
            },
        );
        cap
    }

    /// The server host's cube parts.
    fn cube_parts(&mut self) -> &mut CubeParts {
        self.sim().world.cube.as_mut().unwrap()
    }

    /// The game's one item store.
    fn items(&mut self) -> &mut ItemStore {
        &mut self.sim().world.items
    }

    fn guid(&self, u: UnitId) -> u32 {
        self.sim_ref().game.lists.unit(u).unwrap().guid
    }

    fn mode(&self, u: UnitId) -> u32 {
        self.sim_ref().events.action.sys.units.get(u).unwrap().mode
    }

    /// Stat `s` of unit `u` (unit getter, `stats.md`).
    fn stat(&mut self, u: UnitId, s: u16) -> i32 {
        let sim = self.sim();
        sim.events.action.with(&mut sim.game, |_, v| v.stat(u, s))
    }

    /// The player's timer events (type, expiry).
    fn player_timers(&self) -> Vec<(u8, i32)> {
        self.timers(self.player)
    }

    /// The monsters other than Akara, in id order.
    fn monsters(&self) -> Vec<UnitId> {
        let mut v = self.sim_ref().game.lists.units_of_type(UnitType::Monster);
        v.retain(|&m| m != self.npc);
        v.sort();
        v
    }

    /// Every error so far: world adapters, level types, action adapters,
    /// the unit dispatch, the world handlers' faults.
    fn errors(&self) -> Vec<String> {
        let s = self.sim_ref();
        let mut e = s.events.errors();
        e.extend(s.world.action.faults.iter().map(|f| format!("{f:?}")));
        e.extend(s.world.state.errors.iter().map(|f| format!("{f:?}")));
        if let Some(c) = &s.world.cube {
            e.extend(c.errors.iter().map(|f| format!("{f:?}")));
        }
        if let Some(i) = &s.world.inventory {
            e.extend(i.state.errors.iter().map(|f| format!("{f:?}")));
        }
        e.extend(s.tick_faults.iter().map(|f| format!("{f:?}")));
        e
    }

    /// Sends `msgs` through the bridge, advances the host clock 40 ms
    /// (one tick, `tick.md` §1) and runs one bridge frame. The frame's
    /// result codes, the S→C bytes the client received, the bridge
    /// report.
    fn step(&mut self, msgs: &[Vec<u8>]) -> Step {
        for m in msgs {
            assert_eq!(self.bridge.send_bytes(m).unwrap(), Sent::Queued);
        }
        self.bridge.link_mut().inner.host_mut().clock.0 += 40;
        let report = self.bridge.frame().unwrap();
        let host = self.bridge.link().inner.last_frame();
        let codes = host
            .messages
            .iter()
            .map(|h| match h.handled {
                Handled::Game(Outcome::Dispatched(c)) => (h.id, Some(c)),
                _ => (h.id, None),
            })
            .collect();
        Step {
            codes,
            received: self.bridge.log().unowned.clone(),
            report,
        }
    }
}

const LOCAL_CLIENT_ID: u32 = d2_client::bridge::LOCAL_CLIENT;

fn facts((x, y): (i32, i32)) -> UnitFacts {
    UnitFacts {
        act: 0,
        pos: Pos { x, y },
        owner: None,
    }
}

/// One bridge frame: (C→S id, result) per drained message, the
/// bridge's unowned S→C counts so far, the frame report.
#[derive(Debug, PartialEq, Eq)]
struct Step {
    codes: Vec<(u8, Option<ResultCode>)>,
    received: BTreeMap<u8, u64>,
    report: FrameReport,
}

fn bytes<M: d2_proto::FixedMessage>(m: &M) -> Vec<u8> {
    d2_client::bridge::intent::encode(m)
}

// ---- the run ----------------------------------------------------------------------------

/// One recorded bridge frame: the C→S bytes sent, the drained results,
/// the S→C chunks the client received.
type Frame = (Vec<Vec<u8>>, Step, Vec<Vec<u8>>);

/// Everything a run leaves behind, compared byte for byte between runs.
#[derive(Debug, PartialEq, Eq)]
struct Transcript {
    /// Per bridge frame: the C→S bytes sent, the drained results, the
    /// S→C chunks the client received.
    frames: Vec<Frame>,
    game_frame: i32,
    game_seed: Seed,
    /// Monsters: GUID, unit seed, position, mode.
    monsters: Vec<(u32, Seed, (i32, i32), u32)>,
    active_rooms: Vec<RoomId>,
    player_mode: u32,
    player_mana: i32,
    player_exp: i32,
    /// Dropped items: GUID, unit seed, position, mode; their gold.
    drops: Vec<(u32, Seed, i32, i32, u32)>,
    gold: Vec<i32>,
    pending_log: Vec<String>,
    skill_log: Vec<String>,
    /// The player's level, stat points, strength and gold at the end.
    player_stats: Vec<i32>,
    /// Akara's store: GUID, record, item seed, AC.
    store: Vec<(u32, usize, Seed, i32)>,
    npc_seed: Seed,
    rest_log: Vec<String>,
    cube_log: Vec<String>,
    /// The item-move seams' log.
    inv_log: Vec<String>,
    unhandled: Vec<(u32, u8, usize)>,
    client: (u64, u64, usize),
    errors: Vec<String>,
}

/// A recording bridge frame.
fn record(fx: &mut Fx, frames: &mut Vec<Frame>, msgs: Vec<Vec<u8>>) {
    let before = fx.bridge.log().unowned.values().sum::<u64>();
    let step = fx.step(&msgs);
    // The bridge has no S→C handler yet (`bridge-dispatch.tsv`: every id
    // TBD), so each received message is counted unowned; the chunks are
    // taken from the host's flush report.
    let chunks = std::mem::take(&mut fx.bridge.link_mut().chunks);
    let after = fx.bridge.log().unowned.values().sum::<u64>();
    assert_eq!(after - before, step.report.messages as u64);
    frames.push((msgs, step, chunks));
}

fn run() -> Transcript {
    run_with(GAME_SEED)
}

fn run_with(game_seed: u32) -> Transcript {
    let mut fx = Fx::new(game_seed);
    let mut frames = Vec::new();
    let (player, wp) = (fx.player, fx.wp);
    // Each step says what it sends; a frame that sends nothing is
    // asserted empty.
    let none: Vec<Vec<u8>> = Vec::new();

    // Before any frame: one active room (the player's), no monster, the
    // generated level's 15 preset rooms (40 × 18 tiles, `preset.md`
    // §3.2).
    assert_eq!(fx.level_rooms.len(), 15);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 1);
    assert!(fx.monsters().is_empty());

    // Frame 1 at 1000 ms: the tick driver starts its clock; no tick.
    let r = fx.bridge.frame().unwrap();
    assert!(!r.ticked);

    // Frame 2 (tick 1): the client's room change activates the rooms
    // near the player's (`rooms.md` §4.1: 4 rooms); the room pass
    // creates the DS1's preset monster at its sub-tile (`population.md`
    // §11.1). No step sends.
    record(&mut fx, &mut frames, vec![]);
    assert_eq!(frames[0].2, none);
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 4);
    let monsters = fx.monsters();
    assert_eq!(monsters.len(), 1, "the DS1 preset monster");
    let monster = monsters[0];
    let mpos = fx.pending().pos[&monster];
    assert_eq!(mpos, (40_012, 40_010));
    assert_eq!(
        fx.pending().log,
        [format!("preset {} class 0 at 12,10", monster.0)]
    );
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    fx.sim().set_unit(monster, facts(mpos));

    // 4. Right skill at the monster (C→S 0x0C, `use.md` §1): accepted
    // (0), mana charged at start (the Multiple Shot vector: 3,328 of
    // 4,000 in 1/256 units), srvst 4 run, mode SC (10) set. The mode
    // start's animation schedule (`units.md` §4.1–§4.2) reads the
    // AnimData record of the composed name (`animdata.md` §5): 8 frames
    // at speed 256, event byte 2 on frame 4 → event 0 at f + 4 = 5 with
    // args (2, 0), the end (event 1) at f + 8 = 9.
    fx.stage_combat(monster);
    let cast = bytes(&RightSkill {
        x: mpos.0 as u16,
        y: mpos.1 as u16,
    });
    assert_eq!(cast, [0x0C, 0x4C, 0x9C, 0x4A, 0x9C]);
    record(&mut fx, &mut frames, vec![cast]);
    assert_eq!(fx.sim_ref().game.frame, 2);
    assert_eq!(frames[1].1.codes, [(0x0C, Some(ResultCode::Done))]);
    assert_eq!(frames[1].2, none);
    assert_eq!(fx.mode(player), 10);
    assert_eq!(fx.stat(player, 8), 4000 - 3328);
    assert_eq!(fx.book.get().log, ["srvst 4 1 10"]);
    assert_eq!(fx.player_timers(), [(0, 5), (1, 9)]);
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // Frames 3–5. On frame 5 the action frame `0x00580460` runs the used
    // skill's do function (`use.md` §5.2, §5.4): srvdo 8 (body
    // catalogued only, `use.md` OQ10: the seam), then the generic
    // `srvmissile` 0 through the real missile creation (`missiles.md`
    // §R2) at the player, aimed at the cast point.
    for _ in 3..=5 {
        record(&mut fx, &mut frames, vec![]);
    }
    assert_eq!(fx.sim_ref().game.frame, 5);
    assert_eq!(
        fx.pending().log[1..],
        [format!("action frame {} 2 0", player.0)]
    );
    assert_eq!(
        fx.book.get().log,
        ["srvst 4 1 10", "srvdo 8 1 10 true false false"]
    );
    assert_eq!(fx.player_timers(), [(1, 9)]);
    let shot = fx.missiles();
    assert_eq!(shot.len(), 1);
    let shot = shot[0];
    assert_eq!(fx.pending().pos[&shot], PLAYER_AT);
    // The damage setup `0x0059F900` is the skills spec's: 10 points.
    fx.set_missile_damage(shot, 2560);

    // Frames 6–15: the missile flies one sub-tile a frame (the fixture's
    // path) and enters the monster's sub-tile on frame 15: hit
    // (`missiles.md` §R5, to-hit on the player's seed), damage 10 points
    // ≥ the monster's 5 → life 0, result 3 (`damage.md` §5.2 steps
    // 11–15: events 10, 9), the missile removed (collide-kill). The
    // reaction (§7.1) kills the monster (§7.2): its seam steps in order,
    // the death mode change with the player as target (mode DT 0, the
    // death start `0x005A6FF0`), the player's experience (`vitals.md`
    // §4.2: equal levels → 100).
    for _ in 6..=15 {
        record(&mut fx, &mut frames, vec![]);
    }
    assert_eq!(fx.sim_ref().game.frame, 15);
    assert_eq!(fx.mode(player), 1, "event 1 on frame 9 → neutral");
    assert!(fx.missiles().is_empty());
    assert_eq!(fx.stat(monster, 6), 0);
    assert_eq!(fx.mode(monster), 0);
    let (p, m) = (player.0, monster.0);
    assert_eq!(
        fx.pending().log[2..],
        [
            format!("event 0 Some({m})"),
            format!("event 11 Some({m})"),
            format!("event 2 Some({m})"),
            format!("event 10 Some({m})"),
            format!("event 9 Some({p})"),
            format!("reaction {p} {m} 0x3"),
            format!("kill PetCredit {m} {p}"),
            format!("kill AttackerBookkeeping {m} {p}"),
            format!("kill FaceAttacker {m} {p}"),
            format!("death start {m} target Some({p})"),
            format!("kill QuestKill {m} {p}"),
            format!("kill BarricadeDoors {m} {p}"),
            // The experience last (C2), its level-up event (§4.3).
            format!("level up {p}"),
        ]
    );
    assert_eq!(fx.stat(player, 13), 100);
    // The death animation: 4 frames → event 1 at 19.
    assert_eq!(fx.timers(monster), [(1, 19)]);

    // 5a. The drop (`treasure.md` §3): the death start's gate passes
    // (no flag 0x20000, no wall / door at the monster's sub-tile); TC 1
    // picks gold on the monster's seed; the item is created on the game
    // seed (`generation.md` §3), placed at the start spot (x + 2, y + 3,
    // §7 step 2) and added to that room's units in mode 3, its gold
    // amount (§8) in stat 14.
    let drops = fx.drops();
    assert_eq!(drops.len(), 1);
    let (gold, spot) = drops[0];
    let room = fx.sim_ref().game.lists.unit(monster).unwrap().room();
    assert_eq!(
        spot,
        DropSpot {
            room,
            x: mpos.0 + 2,
            y: mpos.1 + 3
        }
    );
    assert_eq!(fx.sim_ref().game.lists.unit(gold).unwrap().room(), room);
    let rec = fx.sim_ref().events.action.sys.units.get(gold).unwrap();
    assert_eq!((rec.ty, rec.class, rec.mode), (UnitType::Item, 0, 3));
    let amount = fx.stat(gold, 14);
    assert!((1..=6).contains(&amount), "roll(5 · 1) + 1: {amount}");
    for f in &frames[2..] {
        assert_eq!(f.2, none);
    }
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // Level-up (`vitals.md` §4.3 → §3): 100 experience reaches level 2
    // (thresholds 0, 100, 1500): level 2, next threshold 1500, the
    // sorceress' 5 stat points and 1 skill point per level, mana refilled
    // to its maximum (4000); life is not refilled (life 0 in this
    // fixture). Then the level-up seams (`Pending::level_up_notify`,
    // `level_up_event`).
    assert_eq!(fx.stat(player, LEVEL), 2);
    assert_eq!(fx.stat(player, NEXTEXP), 1500);
    assert_eq!(fx.stat(player, STATPTS), 5);
    assert_eq!(fx.stat(player, NEWSKILLS), 1);
    assert_eq!(fx.stat(player, 8), 4000);

    // 7. A stat point (C→S 0x3A, `vitals.md` §2): stat 0 (strength),
    // count − 1 = 0 (Open question 4 reads byte +2 so): one `spend`:
    // stat points 5 → 4, strength 0 → 1, result 0. No message (none is
    // written for it).
    let point = bytes(&AddStatPoint { stat: STRENGTH });
    assert_eq!(point, [0x3A, 0, 0]);
    record(&mut fx, &mut frames, vec![point]);
    let done = Some(ResultCode::Done);
    assert_eq!(frames[15].1.codes, [(0x3A, done)]);
    assert_eq!(frames[15].2, none);
    assert_eq!(fx.stat(player, STATPTS), 4);
    assert_eq!(fx.stat(player, STRENGTH), 1);

    // 5b. Pick-up of the kill's gold (C→S 0x16, `inventory.md` §7.1)
    // through the item-move handler on the host's inventories. STOP:
    // the gold is a unit of the game's unit lists in mode 3, but its
    // item record lives in the death drop's own item store
    // (`DeathDrops::items`, `host-merge.md` W-5), not in the host's one
    // store the inventory wiring reads, so the item lookup finds no item
    // data: "item missing" → 1, nothing changes, nothing is sent.
    let pick = bytes(&PickItem {
        type_: 4,
        id: fx.guid(gold),
        cursor: 0,
    });
    record(&mut fx, &mut frames, vec![pick]);
    assert_eq!(frames[16].1.codes, [(0x16, Some(ResultCode::Refused))]);
    assert_eq!(frames[16].2, none);
    assert!(fx.sim_ref().unhandled.is_empty());
    assert_eq!(fx.mode(gold), 3);
    assert_eq!(fx.sim_ref().game.lists.unit(gold).unwrap().room(), room);
    assert_eq!(fx.stat(gold, 14), amount);
    assert_eq!(fx.stat(player, GOLD), PLAYER_GOLD);
    assert!(fx.inv.with(|r| r.log.is_empty()));

    // 8. NPC talk (C→S 0x13, `npc.md` §2) with Akara: distance 3 (the
    // unit spec's distance, staged), the talk starts: interact unit (1,
    // GUID), S→C 0x27, 0x29, 0x28 in that order (§2 start step 5). 0x27
    // bytes 6–39 are the text-list encoder `0x00661480`'s
    // (`server-messages.tsv` 0x27 `partial`, staged zeros).
    let ng = fx.guid(fx.npc);
    let talk = bytes(&InteractWithEntity { type_: 1, id: ng });
    record(&mut fx, &mut frames, vec![talk]);
    assert_eq!(frames[17].1.codes, [(0x13, done)]);
    let mut npc_info = vec![0x27, 1];
    npc_info.extend_from_slice(&ng.to_le_bytes());
    npc_info.extend_from_slice(&[0; 34]);
    let mut game_quests = vec![0x29];
    game_quests.extend_from_slice(&fx.sim_ref().world.quests.game.0);
    let mut quest_info = vec![0x28, 1];
    quest_info.extend_from_slice(&ng.to_le_bytes());
    quest_info.push(0);
    quest_info.extend_from_slice(&fx.sim_ref().world.rest.quests[&player].flags[0].0);
    assert_eq!(frames[17].2, [npc_info, game_quests, quest_info]);
    assert_eq!(fx.sim_ref().world.rest.interact[&player], (1, ng));

    // 9. Chat (C→S 0x2F, §3): the heal hook (§5; nothing to heal). No
    // message.
    record(
        &mut fx,
        &mut frames,
        vec![bytes(&InitEntityChat { id: ng })],
    );
    assert_eq!(frames[18].1.codes, [(0x2F, done)]);
    assert_eq!(frames[18].2, none);

    // 10. Trade (C→S 0x38 action 1, `vendors.md` §4 → §3): the store is
    // generated on the NPC-control seed, its items made by the economy
    // wiring on the game seed (two steps per item, `rng.md` §5.3): 1–3
    // bucklers (Min 1, Max 3), then the permanent cap, each identified.
    // S→C 0x9C action 11 belongs to the unwritten item spec
    // (`add_trade_inventory` stub): no message.
    let seed_before = fx.sim_ref().events.action.sys.hooks.game_seed;
    let trade = bytes(&EntityAction {
        action: 1,
        npc: ng,
        item: 0,
    });
    record(&mut fx, &mut frames, vec![trade]);
    assert_eq!(frames[19].1.codes, [(0x38, done)]);
    assert_eq!(frames[19].2, none);
    let store = {
        let w = &fx.sim_ref().world;
        let rec = &w.state.vendors[w.state.vendor_index(class::AKARA).unwrap()];
        assert!(rec.has_traded && rec.store_generated);
        rec.store.clone()
    };
    assert!((2..=4).contains(&store.len()), "{store:?}");
    let mut seed = seed_before;
    for _ in 0..2 * store.len() {
        seed.step();
    }
    assert_eq!(fx.sim_ref().events.action.sys.hooks.game_seed, seed);
    let mut store_rows = Vec::new();
    for &item in &store {
        let guid = fx.guid(item);
        let ac = fx.stat(item, ARMORCLASS);
        let it = fx.sim_ref().world.items.get(item).unwrap();
        assert_ne!(it.flags & flag::IDENTIFIED, 0);
        store_rows.push((guid, it.record, it.item_seed, ac));
    }
    assert_eq!(store_rows.last().unwrap().1, CAP, "permanent codes last");
    assert!(store_rows[..store.len() - 1].iter().all(|r| r.1 == BUC));

    // 11. Buy (C→S 0x32) the store's cap with enough gold: rules 1–8
    // pass, the purchase copies the store item (§7.1 rule 9.2). STOP at
    // the item copy `0x0055A2A0` (`VendorRest::copy_item`, no items
    // spec writes it): its null runs the spec's refusal: S→C 0x2A code
    // 9, GUID −1, result 1; nothing paid.
    let store_cap = fx.guid(*store.last().unwrap());
    let buy = bytes(&BuyItem {
        npc: ng,
        item: store_cap,
        mode: 0,
        cost: 0,
    });
    record(&mut fx, &mut frames, vec![buy]);
    assert_eq!(frames[20].1.codes, [(0x32, Some(ResultCode::Refused))]);
    assert_eq!(frames[20].2, [tx(0, 9, u32::MAX, PLAYER_GOLD)]);
    assert_eq!(fx.stat(player, GOLD), PLAYER_GOLD);

    // 12. Sell (C→S 0x33) the player's buckler (re-sellable, not a
    // permanent code). STOP at §7.2 rule 8: the copy into the NPC is the
    // same unwritten `0x0055A2A0`: 0x2A code 9, GUID −1, result 3.
    let sell = |item| {
        bytes(&SellItem {
            npc: ng,
            item,
            tab: 0,
            cost: 0,
        })
    };
    let buckler = fx.guid(fx.buckler);
    record(&mut fx, &mut frames, vec![sell(buckler)]);
    assert_eq!(frames[21].1.codes, [(0x33, Some(ResultCode::Malformed))]);
    assert_eq!(frames[21].2, [tx(0, 9, u32::MAX, PLAYER_GOLD)]);

    // 13. Sell the player's cap: one of Akara's permanent codes, so no
    // copy (rule 8); rule 9's removal is the inventory stub
    // (`remove_stored`); rule 10 receives the price (§9.1, §9.2 by hand:
    // B = 100·AC/5, buy mult 512 → B·512/1024): 0x2A kind 3, code 1, the
    // cap's GUID, the new gold.
    let cap = fx.guid(fx.cap);
    let sold = (100 * fx.stat(fx.cap, ARMORCLASS) / 5) * 512 / 1024;
    assert!(sold > 0);
    record(&mut fx, &mut frames, vec![sell(cap)]);
    assert_eq!(frames[22].1.codes, [(0x33, done)]);
    assert_eq!(frames[22].2, [tx(3, 1, cap, PLAYER_GOLD + sold)]);
    assert_eq!(fx.stat(player, GOLD), PLAYER_GOLD + sold);
    assert!(!fx.sim_ref().world.rest.inventory.contains(&fx.cap));
    let copies = fx.sim_ref().world.rest.log.iter();
    let copies: Vec<&String> = copies.filter(|l| l.starts_with("copy")).collect();
    assert_eq!(copies.len(), 2, "the two stops at 0x0055A2A0");

    // TODO(after the quest-host merge): quest messages 0x31, 0x40, 0x58
    // on `WiredWorld` (`QuestCall`) are being added in parallel; until
    // then they stay stubs and this run sends none. The step goes here.

    // 14. Cube (C→S 0x2A, `cube.md` §2): the cursor ring into the
    // player's cube: the checks pass, the targeting reset, page 3, the
    // placement (inventory stub); result 0, no message. The cube runs on
    // the same host, units and item store as the rest of the run.
    let (cube, ring) = (fx.cube, fx.ring);
    let mut put = vec![0x2A];
    put.extend_from_slice(&fx.guid(ring).to_le_bytes());
    put.extend_from_slice(&fx.guid(cube).to_le_bytes());
    assert_eq!(
        put,
        bytes(&ItemToCube {
            item: fx.guid(ring),
            cube: fx.guid(cube)
        })
    );
    record(&mut fx, &mut frames, vec![put]);
    assert_eq!(frames[23].1.codes, [(0x2A, done)]);
    assert_eq!(frames[23].2, none);
    assert_eq!(fx.items().get(ring).unwrap().inv_page, CUBE_PAGE);
    assert_eq!(fx.cube_parts().staged.targeting_resets, [player]);
    assert_eq!(
        fx.cube_parts().staged.inventories[&player].items,
        [cube, ring]
    );

    // 15. Transmute (C→S 0x4F button 0x18, `cube.md` §1, §3, §8) with
    // the cube open. The cube's opening (item use, `cube.md` §10) has no
    // spec: the interaction (type 4, the cube's GUID) is staged at the
    // host's one owner. The ring matches the recipe: the amulet is
    // created, the ring removed and freed, sound 4, the amulet placed on
    // page 3, identified.
    let cg = fx.guid(cube);
    fx.sim().world.rest.interact.insert(player, (4, cg));
    let click = bytes(&ClickButton {
        button: 0x18,
        p1: 0,
        p2: 0,
    });
    assert_eq!(click, [0x4F, 0x18, 0, 0, 0, 0, 0]);
    record(&mut fx, &mut frames, vec![click]);
    assert_eq!(frames[24].1.codes, [(0x4F, done)]);
    assert_eq!(frames[24].2, none);
    assert!(!fx.items().contains(ring));
    let amulet = *fx.cube_parts().staged.inventories[&player]
        .items
        .last()
        .unwrap();
    let it = fx.items().get(amulet).unwrap().clone();
    assert_eq!(
        (it.record, it.quality, it.inv_page),
        (AMULET, q::NORMAL, CUBE_PAGE)
    );
    assert_ne!(it.flags & flag::IDENTIFIED, 0);
    assert_eq!(fx.cube_parts().staged.sounds, [(player, 4)]);
    assert_eq!(
        *fx.cube_rest.0.lock().unwrap(),
        [
            format!("place {}", ring.0),
            format!("remove {}", ring.0),
            format!("place {}", amulet.0)
        ]
    );
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());
    assert!(fx.sim_ref().unhandled.is_empty());

    // 6. Waypoint travel (C→S 0x49, `waypoints.md` §6–§7): accepted,
    // the interaction closed (rule 2), the destination bit tested (rule
    // 3), tile code 0 (rule 4), the warp called (rule 5), the spawn
    // search streamed the destination's room (rule 7's `0x00619E50`: 5
    // active rooms), the arrival node prepended (rule 8). STOP: the
    // warp's same-act placement `0x00554EA0` belongs to the unwritten
    // path / placement spec (`Pending::warp`), so the player stays in
    // the ISLE room and rule 7's room test sends no S→C 0x0D.
    fx.sim().world.rest.interact.insert(player, (2, wp));
    let travel = bytes(&TakeOrCloseWp {
        wp,
        level: GATE as u16,
    });
    let mut want = vec![0x49];
    want.extend_from_slice(&wp.to_le_bytes());
    want.extend_from_slice(&[GATE as u8, 0, 0, 0]);
    assert_eq!(travel, want);
    record(&mut fx, &mut frames, vec![travel]);
    assert_eq!(frames[25].1.codes, [(0x49, done)]);
    assert_eq!(frames[25].2, none);
    assert!(!fx.sim_ref().world.rest.interact.contains_key(&player));
    let log = fx.pending().log.clone();
    assert_eq!(log.last(), Some(&format!("warp {} {GATE} 0", player.0)));
    assert_eq!(fx.sim_ref().game.lists.active_rooms(0).len(), 5);
    let arrivals = &fx.sim_ref().world.action.arrivals.0;
    assert_eq!(arrivals.len(), 1);
    assert_eq!((arrivals[0].x, arrivals[0].y), PLAYER_AT);
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // 16–21. Item moves (`inventory.md` §7) on the host's inventories:
    // a cap on the ground beside the player, made by the economy wiring
    // on the game seed into the host's one item store (it stands in for
    // a drop into that store, W-5), identified, at (x + 1, y + 1).
    let cap = fx.ground_cap();
    let cg = fx.guid(cap);
    let pg = fx.guid(player);
    // The deferred item messages of §6 and §11 (the item bit stream is
    // the unwritten serialization spec's, `inventory.md` OQ1: empty),
    // then 0x47 and 0x48, in the frame's tick (§6.1).
    let x9c = |action: u8| {
        let mut b = vec![0x9C, action, 8, 0];
        b.extend_from_slice(&cg.to_le_bytes());
        b
    };
    let x9d = |action: u8| {
        let mut b = vec![0x9D, action, 13, 0];
        b.extend_from_slice(&cg.to_le_bytes());
        b.push(0);
        b.extend_from_slice(&pg.to_le_bytes());
        b
    };
    let pass = |m: Vec<u8>| {
        let mut r = vec![0x47, 0, 0];
        r.extend_from_slice(&pg.to_le_bytes());
        r.extend_from_slice(&[0; 4]);
        let mut r2 = r.clone();
        r2[0] = 0x48;
        vec![m, r, r2]
    };

    // 16. Pick-up to the cursor (C→S 0x16 cursor 1, §7.1 → §8.2): the
    // staged distance 3 (< 5), the cap leaves the room for the cursor
    // (mode 4) → 0x9C action 1.
    let pick = bytes(&PickItem {
        type_: 4,
        id: cg,
        cursor: 1,
    });
    record(&mut fx, &mut frames, vec![pick]);
    assert_eq!(frames[26].1.codes, [(0x16, done)]);
    assert_eq!(frames[26].2, pass(x9c(0x01)));
    assert_eq!(fx.mode(cap), 4);
    assert_eq!(fx.sim_ref().game.lists.unit(cap).unwrap().room(), None);

    // 17. Inventory placement (C→S 0x18, §7.3 → §2.4): at (0, 0) of page
    // 0 of the sorceress' 10 × 4 grid (record 1): mode 0 → 0x9C action 4.
    let insert = bytes(&InsertItemInBuffer {
        item: cg,
        x: 0,
        y: 0,
        page: 0,
    });
    record(&mut fx, &mut frames, vec![insert]);
    assert_eq!(frames[27].1.codes, [(0x18, done)]);
    assert_eq!(frames[27].2, pass(x9c(0x04)));
    assert_eq!(fx.mode(cap), 0);
    assert_eq!(fx.items().get(cap).unwrap().inv_page, 0);

    // 18. Back to the cursor (C→S 0x19, §7.4) → 0x9D action 5 (owner the
    // player).
    let lift = bytes(&RemoveItemFromBuffer { item: cg });
    record(&mut fx, &mut frames, vec![lift]);
    assert_eq!(frames[28].1.codes, [(0x19, done)]);
    assert_eq!(frames[28].2, pass(x9d(0x05)));
    assert_eq!(fx.mode(cap), 4);

    // 19. Equip on the head (C→S 0x1A location 1, §7.5 → §4.6): mode 1
    // → 0x9D action 6.
    let equip = bytes(&EquipItem {
        item: cg,
        bodyloc: 1,
    });
    record(&mut fx, &mut frames, vec![equip]);
    assert_eq!(frames[29].1.codes, [(0x1A, done)]);
    assert_eq!(frames[29].2, pass(x9d(0x06)));
    assert_eq!(fx.mode(cap), 1);

    // 20. Unequip (C→S 0x1C location 1, §7.7): to the cursor → 0x9D
    // action 8.
    let unequip = bytes(&RemoveBodyItem { bodyloc: 1 });
    record(&mut fx, &mut frames, vec![unequip]);
    assert_eq!(frames[30].1.codes, [(0x1C, done)]);
    assert_eq!(frames[30].2, pass(x9d(0x08)));
    assert_eq!(fx.mode(cap), 4);

    // 21. Drop (C→S 0x17, §7.2 → §9.1): no room at (x + 2, y + 3) (the
    // staged answer), so the search starts at the player; the staged
    // free-spot search answers that spot: the cap on the ground (mode 3,
    // in the player's room, at the player's position), the ITEMDROPPED
    // hook. No owner refresh, so no update pass; the ground message
    // (§6.3) is not built on real units (`wire-inventory-sim.md` WV1).
    let drop_msg = bytes(&DropItem { item: cg });
    record(&mut fx, &mut frames, vec![drop_msg]);
    assert_eq!(frames[31].1.codes, [(0x17, done)]);
    assert_eq!(frames[31].2, none);
    assert_eq!(fx.mode(cap), 3);
    let room = fx.sim_ref().game.lists.unit(player).unwrap().room();
    assert_eq!(fx.sim_ref().game.lists.unit(cap).unwrap().room(), room);
    assert_eq!(
        fx.inv.with(|r| r.log.clone()),
        [
            format!("quest_item_picked {cg}"),
            format!("pickup_sound {pg} {cg}"),
            format!("quest_item_dropped {cg}"),
        ]
    );
    assert!(fx.errors().is_empty(), "{:?}", fx.errors());

    // The client: 33 frames, 32 server ticks. The S→C messages it got
    // (0x27, 0x29, 0x28 once, 0x2A three times; 0x9C twice, 0x9D three
    // times, 0x47 and 0x48 five times each) have no client owner
    // yet (`bridge-dispatch.tsv`: every id TBD), so they are counted
    // unowned and no unit is in the model; nothing rejected or
    // discarded.
    let w = fx.bridge.world();
    let client = (w.frames, w.server_ticks, w.units.len());
    assert_eq!(client, (33, 32, 0));
    let log = fx.bridge.log();
    assert_eq!(
        log.unowned,
        BTreeMap::from([
            (0x27, 1),
            (0x28, 1),
            (0x29, 1),
            (0x2A, 3),
            (0x47, 5),
            (0x48, 5),
            (0x9C, 2),
            (0x9D, 3),
        ])
    );
    assert!(log.rejected.is_empty() && log.discarded.is_empty());

    let player_mana = fx.stat(player, 8);
    let player_exp = fx.stat(player, 13);
    let drops = fx
        .drops()
        .into_iter()
        .map(|(u, spot)| {
            let r = fx.sim_ref().events.action.sys.units.get(u).unwrap();
            (fx.guid(u), r.seed, spot.x, spot.y, r.mode)
        })
        .collect::<Vec<_>>();
    let gold = fx.drops().iter().map(|&(u, _)| fx.stat(u, 14)).collect();
    let skill_log = fx.book.get().log.clone();
    let player_stats = [LEVEL, STATPTS, STRENGTH, GOLD]
        .iter()
        .map(|&st| fx.stat(player, st))
        .collect();
    let cube_log = fx.cube_rest.0.lock().unwrap().clone();
    let inv_log = fx.inv.with(|r| r.log.clone());
    let s = fx.sim_ref();
    let x = &s.events.action.sys;
    Transcript {
        game_frame: s.game.frame,
        game_seed: x.hooks.game_seed,
        monsters: fx
            .monsters()
            .iter()
            .map(|&m| {
                (
                    fx.guid(m),
                    x.units.get(m).unwrap().seed,
                    x.hooks.x.pos[&m],
                    x.units.get(m).unwrap().mode,
                )
            })
            .collect(),
        active_rooms: s.game.lists.active_rooms(0),
        player_mode: fx.mode(player),
        player_mana,
        player_exp,
        drops,
        gold,
        pending_log: x.hooks.x.log.clone(),
        skill_log,
        player_stats,
        store: store_rows,
        npc_seed: s.world.npc.seed,
        rest_log: s.world.rest.log.clone(),
        cube_log,
        inv_log,
        unhandled: s.unhandled.clone(),
        client,
        errors: fx.errors(),
        frames,
    }
}

// Covers: specs/client/bridge.md §3 r1, §3 r2, §3 r3
#[test]
fn single_player_end_to_end() {
    let t = run();
    assert_eq!(t.game_frame, 32);
    assert_eq!(t.frames.len(), 32);
    assert_eq!(t.player_exp, 100);
    assert_eq!(t.drops.len(), 1);
    // Level 2, 4 stat points left, strength 1, gold after the cap sale.
    assert_eq!(t.player_stats[..3], [2, 4, 1]);
    assert!(t.player_stats[3] > PLAYER_GOLD);
}

/// Same seeds → the same run: every C→S byte, result code, S→C chunk,
/// seed, unit, room and log, twice.
#[test]
fn same_seed_same_run() {
    assert_eq!(run(), run());
}

/// The comparison sees the seed: another game seed gives other unit
/// seeds (`rng.md` §5.3), so the transcripts differ.
#[test]
fn other_seed_other_run() {
    let (a, b) = (run(), run_with(GAME_SEED + 1));
    assert_ne!(a.game_seed, b.game_seed);
    assert_ne!(a.monsters, b.monsters);
    assert_ne!(a.npc_seed, b.npc_seed);
    assert_ne!(a.store, b.store);
    // Up to the trade the wire is seed-independent; the store (its
    // size, so the GUIDs after it, and the ACs, so the prices) is not.
    assert_eq!(a.frames[..19], b.frames[..19]);
    let codes = |t: &Transcript| {
        t.frames
            .iter()
            .map(|f| f.1.codes.clone())
            .collect::<Vec<_>>()
    };
    assert_eq!(codes(&a), codes(&b));
}
