#!/usr/bin/env python3
# Spec: specs/tools/scenario-diff.md, specs/tools/poke.md
"""Writes the Nightmare / Hell Acts III-V monster checks of q-chk-difficulty-a3a5
to traces/checks/diff/. One check per (act, difficulty, kind): the act's
save at that difficulty, warp to a native level, spawn one act-native
monster (normal / champion / unique), state channel (hp, damage, resists,
level through the unit records), plus an items channel and a Fire Bolt
volley so drops are compared when the monster dies.
Levels and classes come from levels.txt (nmon1) and monstats.txt (hcIdx) of the
1.14d excel view: python3 tools/chk-difficulty/gen_diff.py [--excel DIR]"""
import argparse, csv, os, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "playthrough"))
import playthrough as pt  # DIFFS / DONE_SLOTS: the lower difficulties' quest bits (as the matrix saves)

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ACTS = {3: ("ScnAm3", 2, "acts=2", 76), 4: ("ScnAm4", 3, "acts=3", 105), 5: ("ScnAm5", 4, "acts=4", 115)}


def tsv(p):
    r = list(csv.reader(open(p, encoding="utf-8", newline=""), delimiter="\t"))
    return r[0], r[1:]


def qs(base, diff):
    done = []
    for lower in pt.DIFFS[:pt.DIFFS.index(diff)]:
        done.append(f"{lower}:acts=4")
        done += [f"{lower}:{slot}.0" for slot in pt.DONE_SLOTS]
    return ",".join([base] + done)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--excel", default=os.path.join(os.environ.get("D2_GAME_DIR", os.path.expanduser("~/game")), "extracted/patch_d2/data/global/excel"))
    ap.add_argument("--out", default=os.path.join(REPO, "traces/checks/diff"))
    a = ap.parse_args()
    lh, lr = tsv(os.path.join(a.excel, "levels.txt"))
    mh, mr = tsv(os.path.join(a.excel, "monstats.txt"))
    hc = {r[mh.index("Id")]: r[mh.index("hcIdx")] for r in mr}
    n = 0
    for act, (save, actn, quests, lvl) in ACTS.items():
        row = next(r for r in lr if r[lh.index("Id")] == str(lvl))
        mon = row[lh.index("nmon1")]
        cls = hc[mon]
        for diff in ("nightmare", "hell"):
            ml = row[lh.index("MonLvl2Ex" if diff == "nightmare" else "MonLvl3Ex")]
            for kind, extra, bm in [(k, e, b) for b in (False, True) for k, e in (("normal", ""), ("champion", " umod 16"), ("unique", " umod 19"))]:
                name = f"diff-a{act}-{'nm' if diff == 'nightmare' else 'hell'}-{kind}" + ("-bm" if bm else "")
                body = [
                    "check 1",
                    f"# GENERATED by tools/chk-difficulty/gen_diff.py. {diff.title()} Act {act}: level {lvl} ({row[lh.index('Name')]}, MonLvl {ml}),",
                    f"# {'Blood Moor warp under variant blood-moor-empty (isolates the stat formulas from level generation)' if bm else 'act level warp (level generation + population included)'}; nmon1 {mon} (class {cls}) spawned {kind}; compare hp / damage / resists / level (state) and drops (items).",
                    "# Spec: specs/tools/scenario-diff.md, specs/tools/poke.md. Do not edit: regenerate.",
                    f"name {name}",
                    f"save {save} --class ama --expansion --act {actn} --quests {qs(quests, diff)} --difficulty {diff} --difficulty-unlocked {diff}",
                    "seed 1234", f"difficulty {diff}", "ticks 400", "seconds 900", "channels state items",
                ] + (["variant blood-moor-empty-nh"] if bm else []) + [
                    "at 4 poke warp %d" % (2 if bm else lvl),
                    "at 30 poke seed-game 0x00001234 666",
                    "at 30 poke seed-unit @player 0x00000055 666",
                    f"at 30 poke spawn {cls} @x+4 @y+4 {kind}{extra}",
                ] + [f"at {t} poke missile 58 @x @y @x+4 @y+4 skill 36 20" for t in range(60, 360, 20)]
                with open(os.path.join(a.out, name + ".check"), "w") as f:
                    f.write("\n".join(body) + "\n")
                n += 1
    print(f"{n} checks in {a.out}")


main()
