//! Dev tool: records which local install our traces and specs come from.
//! Writes the names, sizes and SHA-256 hashes of the game files in `game/`
//! (no Blizzard content), so a trace that stops matching can be traced back
//! to a changed install. This is NOT the ownership gate and never ships:
//! players' installs are not compared against these hashes (see d2-verify).
//!
//! Usage:
//!   cargo run -p hash-manifest -- [GAME_DIR] [OUT_FILE]
//! GAME_DIR defaults to $D2_GAME_DIR; OUT_FILE defaults to
//! traces/reference-install.toml.

use anyhow::{bail, Context, Result};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

/// Version of the manifest file this tool writes.
const MANIFEST_FORMAT_VERSION: u32 = 1;
const GAME_VERSION: &str = "1.14d";

/// File extensions included in the manifest (archives and binaries; 1.14d
/// ships one merged `Game.exe` plus a few DLLs).
const EXTENSIONS: &[&str] = &["mpq", "exe", "dll"];

fn sha256_file(path: &Path) -> Result<(u64, String)> {
    let mut file = File::open(path).with_context(|| format!("opening {}", path.display()))?;
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; 1 << 20];
    let mut size = 0u64;
    loop {
        let n = file.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
        size += n as u64;
    }
    let hex = hasher.finalize().iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    });
    Ok((size, hex))
}

fn main() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let game_dir = match args.next() {
        Some(d) => PathBuf::from(d),
        None => {
            PathBuf::from(std::env::var("D2_GAME_DIR").context("pass GAME_DIR or set D2_GAME_DIR")?)
        }
    };
    let out = args
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("traces/reference-install.toml"));

    let mut files: Vec<PathBuf> = std::fs::read_dir(&game_dir)
        .with_context(|| format!("reading {}", game_dir.display()))?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_file())
        .filter(|p| {
            p.extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| EXTENSIONS.iter().any(|x| e.eq_ignore_ascii_case(x)))
        })
        .collect();
    if files.is_empty() {
        bail!("no .mpq/.exe/.dll files found in {}", game_dir.display());
    }
    // Sort by lowercase name so the manifest is stable across machines.
    files.sort_by_key(|p| p.file_name().unwrap().to_string_lossy().to_lowercase());

    let mut toml = format!(
        "# Generated by tools/hash-manifest. Names, sizes and SHA-256 only.\n\
         format_version = {MANIFEST_FORMAT_VERSION}\n\
         game_version = \"{GAME_VERSION}\"\n"
    );
    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy().to_lowercase();
        let (size, hash) = sha256_file(path)?;
        println!("{hash}  {size:>12}  {name}");
        let _ = write!(
            toml,
            "\n[[file]]\nname = \"{name}\"\nsize = {size}\nsha256 = \"{hash}\"\n"
        );
    }

    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&out, toml).with_context(|| format!("writing {}", out.display()))?;
    println!("wrote {} entries to {}", files.len(), out.display());
    Ok(())
}
