#!/usr/bin/env python3
"""Generate Horadric Cube transmute checks from cubemain.txt (q-chk-items-cube).

    python3 tools/checks/gen_cube.py --excel DIR --out DIR [--only N,N] [--list]

DIR is the live excel view (`$D2_GAME_DIR/extracted/patch_d2/data/global/excel`).
One `.check` file per enabled cubemain row: a save (ScnCube) with a cube in the
inventory and the row's inputs already in the cube page (`--item CODE:3`), then
the client's own messages: 0x20 UseGridItem on the cube (opens the cube,
specs/world/cube.md §1), 0x4F ClickButton 0x18 (transmute, §3). Both sides
(1.14d, d2rs) compare on the state + packets channels; the items channel
replaces that once it lands.

The files carry item codes and message fields only (our own inputs); no table
content is copied. Standard library only. Spec: specs/world/cube.md.
"""

import argparse
import csv
import os
import re
import sys


def table(excel, name):
    p = None
    for f in os.listdir(excel):
        if f.lower() == name.lower():
            p = os.path.join(excel, f)
    if p is None:
        sys.exit("no %s in %s" % (name, excel))
    with open(p, encoding="latin1", newline="") as f:
        rows = list(csv.reader(f, delimiter="\t"))
    h = rows[0]
    return [dict(zip(h, r)) for r in rows[1:]]


class Items:
    def __init__(self, excel):
        self.by_code = {}
        for fn in ("armor", "weapons", "misc"):
            for r in table(excel, fn + ".txt"):
                if r["code"]:
                    r["_file"] = fn
                    self.by_code[r["code"]] = r
        self.types = {r["Code"]: r for r in table(excel, "ItemTypes.txt") if r["Code"]}

    def is_type(self, tcode, want):
        """tcode equals want or inherits it through Equiv1/Equiv2."""
        seen, todo = set(), [tcode]
        while todo:
            t = todo.pop()
            if t == want:
                return True
            if t in seen or t not in self.types:
                continue
            seen.add(t)
            todo += [self.types[t]["Equiv1"], self.types[t]["Equiv2"]]
        return False

    def pick(self, want, flags):
        """A base item code for a cubemain item/type token."""
        if want in self.by_code:
            return want
        best = None
        for code, r in self.by_code.items():
            ok = want == "any" or self.is_type(r["type"], want) or (
                r.get("type2") and self.is_type(r["type2"], want))
            if not ok or r["spawnable"] == "0" or not r["name"]:
                continue
            if "bas" in flags and r["normcode"] != code:
                continue
            if "exc" in flags and r["ubercode"] != code:
                continue
            if "eli" in flags and r["ultracode"] != code:
                continue
            if "sock" in flags and r["gemsockets"] in ("", "0"):
                continue
            if r["_file"] == "misc" and want == "any":
                continue
            if best is None:
                best = code
        return best


QUAL = {"low": "low", "nor": "normal", "hiq": "superior", "mag": "magic",
        "set": "set", "rar": "rare", "uni": "unique", "crf": "crafted", "tmp": "rare"}


def item_args(items, token):
    """One input token -> [(save --item argument)] (count = qty)."""
    parts = token.split(",")
    base, flags = parts[0], parts[1:]
    qty = 1
    opts = []
    f2 = []
    for f in flags:
        m = re.match(r"qty=(\d+)$", f)
        if m:
            qty = int(m.group(1))
        elif f in QUAL:
            opts.append("q=" + QUAL[f])
        elif f == "sock":
            opts.append("sock=1")
            f2.append(f)
        elif f == "eth":
            opts.append("eth")
        elif f in ("bas", "exc", "eli"):
            f2.append(f)
        elif f in ("noe", "nos", "nor", "upg", "nru") or re.match(r"(pre|suf)=", f):
            pass
        else:
            raise ValueError("flag " + f)
    code = items.pick(base, f2)
    if code is None:
        raise ValueError("no base item for " + token)
    if "uni" in flags or "set" in flags:
        raise ValueError("unique/set input needs a row (idx): " + token)
    spec = code + ":3" + ("".join("/" + o for o in opts))
    return [spec] * min(qty, 6)


def gen_row(i, row, items):
    ins = []
    for k in range(1, 8):
        t = row["input %d" % k]
        if t:
            ins += item_args(items, t)
    return ins


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:30]


HEADER = """check 1
# Horadric Cube recipe {i}: {desc}
# cubemain row {i}: inputs {inp} -> output {out}. Generated by tools/checks/gen_cube.py
# (specs/world/cube.md §1-§8): ScnCube holds a cube (page 0) and the inputs (page 3)
# from the start; frame 4 opens the cube (0x20 UseGridItem, §1), frame 8 transmutes
# (0x4F ClickButton 0x18, §3). Compared: state + packets (0x9D action 5 per removed
# item, 0x9C action 4 per output, §8).
name {name}
save ScnCube --class ama --expansion {items}
seed 1234
ticks 24
seconds 300
channels state packets items
at 4 send UseGridItem item=@{cube_ref} x={cx} y={cy}
at 8 send ClickButton button=0x18 p1=0 p2=0
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--excel", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--only", default="")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--cube-ref", default="4", help="GUID reference of the cube item")
    a = ap.parse_args()
    items = Items(a.excel)
    only = {int(x) for x in a.only.split(",") if x}
    os.makedirs(a.out, exist_ok=True)
    made = skipped = 0
    for i, row in enumerate(table(a.excel, "cubemain.txt")):
        if only and i not in only:
            continue
        if row["enabled"] != "1":
            continue
        try:
            ins = gen_row(i, row, items)
        except ValueError as e:
            print("row %d skipped: %s" % (i, e))
            skipped += 1
            continue
        name = "cube-%03d-%s" % (i, slug(row["description"]))
        inputs = " ".join(row["input %d" % k] for k in range(1, 8) if row["input %d" % k])
        its = " ".join("--item %s" % s for s in ["box"] + ins)
        txt = HEADER.format(i=i, desc=row["description"].strip(), inp=inputs, out=row["output"],
                            name=name, items=its, cube_ref=a.cube_ref, cx=0, cy=0)
        if a.list:
            print(name, inputs, "->", row["output"])
            continue
        with open(os.path.join(a.out, name + ".check"), "w") as f:
            f.write(txt)
        made += 1
    print("generated %d, skipped %d" % (made, skipped))


if __name__ == "__main__":
    main()
