// Spec: specs/drlg/outdoor.md §2 (Act V placement), §11, §12; specs/drlg/outdoor-act3-act5.md §1, §5; specs/drlg/rooms.md §4.1
//! Act V on synthetic data, in CI (task `q-a5-fields`): the Act V-shaped
//! set ([`test_fixtures::act5`]) → `GameData` → act 4 created by the real
//! A5 / A5T placement → every outdoor level (Bloody Foothills, Frigid
//! Highlands, Arreat Plateau, Frozen Tundra) generated by the real Act V
//! build (barricade, ravine, entrances, caves, siege, border
//! substitution, prisons, specials) and streamed. No `Covers:` claim: the
//! data is made up, not 1.14d.

use std::path::PathBuf;
use std::sync::OnceLock;

use d2_sim::drlg::{room_flags, Drlg, DrlgError, RoomKind, TileRect};
use d2_sim::game::Game;
use test_fixtures::act5::{self, OUTDOOR, TOWN};
use test_fixtures::game::GameData;
use test_fixtures::install;

const INIT: u32 = 644_409_375;

fn data() -> &'static GameData {
    static D: OnceLock<GameData> = OnceLock::new();
    D.get_or_init(|| {
        let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
            .join(format!("act5-game-{}", std::process::id()));
        let i = install::build(&dir, &act5::act5()).unwrap_or_else(|e| panic!("{e}"));
        GameData::from_install(&i).unwrap_or_else(|e| panic!("{e}"))
    })
}

#[test]
fn the_act5_placement_links_the_levels() {
    let d = data();
    let (data, types) = d.level_types();
    let dr = Drlg::create(4, INIT, 0, TOWN, false, &data, &mut types.clone())
        .unwrap_or_else(|e| panic!("{e:?}"));
    assert!(
        types.borrow().errors.is_empty(),
        "{:?}",
        types.borrow().errors
    );
    let rect = |id| dr.level(dr.find_level(id).unwrap()).rect;
    // The vector of outdoor-act3-act5.md §1, §5 (same seed, same draws).
    assert_eq!(rect(109), TileRect::new(1000, 1000, 40, 40));
    assert_eq!(rect(110), TileRect::new(760, 1000, 240, 48));
    assert_eq!(rect(111), TileRect::new(600, 968, 160, 64));
    assert_eq!(rect(112), TileRect::new(440, 968, 160, 64));
    assert_eq!(rect(117), TileRect::new(2000, 1896, 160, 64));
}

#[test]
fn every_act5_outdoor_level_generates_and_streams() {
    let d = data();
    let (data, types) = d.level_types();
    let dr = Drlg::create(4, INIT, 0, TOWN, false, &data, &mut types.clone())
        .unwrap_or_else(|e| panic!("{e:?}"));
    let mut world = d2_sim::wiring::action::DrlgWorld {
        dungeon: Default::default(),
        data: data.clone(),
        tiles: Box::new(d.files.dt1.clone()),
        types: Box::new(types.clone()),
    };
    let mut game = Game::new();
    game.lists.ensure_act(4).unwrap();
    world.dungeon.acts[4] = Some(dr);
    for id in std::iter::once(TOWN).chain(OUTDOOR) {
        let (rooms, outdoor, wp) = world
            .with_act(4, &mut game.lists, |dr, svc| {
                let l = dr.get_or_alloc_level(svc.data, svc.types, id)?;
                if dr.level_rooms(l).is_empty() {
                    dr.generate_level(svc.data, svc.types, l)?;
                }
                let rooms = dr.level_rooms(l);
                for &r in &rooms {
                    dr.stream_room(svc, r)?;
                }
                let outdoor = rooms
                    .iter()
                    .filter(|&&r| dr.room(r).kind != RoomKind::Preset)
                    .count();
                let wp = rooms
                    .iter()
                    .filter(|&&r| dr.room(r).flags & room_flags::ANY_WAYPOINT != 0)
                    .count();
                Ok::<_, DrlgError>((rooms.len(), outdoor, wp))
            })
            .expect("act 4")
            .unwrap_or_else(|e| panic!("level {id}: {e:?} {:?}", types.borrow().errors));
        assert!(rooms > 0, "level {id}: no rooms");
        // The siege strip covers every cell of the 30 × 6 grid with 15
        // preset pieces (outdoor-act3-act5.md §5 r2); a 16 × 48 piece
        // streams as 2 × 6 rooms of 8 × 8 tiles.
        if id == 110 {
            assert_eq!((rooms, outdoor), (15 * 12, 0), "Bloody Foothills");
        }
        // No waypoint room flag: Act V's waypoints come from preset content.
        assert_eq!(wp, 0, "level {id} waypoint rooms");
        assert!(
            types.borrow().errors.is_empty(),
            "level {id}: {:?}",
            types.borrow().errors
        );
    }
}
