#!/usr/bin/env python3
"""Write one scenario-diff check per skill of barbarian, druid, assassin.

The pattern of traces/checks/{bar,dru,ass}-*.check (area F2): a level-30
expansion save with every skill at 20, the skill on the right button, one
right click in the Blood Moor. Skills with a melee or ranged reach get a
cow 4 sub-tiles away (aimed click); the others cast at the screen centre.
Passive skills get one check per class: a left-click attack with every
passive at 20 (a save with the synergies). Existing checks are kept.

  gen_skill_checks.py [--out traces/checks] [--excel DIR]
Spec: specs/tools/scenario-diff.md (format); inputs: the live excel view
(skills.txt) from D2_GAME_DIR; writes names, ids and numbers only.
"""
import argparse, csv, os, re, glob

CLS = {"bar": ("ScnBar", "Barbarian"), "dru": ("ScnDru", "Druid"), "ass": ("ScnAss", "Assassin")}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="traces/checks")
    ap.add_argument("--excel", default=os.path.join(os.environ.get("D2_GAME_DIR", os.path.expanduser("~/game")),
                    "extracted/patch_d2/data/global/excel"))
    a = ap.parse_args()
    rows = list(csv.reader(open(os.path.join(a.excel, "skills.txt"), encoding="latin1"), delimiter="\t"))
    ix = {n: i for i, n in enumerate(rows[0])}
    have = set()
    for f in glob.glob(os.path.join(a.out, "*.check")):
        m = re.search(r"--right-skill (\d+)", open(f).read())
        if m:
            have.add(int(m.group(1)))
    made = 0
    for r in rows[1:]:
        if len(r) < len(rows[0]) - 5 or r[ix["charclass"]] not in CLS:
            continue
        c = r[ix["charclass"]]
        sid = int(r[ix["Id"]]); name = r[ix["skill"]]
        if r[ix["passive"]] == "1" or sid in have:
            continue
        reach = r[ix["range"]] != "none"
        write(a.out, c, f"{c}-{slug(name)}", name, sid, reach, None)
        made += 1
    for c, (ch, cn) in CLS.items():
        write(a.out, c, f"{c}-passives", "every passive at 20", None, True, 0)
        made += 1
    print(f"{made} checks written (existing ones kept)")


def write(out, c, name, label, sid, cow, left):
    path = os.path.join(out, name + ".check")
    if os.path.exists(path):
        return
    ch, cn = CLS[c]
    if left is None:
        skill = f" --right-skill {sid}"
        click = "rclick 544 336" if cow else "rclick 330 300"
        what = f"{label} ({'aimed at a cow 4 sub-tiles away' if cow else 'cast at the screen centre'})"
    else:
        skill = ""
        click = "move 544 336; frame 20; click 544 336"
        what = "left-click attack on a cow with every passive and synergy at 20"
    cowline = "at 10 poke spawn 179 @x+4 @y normal\n" if cow else ""
    open(path, "w").write(f"""check 1
# {what}: {ch} (expansion {cn}, level 30, every skill at 20{', right skill %d' % sid if sid else ''}),
# -seed 1234; warp to the Blood Moor (level 2; variant blood-moor-empty)
# before frame 4, then {'a cow (class 179, AI Idle) before frame 10, then ' if cow else ''}one click at client pixel before frame 20's drain.
# Compares the cast (mode, states, stats), its missiles' or summons' effects
# and the draws. Generated by tools/scenario-diff/gen_skill_checks.py.
# Spec: specs/tools/scenario-diff.md.
name {name}
save {ch} --class {c} --expansion --level 30 --all-skills 20{skill}
seed 1234
ticks 70
seconds 300
channels state
variant blood-moor-empty
at 4 poke warp 2
{cowline}input frame {"19" if left is not None else "20"}; {click}
""")


main()
