"""Generate the items-drops-* checks (q-chk-items-drops): one representative
monster per distinct monstats TreasureClass1 column of a difficulty, five per
check, each killed with Fire Bolts; the items channel compares every dropped
item (S->C 0x9C bit streams, creation order) with 1.14d.

    python3 tools/scenario-diff/gen_drop_checks.py EXCEL_DIR [--out traces/checks]

EXCEL_DIR: the live excel view (`data-tool excel-dir`). Our own code; reads
the user's tables, writes only poke lines and class numbers."""
import csv, os, sys

OFFS = [(4, 0), (0, 4), (-4, 0), (0, -4), (4, 4)]
COLS = {"normal": "TreasureClass1", "nightmare": "TreasureClass1(N)", "hell": "TreasureClass1(H)"}


def rel(v, a):
    return a if v == 0 else "%s%+d" % (a, v)


def reps(excel, col):
    r = list(csv.reader(open(os.path.join(excel, "monstats.txt"), encoding="latin1"), delimiter="\t"))
    i = {n: k for k, n in enumerate(r[0])}
    seen = {}
    for x in r[1:]:
        if (x[i["hcIdx"]].isdigit() and x[i["enabled"]] == "1" and x[i["killable"]] == "1"
                and x[i["npc"]] != "1" and x[i[col]]):
            seen.setdefault(x[i[col]], (int(x[i["hcIdx"]]), x[i["Id"]]))
    return sorted(seen.items(), key=lambda kv: kv[1][0])


KINDS = [("cha", "champion umod 16"), ("uni", "unique umod 5 7"), ("rbo", "random-boss")]


def kinds_checks(excel, out):
    """champion / unique / random-boss drops: 3 monsters per check, every 4th
    TreasureClass1 representative (normal difficulty)."""
    BOSSES = {"andariel", "duriel", "mephisto", "diablo", "summoner", "izual", "radament", "bloodraven", "griswold",
              "smith", "hephasto", "diabloclone", "nihlathakboss", "baalcrab", "flyingscimitar", "hellbovine", "vilemother3",
              "regurgitator3", "councilmember1", "trappedsoul1"}
    rs = [r for r in reps(excel, COLS["normal"]) if r[1][1] not in BOSSES][::3]
    for tag, kind in KINDS:
        for n in range(0, len(rs), 3):
            grp = rs[n:n + 3]
            name = "items-drops-%s-%02d" % (tag, n // 3)
            L = ["check 1", "# q-chk-items-drops (generated by tools/scenario-diff/gen_drop_checks.py): %s drops;" % kind,
                 "# classes %s (TreasureClass1 %s); the boss (and its minions) killed by Fire Bolts, drops compared by the items channel." % (
                     " ".join(str(c[0]) for _, c in grp), ", ".join(tc for tc, _ in grp)),
                 "# Spec: specs/items/treasure.md §3, specs/monsters/population.md §6.",
                 "name " + name, "save ScnAma --class ama --expansion", "seed 1234", "ticks 400", "seconds 500",
                 "channels items", "at 4 poke warp 2", "at 30 poke seed-game 0x00001234 666",
                 "at 30 poke seed-unit @player 0x00000055 666"]
            for k, (_, (cls, _id)) in enumerate(grp):
                dx, dy = OFFS[k]
                L.append("at 30 poke spawn %d %s %s %s" % (cls, rel(dx + (1 if dx > 0 else -1 if dx < 0 else 0), "@x"), rel(dy, "@y"), kind))
            f = 34
            for k in range(len(grp)):
                dx, dy = OFFS[k]
                for _ in range(12):
                    L.append("at %d poke missile 58 @x @y %s %s skill 36 40" % (f, rel(dx, "@x"), rel(dy, "@y"))); f += 6
            open(os.path.join(out, name + ".check"), "w").write("\n".join(L) + "\n")
            print(name, [c[1] for _, c in grp])


def main():
    excel = sys.argv[1]
    out = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else "traces/checks"
    # nightmare / hell run on 1.14d too since autostart.py writes the check's difficulty into
    # the game config (q-tool-autostart-difficulty); `--normal-only` skips them.
    kinds_checks(excel, out)
    for diff, col in COLS.items():
        if diff != "normal" and "--normal-only" in sys.argv:
            continue
        rs = reps(excel, col)
        for n in range(0, len(rs), 5):
            grp = rs[n:n + 5]
            name = "items-drops-%s-%02d" % (diff[:3], n // 5)
            L = ["check 1",
                 "# q-chk-items-drops (generated by tools/scenario-diff/gen_drop_checks.py): %s monsters," % diff,
                 "# one per TreasureClass1 value (%s)," % ", ".join(tc for tc, _ in grp),
                 "# classes %s; killed by Fire Bolts in the Blood Moor, drops compared by the items channel." %
                 " ".join(str(c[0]) for _, c in grp),
                 "# Spec: specs/items/treasure.md §3, specs/tools/scenario-diff.md §3 rule 13.",
                 "name " + name, "save ScnAma --class ama --expansion" + ("" if diff == "normal" else " --difficulty-unlocked %s --difficulty %s" % (diff, diff)),
                 "difficulty " + diff, "seed 1234", "ticks 260", "seconds 400", "channels items",
                 "at 4 poke warp 2", "at 30 poke seed-game 0x00001234 666",
                 "at 30 poke seed-unit @player 0x00000055 666"]
            for k, (_, (cls, _id)) in enumerate(grp):
                dx, dy = OFFS[k]
                L.append("at 30 poke spawn %d %s %s normal" % (cls, rel(dx, "@x"), rel(dy, "@y")))
            f = 34
            for k in range(len(grp)):
                dx, dy = OFFS[k]
                for _ in range(6):
                    L.append("at %d poke missile 58 @x @y %s %s skill 36 40" % (f, rel(dx, "@x"), rel(dy, "@y"))); f += 6
            open(os.path.join(out, name + ".check"), "w").write("\n".join(L) + "\n")
            print(name, [c[1] for _, c in grp])


main()
