"""Generate the items-vendor-<npc>-* checks (q-chk-items-drops): for every
trading / gambling NPC of specs/world/vendors.tsv, warp to its town, `goto`
the NPC, open trade (0x38 action 1) and/or gamble (action 2); the items
channel compares the store / gamble stock item by item with 1.14d.

    python3 tools/scenario-diff/gen_vendor_checks.py [--out traces/checks]
Our own code; reads only the public spec table."""
import csv, os, sys

TOWN = {0: None, 1: 40, 2: 75, 3: 103, 4: 109}  # act -> town level (act 1: start)
ACT = {0: 1, 1: 2, 2: 3, 3: 4, 4: 5}


def main():
    out = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else "traces/checks"
    here = os.path.dirname(os.path.abspath(__file__))
    rows = list(csv.DictReader(open(os.path.join(here, "..", "..", "specs", "world", "vendors.tsv")), delimiter="\t"))
    for r in rows:
        trade, gamble = r["trade_action"] == "1", r["gamble_action"] == "1"
        if not (trade or gamble):
            continue
        npc, act = int(r["npc"]), int(r["act"])
        name = "items-vendor-%s-stock" % r["name"]
        L = ["check 1", "# q-chk-items-drops (generated by tools/scenario-diff/gen_vendor_checks.py): %s" % r["name"],
             "# (npc %d, act %d): warp to the town, goto the NPC, open %s; the items channel" % (
                 npc, ACT[act], " + ".join(x for x, f in (("trade", trade), ("gamble", gamble)) if f)),
             "# compares every stocked item (S->C 0x9C) with 1.14d. Spec: world/vendors.md §3-§5.",
             "name " + name, "save ScnBuy --class ama --expansion --gold 5000", "seed 1234", "ticks 140",
             "seconds 400", "channels items"]
        f = 4
        if TOWN[act]:
            L.append("at 4 poke warp %d" % TOWN[act]); f = 12
        L.append("at %d poke goto unit %d" % (f, npc)); f += 50
        L += ["at %d send InteractWithEntity type=1 id=@1:%d" % (f, npc), "at %d send InitEntityChat id=@1:%d" % (f + 2, npc)]
        f += 4
        if trade:
            L.append("at %d send EntityAction action=1 npc=@1:%d item=0" % (f, npc)); f += 12
        if gamble:
            L.append("at %d send EntityAction action=2 npc=@1:%d item=0" % (f, npc))
        open(os.path.join(out, name + ".check"), "w").write("\n".join(L) + "\n")
        print(name)


main()
