#!/usr/bin/env python3
"""Turn a suite.py --json result into docs/handoff/checks-status.md: per check
and channel the verdict, frames equal/compared, the first divergence and its
owner (tools/coord/route.py).

    python3 tools/scenario-diff/status_md.py SUITE.json [-o docs/handoff/checks-status.md] [--rev REV]

Standard library only. Our own code. Spec: specs/tools/scenario-diff.md §4.
"""
import argparse
import collections
import json
import os
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def routes(check):
    res = os.path.join(REPO, check["work"], "result.json")
    if not os.path.exists(res):
        return {}
    p = subprocess.run([sys.executable, os.path.join(REPO, "tools", "coord", "route.py"), "--json", res],
                       capture_output=True, text=True)
    try:
        rs = json.loads(p.stdout)["routes"]
    except (ValueError, KeyError):
        return {}
    return {r["channel"]: r for r in rs}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("suite_json")
    ap.add_argument("-o", default=os.path.join(REPO, "docs", "handoff", "checks-status.md"))
    ap.add_argument("--rev", default="")
    a = ap.parse_args()
    d = json.load(open(a.suite_json))
    rows, owners, counts = [], collections.Counter(), collections.Counter()
    for c in d["checks"]:
        rt = routes(c)
        if c.get("error") or not c["channels"]:
            counts["ERROR"] += 1
            rows.append(f"| {c['name']} | - | ERROR | - | {c.get('error')} | - |")
            continue
        for ch, r in c["channels"].items():
            s = r["summary"]
            v = r["verdict"]
            counts[v] += 1
            first = (s.get("first") or {}).get("text", "-")
            own = "-"
            if first != "-" and ch in rt:
                o = rt[ch].get("owner") or {}
                own = (o.get("branch") or "unrouted").replace("claude/", "")
                owners[own] += 1
            rows.append(f"| {c['name']} | {ch} | {v} | {s.get('frames_equal')}/{s.get('frames_compared')} "
                        f"| {first.replace('|', '/')} | {own} |")
    out = [f"# 1.14d check status (generated by tools/scenario-diff/status_md.py)", "",
           f"Suite run {d['date']}{' at ' + a.rev if a.rev else ''}: `{d['command']}`.",
           f"{len(d['checks'])} checks, {sum(counts.values())} channel results: "
           + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + ".",
           "PARTIAL = every compared frame equal but a part of the channel is not compared "
           "(spec scenario-diff.md §3); not a match.", "",
           "First divergences by owner branch: " + ", ".join(f"{k} {v}" for k, v in owners.most_common()), "",
           "| Check | Channel | Verdict | Frames equal | First divergence | Owner |", "|---|---|---|---|---|---|"]
    open(a.o, "w").write("\n".join(out + rows) + "\n")
    print(a.o, len(rows), "rows")


main()
