#!/usr/bin/env python3
"""Writes one level-warp check per level of levels.txt (the a*-warp-* pattern of
traces/checks: save of the level's act, idle in town to frame 20, `poke warp N`,
channels state rng). Skips levels that already have a hand-written warp check.

    python3 tools/chk-levels/gen_level_checks.py [--excel DIR] [--out DIR] [--check]
    python3 tools/chk-levels/gen_level_checks.py --selftest

Names: a<act>-warp-L<id>-<slug>-ama (generated files carry a header naming the
row). Standard library only. Our own code. Spec: specs/tools/scenario-diff.md, poke.md (warp)."""
import argparse, glob, os, re, sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SAVES = {0: "save ScnAma --class ama --expansion",
         1: "save ScnAm2 --class ama --expansion --act 1 --quests acts=1",
         2: "save ScnAm3 --class ama --expansion --act 2 --quests acts=2",
         3: "save ScnAm4 --class ama --expansion --act 3 --quests acts=3",
         4: "save ScnAm5 --class ama --expansion --act 4 --quests acts=4"}
VERSION = "gen-level-checks-1"

def read_levels(excel):
    with open(os.path.join(excel, "levels.txt"), encoding="latin-1") as f:
        rows = [l.rstrip("\r\n").split("\t") for l in f]
    h = rows[0]; ci = {n: h.index(n) for n in ("Name", "Id", "Act")}
    out = []
    for r in rows[1:]:
        if len(r) <= ci["Act"] or not r[ci["Id"]].isdigit() or r[ci["Name"]] in ("", "Expansion"):
            continue
        i = int(r[ci["Id"]])
        if i == 0:
            continue
        out.append((i, r[ci["Name"]], int(r[ci["Act"]])))
    return out

def slug(n):
    return re.sub(r"[^a-z0-9]+", "-", n.lower()).strip("-")

def existing_warps(checks):
    s = set()
    for p in glob.glob(os.path.join(checks, "*.check")):
        txt = open(p).read()
        if os.path.basename(p).startswith("a") and "-warp-L" in p:
            continue  # ours
        s.update(int(m) for m in re.findall(r"^at \d+ poke warp (\d+)", txt, re.M))
    return s

def render(i, name, act, excel_ver="levels.txt"):
    # act of the save = the level's own act (Act column), Act V hell rows keep their column value
    nm = "a%d-warp-L%d-%s-ama" % (act + 1, i, slug(name.split(" - ", 1)[-1]))
    body = ["check 1",
            "# GENERATED by tools/chk-levels/gen_level_checks.py (%s) from levels.txt row Id %d (%s)." % (VERSION, i, name),
            "# Level warp (poke warp %d, tile 0) after idle in town until frame 20; compare the" % i,
            "# generated level and its populated units and the draws (a*-warp-* pattern).",
            "name " + nm, SAVES[act], "seed 1234", "ticks 160", "seconds 900",
            "channels state rng", "at 20 poke warp %d" % i]
    return nm, "\n".join(body) + "\n"

def generate(excel, out, checks):
    have = existing_warps(checks)
    made = []
    for i, name, act in read_levels(excel):
        if i in have:
            continue
        nm, txt = render(i, name, act)
        made.append((nm, txt))
    return made

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--excel", default=os.path.expanduser("~/game/extracted/patch_d2/data/global/excel"))
    ap.add_argument("--out", default=os.path.join(REPO, "traces", "checks"))
    ap.add_argument("--check", action="store_true", help="fail when the files are not current")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    made = generate(a.excel, a.out, os.path.join(REPO, "traces", "checks"))
    bad = 0
    for nm, txt in made:
        p = os.path.join(a.out, nm + ".check")
        cur = open(p).read() if os.path.exists(p) else None
        if a.check:
            bad += cur != txt
        elif cur != txt:
            open(p, "w").write(txt)
    print("%d level checks%s" % (len(made), " (%d stale)" % bad if a.check else ""))
    return 1 if bad else 0

def selftest():
    import tempfile
    d = tempfile.mkdtemp(); ex = os.path.join(d, "ex"); ck = os.path.join(d, "ck"); os.mkdir(ex); os.mkdir(ck)
    open(os.path.join(ex, "levels.txt"), "w").write(
        "Name\tId\tAct\nNull\t0\t0\nAct 1 - Town\t1\t0\nAct 1 - Cave 1\t8\t0\n\tExpansion\t\nAct 2 - Arcane\t74\t1\n")
    open(os.path.join(ck, "x.check"), "w").write("check 1\nat 20 poke warp 8\n")
    m = dict(generate(ex, ck, ck))
    assert sorted(m) == ["a1-warp-L1-town-ama", "a2-warp-L74-arcane-ama"], sorted(m)
    assert "poke warp 74" in m["a2-warp-L74-arcane-ama"] and "ScnAm2" in m["a2-warp-L74-arcane-ama"]
    print("selftest ok"); return 0

if __name__ == "__main__":
    sys.exit(main())
